### ISSUE TITLE
Driver: Databricks

### ISSUE THREAD

**Issue by rafaelleinio** [metabase/metabase#10029]
Hi, I'm trying to connect Metabase in my data source that is in Databricks.
I tried to use the SparkSQL connector that comes with Metabase but didn't work. Metabase generates a slightly different jdbc connection url that it should be, Metabase generates a url that begins with `jdbc:hive2` but Databricks requires a connection that starts with `jdbc:spark`.

Databricks provide a Simba Spark JDBC Driver to use for connection. I already used this driver to connect in Databricks with other BI tools and IDEs like Datagrip for example and works perfectly, so I think must be a way to configure Metabase to use this "custom" driver jar to connect to Databricks.

If anyone wants to download the simba driver they provide: http://info.databricks.com/do0hZ6qCUq0Sj00Mjk000Y0

Someone already did something related to that and can help me? Thanks!

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by marcusos** [comment]
We are having the same kind of problem too. We are trying to connect to databricks using metabase but as  @rafaelleinio said, Databricks needs Simba connector in order to connect properly. The default hive connector does not work on spark databricks.

**Comment by victor-lucio** [comment]
Same problem here, an excellent tool with some serious limitations :(

**Comment by butterflysky** [comment]
I've not used Metabase; I just stumbled on this accidentally while searching for a way to connect to Databricks using a Hive JDBC driver. I managed to get a working connection to my Databricks Spark cluster using version 1.2.2 of the Hive JDBC driver; I tried to use a newer version but that failed due to a Thrift protocol mismatch, so I did some research and determined Spark forked their embedded Hive server from the 1.2 series.

**Comment by leandrohmvieira** [comment]
Looking for Databricks support as well.

**Comment by fernando-goncalves-ifood** [comment]
Hey guys,

I did a fork and implemented the databricks driver, based on sparksql driver.
I'm using it in production here at iFood and it's working pretty well, and I have plans to open a PR to the main metabase repo.

The fork is here:
https://github.com/ifood/metabase/commits/databricks-driver

And you can compare the changes here:
https://github.com/ifood/metabase/compare/e31a9428b4b48bce38c47b45b670da603123901a...ifood:databricks-driver?expand=1

Hope that it helps!

**Comment by flamber** [comment]
Hi @fernando-goncalves-ifood 
Awesome - just a couple of inputs. No need to do a PR for the driver, since third-party drivers are supported as modules. Have a look at #9348 for useful links and driver documentation.
You might want to have a look at a couple of other driver repos as examples:
https://github.com/dludwig-jrt/metabase-db2-driver
https://github.com/enqueue/metabase-clickhouse-driver
https://github.com/dacort/metabase-athena-driver

**Comment by fernando-goncalves-ifood** [comment]
Done!

The driver is a external metabase module now:
https://github.com/ifood/metabase-sparksql-databricks-driver

I also provided an easy way to build using docker (see the `README.md`).

I hope it helps you guys!

And thanks @flamber for the inputs!

**Comment by BenderV** [comment]
@fernando-goncalves-ifood The module seems gone (repo is 404). Normal ?

**Comment by fhsgoncalves** [comment]
@BenderV I'm sorry for that, there were some issues with the privacy team here in iFood.
Meanwhile, I've forked it here https://github.com/fhsgoncalves/metabase-sparksql-databricks-driver.

**Comment by guilhermeLira** [comment]
We are having the same kind of problem too, did you can to solve this? Anyone can help me?

**Comment by fhsgoncalves** [comment]
@guilhermeLira you can use this driver:
https://github.com/fhsgoncalves/metabase-sparksql-databricks-driver

The `README.md` file on the repo contains instructions for install the driver!

I hope it helps! :)

**Comment by guilhermeLira** [comment]
OK, thanks @fhsgoncalves, I'll test this.

**Comment by chandanmanjunath** [comment]
Please follow below link, hope it helps.

[https://discourse.metabase.com/t/connecting-databricks-spark-to-metabase/6274 ](url)

**Comment by ValdarT** [comment]
Thank you for the driver, @fhsgoncalves! I managed to connect to the Databricks cluster but syncing the tables failed: I can see all of the tables in the database but they are all empty (i.e., no columns). Metabase v0.38.1, Databricks runtime 8.0.

**Comment by nmuldoon** [comment]
This is blocking a migration to Metabase Hosted. Would be great to get this officially supported and included in the distribution.

**Comment by jeffj** [comment]
An official Metabase instance that supports Databicks is blocking our company as well. I'd love to see it in the road map.

**Comment by coutoreis** [comment]
We have by now many requests about this feature. Is there any way to prioritize this request?

**Comment by flamber** [comment]
Here's the list of driver requests based on their upvotes (click :+1: on the first post of issues):
https://github.com/metabase/metabase/issues?q=is%3Aissue+is%3Aopen+label%3ADatabase%2F+label%3A%22Type%3ANew+Feature%22+sort%3Areactions-%2B1-desc

Including another driver in the official release is much more work than people think. This driver is currently not on our roadmap.

**Comment by ValdarT** [comment]
> Including another driver in the official release is much more work than people think. This driver is currently not on our roadmap. 

As far as I understand any Spark compatible client should work so it might be very little work to support Databricks after Spark driver is [updated to support recent versions of Spark](https://github.com/metabase/metabase/issues/11023). If so then it's more about making the Spark driver work rather than adding a new one.

Considering how popular Spark is and that it's supposed to be supported already, I find it very surprising that it's not prioritized.

**Comment by ValdarT** [comment]
For anyones else ending up here: this fork of the community driver worked for me (the one linked in [documentation](https://www.metabase.com/docs/latest/developers-guide-drivers.html) did not): https://github.com/rajeshkumarravi/metabase-sparksql-databricks-driver

**Comment by jcity** [comment]
@ValdarT did you need to set up a SQL Endpoint to get this to connect?

**Comment by relferreira** [comment]
I've merged [rajeshkumarravi](https://github.com/rajeshkumarravi) version and made other adjustments and now I think it is working on Metabase v0.43. 

https://github.com/relferreira/metabase-sparksql-databricks-driver

**Comment by dominic-teo-db** [comment]
Hi @relferreira, was wondering if we could have a quick chat on your solution?

**Comment by relferreira** [comment]
Of course, @dominic-teo-db, feel free to email me

**Comment by dey-abhishek** [comment]
Hi Metabase team, Can you provide a rough timeline for official Databricks driver support?

**Comment by snarfed** [comment]
Thank you again for updating your driver @relferreira! I've upgraded to your 1.3.0 jar, and it's closer to working, but still not quite there yet. When I enter my Databricks info on the Add Database page and click Save, it looks like it connects ok, but then Metabase's initial `SELECT 1` test query fails. Log snippet:

```
2022-08-11 17:44:11,174 DEBUG middleware.log :: POST /api/database 400 6.1 s (1 DB calls) 
{:message
 "[Simba][SparkJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: TStatus(statusCode:ERROR_STATUS, infoMessages:[*org.apache.hive.service.cli.HiveSQLException:Configuration let-user-control-scheduling is not available...
```

The odd part is, that exception seems to be coming from Databricks - I don't see any `org.apache.hive.service.cli.*` classes in either the Metabase or driver jars - but [`let-user-control-scheduling` is a Metabase setting](https://github.com/metabase/metabase/blob/5edfbdb68f766b4dba33d80ce2172a48520fe81a/src/metabase/driver/common.clj#L140-L146). @relferreira is the driver passing that Metabase setting through to the server somehow? Or am I misreading the log here?

(I've tried on Metabase versions 0.43.1 and 0.44, on Mac OS X.)

**Comment by relferreira** [comment]
Hello @snarfed 
I've tested now using v0.43.4 and it seems to be working.
Some details of how I'm using:
- I'm running with docker.
- I'm using an admin user of Databricks. Maybe your user doesn't have permission to start a cluster that is not already running.
- I'm connecting directly to the cluster with its JDBC URL. I think that the SQL endpoint doesn't work by now.

If it doesn't work, feel free to send me an e-mail.
Unfortunately, it is really expensive for me to maintain a Databricks cluster working, so I try to not use it much :(

**Comment by snarfed** [comment]
Thank you @relferreira! I was using our SQL Endpoint (now called SQL Warehouse)'s JDBC string. I switched to our cluster's JDBC string, and worked through a few other issues, and finally got it working. Awesome!

One note, the plugin evidently also requires Java 11, the version in the Metabase Docker image. I tried with OpenJDK 18.0.1.1 and got this exception when I tried to add the Databricks database:

```
2022-08-12 07:34:36,385 ERROR api.database :: Cannot connect to Database
java.lang.Exception: [Simba][SparkJDBCDriver](500618) Error occured while deserializing arrow data: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
Caused by: java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
	at com.simba.spark.jdbc42.internal.io.netty.util.internal.PlatformDependent.directBuffer(PlatformDependent.java:495)
	at com.simba.spark.jdbc42.internal.io.netty.buffer.NettyArrowBuf.getDirectBuffer(NettyArrowBuf.java:257)
	at com.simba.spark.jdbc42.internal.io.netty.buffer.NettyArrowBuf.nioBuffer(NettyArrowBuf.java:247)
	at com.simba.spark.jdbc42.internal.io.netty.buffer.ArrowBuf.nioBuffer(ArrowBuf.java:248)
	at com.simba.spark.jdbc42.internal.apache.arrow.vector.ipc.ReadChannel.readFully(ReadChannel.java:88)
	at com.simba.spark.jdbc42.internal.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:692)
	at com.simba.spark.jdbc42.internal.apache.arrow.vector.ipc.message.MessageSerializer.deserializeRecordBatch(MessageSerializer.java:346)
	at com.simba.spark.spark.arrow.ArrowBuffer.deserializeBatch(Unknown Source)
	at com.simba.spark.spark.arrow.ArrowBuffer.handleInitializeBuffer(Unknown Source)
	at com.simba.spark.hivecommon.api.HiveServer2BaseBuffer.initializeBuffer(Unknown Source)
	at com.simba.spark.hivecommon.api.RowsetBuffer.initializeBuffer(Unknown Source)
	at com.simba.spark.hivecommon.api.HS2Client.getRowSetInformation(Unknown Source)
	at com.simba.spark.hivecommon.api.HS2Client.fetchFromServer(Unknown Source)
	at com.simba.spark.spark.jdbc.DowloadableFetchClient.fetchNRows(Unknown Source)
	at com.simba.spark.hivecommon.api.HS2Client.fetchRows(Unknown Source)
	at com.simba.spark.hivecommon.dataengine.BackgroundFetcher.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-08-12 07:34:37,174 DEBUG middleware.log :: POST /api/database 400 2.3 s (1 DB calls) 
{:valid false,
 :dbname
 "[Simba][SparkJDBCDriver](500618) Error occured while deserializing arrow data: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available",
 :message
 "[Simba][SparkJDBCDriver](500618) Error occured while deserializing arrow data: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available"}
```

After I downgraded to OpenJDK 11.0.15, I still get the warning below about `java.nio.DirectByteBuffer(long,int)`, but it works:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.simba.spark.jdbc42.internal.io.netty.util.internal.ReflectionUtil (file:/Users/ryan/metabase/plugins/sparksql-databricks.metabase-driver.jar) to constructor java.nio.DirectByteBuffer(long,int)
```

**Comment by flamber** [comment]
@snarfed Similar problem as Snowflake, which also only works with Java 11, since it's also using Arrow dependency. #22564

**Comment by snarfed** [comment]
@relferreira it's working! Exciting, thank you!

One bug report: I can't get it to connect to any database other than `default`. It seems to ignore both the _Database name_ field and the path in the `jdbc:spark://` URI in the JDBC connection string. eg when I enter a JDBC connection URI that starts with `jdbc:spark://adb-...1.azuredatabricks.net:443/benchmarks;...`, it ignores the `/benchmarks` path and still uses the `default` database. Any idea how I can tell it the database name?

**Comment by snarfed** [comment]
Sure!...but it doesn't currently have issues enabled, I think because GitHub defaults them off in forks. You can enable them in its settings.

**Comment by relferreira** [comment]
Wow, I didn't know that.
It is enabled now

**Comment by aravishdatabricks** [comment]
need native Databricks Integration within Metabase.

**Comment by borft** [comment]
I've been using this driver to connect to our databricks cluster, using a docker setup, where we build our own images based on the fine work of @relferreira in https://github.com/relferreira/metabase-sparksql-databricks-driver. I've noticed in more recent builds ( > 0.46, currently on 0.47.9) that it seems to be leaking connections, which eventually results in running out of threads and a crash of Metabase.

Does anybody have similar issues, and perhaps a solution (other than regular restarts)? Does this also affect the regular spark driver, or should we look in the modifications for Databricks specifically?

**Comment by gajanand-jm** [comment]
Databricks is among one of the leading lakehouse platforms. Hoped that Metabase supported this connection by default :/

**Comment by borft** [comment]
Good news, I managed to track down the leaky connections issue, and a PR fixing it was merged into the driver.

That said, would be great if Metabase itself could take over development, as basically it's a wrapper around Databrick's own JDBC driver.

**Comment by borft** [comment]
> I've been using this driver to connect to our databricks cluster, using a docker setup, where we build our own images based on the fine work of @relferreira in https://github.com/relferreira/metabase-sparksql-databricks-driver. I've noticed in more recent builds ( > 0.46, currently on 0.47.9) that it seems to be leaking connections, which eventually results in running out of threads and a crash of Metabase.


Good news, it's been (mostly) fixed, by updating the driver to use an updated version of databricks jdbc driver!

**Comment by paoliniluis** [comment]
Hi @borft, do you have a repository for the driver?

**Comment by borft** [comment]
> Hi @borft, do you have a repository for the driver?

Yes, it's here: https://github.com/relferreira/metabase-sparksql-databricks-driver building instructions are included. (credits to @relferreira )

but basically, building a Metabase docker image, including the driver, boils down to:
```bash
git clone git@github.com:relferreira/metabase-sparksql-databricks-driver.git
cd metabase-sparksql-databricks-driver
export VERSION=0.48.3
docker build --tag metabase:${VERSION} --build-arg METABASE_VERSION=v${VERSION} .
```

On this line: https://github.com/relferreira/metabase-sparksql-databricks-driver/blob/2fe89d06c2a3de0944193be4174206107c93ac6a/deps.edn#L6 it defines what version of databricks' jdbc driver it uses.

**Comment by alxsbn** [comment]
@borft No solution on our side except the same than you. But same opinion about this, it's a long-time awaiting feature. But i see that Databricks was moved on "soon" as a future **paid** feature which was really a shame https://www.metabase.com/roadmap

**Comment by itay-sgh** [comment]
Super interested!

**Comment by ValdarT** [comment]
> But i see that Databricks was moved on "soon" as a future paid feature which was really a shame

To Metabase product development team: you do realize that Databricks is actively working on [their own dashboard solution](https://www.databricks.com/blog/announcing-public-preview-lakeview-dashboards)? I find it safe to assume that having this driver as a paid feature is likely to push people to opt for the Databricks solution in favor of Metabase...

**Comment by alxsbn** [comment]
It's no more a paid feature? good news! 
![image](https://github.com/user-attachments/assets/40ac4e18-d9be-417f-b34d-f78c7ed680c8)

**Comment by luizarakaki** [comment]
This is merged and shipping on 51. https://github.com/metabase/metabase/pull/42263

**Comment by gajanand-jm** [comment]
Will we also be able to control data access at the user level with this using Databricks UC? Otherwise, setting up data governance with Metabase is painful right now.

**Comment by paoliniluis** [comment]
@gajanand-jm please contact us about your use case
