### ISSUE TITLE
Results for questions are always grayed out/loading overlay isn't removed.

### ISSUE THREAD

**Issue by kevinbosak** [metabase/metabase#11547]
**Describe the bug**
After upgrading from 0.32.9 to 0.33.7.1 whenever any results from a query are shown, they are grayed out/faded.  It appears that the layer that fades out the results while they load does not get removed.  This can sort of be resolved via the browser console by entering "$('.Loading').remove()".  This issue seems to happen on every question.  Dashboards are not affected.  This occurs on both Chrome and Firefox on MacOS.

**Logs**
The console had some errors with loading a few resources, including many for "Refused to load the font ... because it violates the following Content Security Policy directive "font-src 'self'"".
There is also an error with loading "/snippets.text.js" because the MIME type is "text/html" and is not executable.

**To Reproduce**
1. Upgrade from version 0.32.9 to 0.33.7.1
2. Run a query/question.
3. Wait for the results to load and observe that they are still faded/grayed out

**Expected behavior**
Once the results load, the overlay for fading out the results should be removed, showing the results properly.

**Screenshots**
https://imgur.com/a/kB1npE0

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:71.0) Gecko/20100101 Firefox/71.0",
    "vendor": ""
  },
  "system-info": {
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.5+10",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.5",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.5+10",
    "os.name": "Linux",
    "os.version": "4.4.111+",
    "user.language": "en",
    "user.timezone": "UTC"
  },
  "metabase-info": {
    "databases": [
      "bigquery",
      "postgres",
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "postgres",
    "run-mode": "prod",
    "version": {
      "date": "2019-12-13",
      "tag": "v0.33.7.1",
      "branch": "release-0.33.x",
      "hash": "d2dda64"
    },
    "settings": {
      "report-timezone": "US/Eastern"
    }
  }
}`

Another affected UserAgent:
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"

**Severity**
Very annoying, but not quite a blocker.  There is a bit of a workaround that requires extra steps (see description).

**Additional context**
We have both a production and staging installation of Metabase and this issue is present on both after upgrading.

**Comment by flamber** [comment]
Hi @kevinbosak 
Please upgrade to 0.33.7.3, not related to this, but fixes a couple of build problems with 0.33.7.1

First time I've heard of this. Can you try starting Firefox/Chrome without any addons/extensions?
The reason is that your first screenshot shows a very strange looking refresh-icon in top-right.
Yours:
![image](https://user-images.githubusercontent.com/1447303/71130045-9709fc80-21b6-11ea-892a-bfc8e801c50c.png)
Mine:
![image](https://user-images.githubusercontent.com/1447303/71130072-a8530900-21b6-11ea-9afc-c5b34eeeea45.png)

You can ignore the `/snippets.text.js` error - that's fixed in the upcoming 0.34.0, but doesn't cause any problems. As for the CSP errors, could it be that your Site URL in Admin > Settings > General doesn't match the URL you're using to access Metabase?

**Comment by kevinbosak** [comment]
Thank you for the response.  We will upgrade to the latest version soon and see if that solves the problem.  I'll close this ticket and file a new one if we still have an issue.
