### ISSUE TITLE
Base memory usage increasing after sync

### ISSUE THREAD

**Issue by noppaz** [metabase/metabase#12060]
**Describe the bug**
We're running Metabase on Heroku and one day last week, we experienced the heaviest loads we've seen yet from our internal users. Memory issues for Metabase and unresponsiveness lead to us temporarily upgrade the Heroku dyno type from two Standard 2X to one Performance L dyno with 14 GB of memory.

Dyno upgrade and decreasing amount of usage eased off the app's problems. We kept the dyno type during the night, however, while Metabase wasn't used at all for several hours, memory usage was still at the same levels as before (about 10 GB) until the dyno was restarted.

**Expected behavior**
When Metabase isn't used, or usage amount/load decreases the memory usage should decrease to more normal operational levels.

**Screenshots**
Heroku metrics dashboard for the app during the night. Memory is high while load and throughput is none.
<img width="1187" alt="Metabase 10 GB memory without usage" src="https://user-images.githubusercontent.com/32292420/75985872-58e6c400-5eed-11ea-95ae-afe69cb741d6.png">
Additional JVM stats for same period
<img width="1185" alt="Metabase 10 GB memory without usage JVM statistics" src="https://user-images.githubusercontent.com/32292420/75985894-5edca500-5eed-11ea-8760-ac5502a4fcf3.png">

Dashboard metrics for the whole day, including heavy loads, dyno type upgrade, memory usage being high during the night and then decrease only after restart
<img width="1189" alt="Metabase whole day memory usage" src="https://user-images.githubusercontent.com/32292420/75986731-eaa30100-5eee-11ea-8b7c-6baf5957d8a2.png">
Additional JVM stats the whole day period
<img width="1188" alt="Metabase whole day memory usage JVM statistics" src="https://user-images.githubusercontent.com/32292420/75987096-9c423200-5eef-11ea-87cb-acb930d4bea1.png">

**Information about your Metabase Installation:**
- Your databases: AWS Redshift
- Metabase version: 0.34.2
- Metabase hosting environment: Heroku
- Metabase internal database: Heroku PostgreSQL

**Severity**
We can operate Metabase as is, with occasional operational issues when memory usage goes too high. However it is annoying to have to restart manually to clear memory when someone e.g. exports a file and uses a lot of memory temporarily. It also forces us to operate Metabase with unnecessary dyno types to avoid memory issues.

**Additional context**
I've noticed similar behaviour previously but not this dramatically. Metabase usually hit the roof of dyno memory in our previous setup (two 2X dynos), and didn't seem to clear memory unless the dyno was restarted manually or the daily Heroku restart was triggered. 

This behaviour has continued after we've downgraded to one Performance M dyno. Most times I've seen memory usage go up a lot (from normal levels of about 1.2 GB to 2.5 GB), and not decrease until I restart the dyno.

**Comment by flamber** [comment]
Hi @noppaz 
I'm fairly sure that most of this will be solved in 0.35.0 with the new Streaming Query Processor #11832
Leaving this open for now.

**Comment by lindsay-stevens** [comment]
Are you setting a JVM memory heap guideline (e.g. `Xmx4g`)? If not, the JVM will just keep using as much heap as it wants. The new QP feature @flamber mentioned probably will give a welcome reduction in memory pressure but the JVM is not concerned by that. Also note that I describe this as a heap guideline, because the JVM will go over it if it wants to, and there are other memory types (PermGen, eden etc from memory) that means the real limit of usage could be another 25% or so over Xmx.

I have experimented with JVM settings and Metabase quite a bit. There is not really any combination of settings or garbage collector types that is both a) very stable and b) releases memory back to the system. The JVM just seems to hate giving back any memory it was able to get, and will only do so reliably by restarting the JVM process. Another route to putting a hard limit is using cgroups or docker.

**Comment by noppaz** [comment]
We did read about those suggestions in one of the [troubleshooting articles](https://www.metabase.com/docs/latest/troubleshooting-guide/running.html) but haven't tested it ourselves. However, I don't follow your suggestions entirely @lindsay-stevens, do you think setting the maximum heap size might help, or add instability?

**Comment by lindsay-stevens** [comment]
I think it is definitely advisable to run Metabase with Xmx value set as it gives a strong hint to the JVM about how much memory to use, but I guess my point is that it should not be surprising if available memory above that Xmx value is consumed by the JVM. The instability I saw was related to using alternative garbage collectors (i.e. besides the Java 11 default G1GC) or setting a hard limit (e.g. with a cgroup) that is close the the Xmx value. So if you have a host with 8GB available, use `Xmx4g` and see if the peak usage gets anywhere near 8GB, then if there's sufficient headroom try `Xmx6g` etc.

**Comment by noppaz** [comment]
Thank you, I'll test that out, along with looking for improvements in 0.35.0.

**Comment by flamber** [comment]
@noppaz Please give 0.35.4 a spin, when you are able to. There should be a lot of improvements.
If you have long-running queries, then have a look at #12423 before upgrading.

**Comment by noppaz** [comment]
Hey @flamber, thanks for keeping this in the loop. I wanted to update you on how it's been for us. We have been running 0.35.4 for two weeks now, using a Heroku P-M dyno (2.5 GB). I haven't been able to observe any clear differences. The memory usage is normally around 1.2-1.6 GB during a day. Some days the usage increases to about 2.2 GB and I suspect that increase is because of large file exports. A common thing is that the usage never decreases until the dyno is restarted, but this might be expected from the JVM as noted previously here.
I'll let you decide if the issue is worth keeping or not. If needed I'd be happy to provide more investigations. Regardless, we will keep a close eye on coming versions.

**Comment by rkist** [comment]
Same here, but with 21Gb of memory, running 0.35.4 :(
It just keeps getting memory and never releases it.

**Comment by mbelang** [comment]
I deployed Metabase on kubernetes and I ran into the same issue. I set JAVA_OPTS to `Xmx4g -Xms4g` and even then the memory goes as high as 6GB which is the limit that I allowed to it. At some point kubernetes restart the container as it busts the memory limit.

Could it be related to Metabase internal caching system which seems to happen in memory?

**Comment by dpsutton** [comment]
Can people with this issue post their jvm versions? I'm wondering if this is a java 8 problem relating to memory usage in containers.

**Comment by mbelang** [comment]
@dpsutton 

I'm using the official metabase docker image 

```
java --version
openjdk 11.0.7 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```

**Comment by noppaz** [comment]
And we're on the [Heroku JVM buildpack](https://github.com/heroku/heroku-buildpack-jvm-common)
```
~ $ java -version
openjdk version "1.8.0_265-heroku"
OpenJDK Runtime Environment (build 1.8.0_265-heroku-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

**Comment by andrericca** [comment]
I am using v0.39.3 of metabase and still facing the same issue. 
Metabase starts using memory and neve clean it, so after a few queries it uses all of free memory.

My jvm version inside container is:
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**Comment by AndrewLWilson** [comment]
I'm also having this issue running metabase in AWS elastic beanstalk v0.41.2.  Here is the RAM usage % from AWS Cloudwatch (the drops are me restarting the instance):
<img width="1172" alt="Screen Shot 2022-04-12 at 8 21 21 AM" src="https://user-images.githubusercontent.com/83972010/162997504-bef54baa-557d-4496-8774-0e994fb79ff1.png">

**Comment by flamber** [comment]
@AndrewLWilson You should upgrade immediately to a newer release: https://github.com/metabase/metabase/releases

**Comment by Tony-metabase** [comment]
This happens to different instances connected with different Databases (snowflake): 

<img width="1195" alt="image" src="https://github.com/metabase/metabase/assets/110378427/e64432b9-c4ee-4ad6-977b-e40de06285af">

This happens to different instances connected with different Databases (postgreSQL):

<img width="1448" alt="image" src="https://github.com/metabase/metabase/assets/110378427/4f027775-ad7d-4c7a-879a-d34dccc64b24">

This comes from the embedding demo (which is not used often)

<img width="1225" alt="image" src="https://github.com/metabase/metabase/assets/110378427/d6d742ac-538d-42ba-9d99-6892fe70ca4d">

It impacts different instances differently so the memory leakage seems to effect instances in a different manner but all follow the same pattern of memory gradually increasing without metabase freeing it.

So just adding more information here that this might be a wider issue with some metabase process that doesn't free memory

**Comment by paoliniluis** [comment]
@camsaul it seems here that the GC never kicks in, but rather the container gets killed because of OOM, or we're doing something very wrong in how we configure Metabase in our cloud

**Comment by AndrewLWilson** [comment]
I just wanted to follow up that I've adopted a strategy of redeploying our Metabase instance in Elastic Beanstalk once per week using the managed updates functionality.  Here is what our memory usage looks like over the last 6 weeks.  Maybe it's overkill, but it's been working seamlessly for us!

<img width="1073" alt="Screenshot 2023-06-09 at 1 55 35 PM" src="https://github.com/metabase/metabase/assets/83972010/b9f32a30-21be-4fd4-88da-4be05a0b98de">

**Comment by lrkarthi** [comment]
Looking for Update for this ticket, same issue our application facing

**Comment by mir1198yusuf** [comment]
For us, Metabase uses normal amount of ram during scheduled sync/scan of source dbs, but does not releases it back after it is completed.
So after 3-4 scan, all memory gets used and docker container gets crashed - `java.lang.OutOfMemoryError: Java heap space`

If we restart the docker container after every 1 day, then it would works, it seems

**Comment by sreeram-narayanan** [comment]
We are also facing the same issue in v0.48.3. We use the official metabase docker image.

**Comment by antonio-polastri** [comment]
Same here.How do u solve the problem?

**Comment by AndrewLWilson** [comment]
> Same here.How do u solve the problem?

@antonio-polastri If I were you I would try hosting on a machine with more memory and restart the container every week or every night if needed.

**Comment by paoliniluis** [comment]
For everyone that commented on this thread: can you please add the following environment variable?
JAVA_TOOL_OPTIONS=-Xmx1488m -Xms500m

Change the xmx value to 80% of the RAM you have on your server and the xms value to 20% of RAM you have on your server. Let me know if there's any change

**Comment by AndrewLWilson** [comment]
> For everyone that commented on this thread: can you please add the following environment variable? JAVA_TOOL_OPTIONS=-Xmx1488m -Xms500m
> 
> Change the xmx value to 80% of the RAM you have on your server and the xms value to 20% of RAM you have on your server. Let me know if there's any change

Would it ned to be JAVA_OPTS if we're running the official docker image because of `exec /bin/sh -c "exec java $JAVA_OPTS -jar /app/metabase.jar $@"` in [run_metabase.sh](https://github.com/metabase/metabase/blob/master/bin/docker/run_metabase.sh#L63)?

**Comment by paoliniluis** [comment]
@AndrewLWilson doesn't matter, it will work with both

**Comment by paoliniluis** [comment]
@mir1198yusuf can you add -XX:+UseStringDeduplication to the JAVA_OPTS environment variable and report back?

**Comment by paoliniluis** [comment]
I've been investigating this on our own internal instance and it seems that Java will take as much memory as you assign to the JVM but it will NOT return it. If you see the RAM consumption of the JVM, it's doing GC, but the RAM won't be returned to the host
![image](https://github.com/metabase/metabase/assets/1711649/c432f29b-8563-4f96-bce5-a275d63d48a8)

There are several interesting articles for this that will shed some light on how the JVM uses the memory and what to do to release it
https://www.baeldung.com/gc-release-memory
https://stackoverflow.com/a/68291068

**Comment by mir1198yusuf** [comment]
@paoliniluis - help me understand. if server instance has 8 gb ram & I assign 4 gb to metabase jvm, jvm might start with 1gb ram and as it needs, it will take more & more till max limit 4gb. From outside (at docker-level), it will be seen as if metabase is not releasing the memory to host OS as which jvm won't. internal gc of jvm will do cleanup but from outside we wont be able to see it. we can see that if we use the tool you mentioned to check jvm usage.
Assume that we are not interested in seeing from inside, from outside the ram usage should not go above 4gb, right ?
Since we have 4gb max limit, when there is too much load on metabase, it will crash but not take more ram from host OS even though 3-4 gb is still free.

I will check & report back how much memory docker container is taking after I added `-e "JAVA_OPTS=-Xmx4g"`
Last I checked after adding this, a line in log mentioned `Maximum memory available to JVM: 970.0 MB` I know jvm uses 1/4 of available ram, but here I am giving 4g to jvm and not to container, docker container as seen in `docker stats` has access to entire 8gb

**Comment by lindsay-stevens** [comment]
@paoliniluis I'm fine with closing this. Not releasing memory seems to be a JVM thing not specific to Metabase. Maybe it's worth talking more about `-Xmx` in the Metabase docs, because a lot of people have come to this ticket.

**Comment by paoliniluis** [comment]
I just changed the name of this issue to something specific that we know it's there and that we might be able to tackle: on big syncs the base memory usage of the JVM increases, and we should keep it stable
![image](https://github.com/metabase/metabase/assets/1711649/2df50a0e-50dd-4ab5-8e21-727cf2d77f54)

**Comment by qnkhuat** [comment]
Given Luiggi's findings, I don't think it's still a P1; we should still investigate and find a way to reduce its memory footprint.

There is an ongoing effort here: https://github.com/metabase/metabase/issues/46209

**Comment by darksciencebase** [comment]
The plan here is to amend the documentation (@paoliniluis said he'd do it) and then close this issue in favor of more specific ones (with OOMs)
