### ISSUE TITLE
Drill through to question from dashboard doesn't set filter UI properly

### ISSUE THREAD

**Issue by dacort** [metabase/metabase#12496]
**Describe the bug**
When clicking "View these items" from a dashboard, the date filter widget UI is not represented properly on the resulting question. While the results are accurate, the Filter value displayed in the UI is for a specific date as opposed to a range and the calendar widget does not properly display said range.

**Logs**
n/a

**To Reproduce**
1. Build a question with a time-based summarization, e.g. `Count by Created At: Week`
2. Click on a data point and "View these orders"
3. Note that the date filter says "Created at is <a specific date>"
4. Expect that the date filter says "Created at is between <date 1 and date 2>"

**Expected behavior**
Expect the Filter widget to represent the underlying query.

**Screenshots**
- Example dashboard
![image](https://user-images.githubusercontent.com/1512/81590370-8f1e4500-936f-11ea-826b-354d855514d4.png)

- Resulting filters
![image](https://user-images.githubusercontent.com/1512/81590413-9cd3ca80-936f-11ea-8213-86ae580f9841.png)

- Calendar dropdown
![image](https://user-images.githubusercontent.com/1512/81590450-ab21e680-936f-11ea-9a2e-ecc982f81dc8.png)

**Information about your Metabase Installation:**
```json
{
  "browser-info": {
    "language": "en-US",
    "platform": "Linux x86_64",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/3.8.2 Chrome/78.0.3904.130 Electron/7.1.7 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "ANSI_X3.4-1968",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "1.8.0_252-8u252-b09-1~18.04-b09",
    "java.vendor": "Private Build",
    "java.vendor.url": "http://java.oracle.com/",
    "java.version": "1.8.0_252",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "25.252-b09",
    "os.name": "Linux",
    "os.version": "5.3.0-1017-aws",
    "user.language": "en",
    "user.timezone": "US/Pacific"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "src_hash": "77aa5e404c41882abb222122b272efa409323d08",
      "tag": "v0.35.2",
      "date": "2020-05-11",
      "branch": "master",
      "hash": "763fb50"
    },
    "settings": {
      "report-timezone": null
    }
  }
}
```

**Severity**
Annoying, but the query is correct.

**Additional context**
n/a

**Comment by flamber** [comment]
Upping priority, since it makes it really difficult to edit a filter:
![image](https://user-images.githubusercontent.com/1447303/83437072-66094580-a43f-11ea-9d5d-8f31a50249f0.png)
Group by "Week of Year" and doing drill-through "View these Orders" is also difficult to understand:
![image](https://user-images.githubusercontent.com/1447303/83437311-da43e900-a43f-11ea-8ac0-81e85c7f4f7b.png)

Related to #10767

**Comment by daltojohnso** [comment]
what we probably need to do here is beef up the `DatePicker` component to support all the possible levels of granularity. for example, there's no possible way to map a point on a chart with unit `month-of-year` to anything in the date picker

**Comment by shaunlebron** [comment]
The display name on the Filter Pill is fixed by: https://github.com/metabase/metabase/pull/32066 

Fixing the calendar widget to support the extra filter types that the Pill can display will require more work:
* I can support week/month/year ranges by converting them to day ranges
* more UI elements will have to be designed for the slice filters like hour-of-day, day-of-month, etc

**Comment by shaunlebron** [comment]
Not to be worked on until MLv2 is ready. [slack context](https://metaboat.slack.com/archives/C04CYTEL9N2/p1689943777033019)

**Comment by darksciencebase** [comment]
just checked on stats, the date filter looks right to me 
![image](https://github.com/metabase/metabase/assets/125455699/eb651e7e-5c0a-4a3a-bc9c-8141022c021b)

but when clicking on the filter, `On` is selected by default. `Between` is just one click away, but wrong end date is pre-selected there
![image](https://github.com/metabase/metabase/assets/125455699/f8d67848-a65c-481e-85cc-0c6e23c2f128)

@deniskaber can you tell if it's an FE or BE issue?

**Comment by bshepherdson** [comment]
I can still reproduce this on master. Looks like an MLv2 issue in one of the functions called in `frontend/src/metabase/querying/hooks/use-date-filter/utils.ts`, probably `Lib.specificDateFilterClause`, not handling ranges properly.

**Comment by ranquild** [comment]
This issue now exists in `master` again. We need to fix drills to expand the expression beforehand, as it was in https://github.com/metabase/metabase/blob/6506fc1b3e5b8c2cbd5972622d6f8e85a9741644/src/metabase/lib/fe_util.cljc#L57
