### ISSUE TITLE
Heroku Boot timeout (R10 error)

### ISSUE THREAD

**Issue by ukd1** [metabase/metabase#1311]
Heroku boot times out on a fresh install. E.g.

```
2015-10-21T21:15:09.349430+00:00 heroku[api]: Resize web to Performance-M by me@rsmith.co
2015-10-21T21:15:11.049946+00:00 heroku[web.1]: Starting process with command `./bin/start`
2015-10-21T21:15:09.460644+00:00 heroku[web.1]: State changed from crashed to starting
2015-10-21T21:15:15.476511+00:00 app[web.1]: 2015-10-21 21:15:15,475 [INFO ] org.eclipse.jetty.util.log :: Logging initialized @3803ms
2015-10-21T21:15:21.192785+00:00 app[web.1]: 2015-10-21 21:15:21,192 [INFO ] metabase.core :: Starting Metabase in STANDALONE mode
2015-10-21T21:15:21.202022+00:00 app[web.1]: 2015-10-21 21:15:21,201 [INFO ] metabase.db :: Verifying Database Connection ...
2015-10-21T21:15:21.201705+00:00 app[web.1]: 2015-10-21 21:15:21,201 [INFO ] metabase.core :: Starting Metabase version v0.12.0 (32ac4fd master)...
2015-10-21T21:15:21.415041+00:00 app[web.1]: 2015-10-21 21:15:21,414 [INFO ] metabase.db :: Verify Database Connection ... CHECK
2015-10-21T21:16:11.238105+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2015-10-21T21:16:11.238105+00:00 heroku[web.1]: Stopping process with SIGKILL
2015-10-21T21:16:11.708877+00:00 heroku[web.1]: Process exited with status 137
2015-10-21T21:16:11.718191+00:00 heroku[web.1]: State changed from starting to crashed
```

I've tried dyno sizes up to production Performance-M.

**Comment by ukd1** [comment]
Also with performance-L

```

2015-10-21T21:19:07.995994+00:00 heroku[api]: Resize web to Performance-L by me@rsmith.co
2015-10-21T21:19:08.102553+00:00 heroku[web.1]: State changed from crashed to starting
2015-10-21T21:19:09.464172+00:00 heroku[web.1]: Starting process with command `./bin/start`
2015-10-21T21:19:12.513809+00:00 app[web.1]: 2015-10-21 21:19:12,513 [INFO ] org.eclipse.jetty.util.log :: Logging initialized @2521ms
2015-10-21T21:19:16.571228+00:00 app[web.1]: 2015-10-21 21:19:16,571 [INFO ] metabase.core :: Starting Metabase in STANDALONE mode
2015-10-21T21:19:16.580583+00:00 app[web.1]: 2015-10-21 21:19:16,580 [INFO ] metabase.db :: Verifying Database Connection ...
2015-10-21T21:19:16.580368+00:00 app[web.1]: 2015-10-21 21:19:16,580 [INFO ] metabase.core :: Starting Metabase version v0.12.0 (32ac4fd master)...
2015-10-21T21:19:16.763420+00:00 app[web.1]: 2015-10-21 21:19:16,763 [INFO ] metabase.db :: Verify Database Connection ... CHECK
2015-10-21T21:20:09.684420+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2015-10-21T21:20:09.684524+00:00 heroku[web.1]: Stopping process with SIGKILL
2015-10-21T21:20:10.151894+00:00 heroku[web.1]: State changed from starting to crashed
2015-10-21T21:20:10.132575+00:00 heroku[web.1]: Process exited with status 137
```

:-1:

**Comment by kdoh** [comment]
Sorry to hear you've been having problems @ukd1 :( Heroku's timeouts are a bit tricky, but we're working on some solutions. https://github.com/metabase/metabase/pull/1212

**Comment by tlrobinson** [comment]
See also https://github.com/metabase/metabase-deploy/issues/4

**Comment by agilliland** [comment]
this specific issue should be fixed by #1212

**Comment by ukd1** [comment]
this is not fixed @agilliland @tlrobinson 

```
2015-10-30T15:56:32.882305+00:00 heroku[api]: Resize web to Performance-M by russ@xxx
2015-10-30T15:56:32.997445+00:00 heroku[web.1]: State changed from crashed to starting
2015-10-30T15:56:34.023749+00:00 heroku[web.1]: Starting process with command `./bin/start`
2015-10-30T15:56:38.437837+00:00 app[web.1]: 2015-10-30 15:56:38,436 [INFO ] org.eclipse.jetty.util.log :: Logging initialized @3777ms
2015-10-30T15:56:44.067801+00:00 app[web.1]: 2015-10-30 15:56:44,067 [INFO ] metabase.core :: Starting Metabase in STANDALONE mode
2015-10-30T15:56:44.095089+00:00 app[web.1]: 2015-10-30 15:56:44,095 [INFO ] metabase.db :: Verifying Database Connection ...
2015-10-30T15:56:44.087985+00:00 app[web.1]: 2015-10-30 15:56:44,087 [INFO ] metabase.core :: Starting Metabase version v0.12.1 (6efe49a 2015-10-21)...
2015-10-30T15:56:44.304177+00:00 app[web.1]: 2015-10-30 15:56:44,304 [INFO ] metabase.db :: Verify Database Connection ... CHECK
2015-10-30T15:57:34.143530+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2015-10-30T15:57:34.143732+00:00 heroku[web.1]: Stopping process with SIGKILL
2015-10-30T15:57:34.660380+00:00 heroku[web.1]: State changed from starting to crashed
2015-10-30T15:57:34.617489+00:00 heroku[web.1]: Process exited with status 137
2015-10-30T15:57:35.658061+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/setup" host=metabase-prd.herokuapp.com request_id=5baf7aa0-04f4-439f-99e1-1c2765c18ad7 fwd="204.28.118.156" dyno= connect= service= status=503 bytes=
```

**Comment by tlrobinson** [comment]
@ukd1 We haven't deployed this to the the metabase-deploy repo yet. Can you try this link and let me know if you have any trouble? It was built from master (after merging this fix) a couple days ago https://heroku.com/deploy?template=https://github.com/metabase/metabase-deploy/tree/test1

**Comment by olimart** [comment]
@ukd1 Master was not working for me so I just tried your link but it raises

```
There was an issue setting up your app environment.
could not find the source blob
```

**Comment by tlrobinson** [comment]
Sorry, the link was wrong, I fixed it and tested it. Can you try again?

**Comment by olimart** [comment]
@tlrobinson Deployed successfully. Very promising project. Thanks

**Comment by olimart** [comment]
@tlrobinson I've added PG database (no error raised so I assume it connected successfully) unfortunately in the list of tables available there are none from my db. How to check that the 'import' is working or debug?

**Comment by ukd1** [comment]
@tlrobinson is this merged in to metabase-deploy yet?

**Comment by robacourt** [comment]
We're still getting this issue with 0.29.0-RC1. In the log below it took 70 seconds to boot (it was successful only because we've increased our boot timeout on Heroku to 120 seconds)

2018-04-25T14:30:19.927189+00:00 heroku[web.1]: Starting process with command `HEROKU=true ./bin/start`
2018-04-25T14:30:21.617755+00:00 app[web.1]: Setting JAVA_TOOL_OPTIONS defaults based on dyno size. Custom settings will override them.
2018-04-25T14:30:21.622569+00:00 app[web.1]: Using these JAVA_OPTS: -Xmx686m -Dfile.encoding=UTF-8  -XX:+IgnoreUnrecognizedVMOptions -Djava.awt.headless=true -Dfile.encoding=UTF-8 --add-opens=java.base/java.net=ALL-UNNAMED --add-modules=java.xml.bind
2018-04-25T14:30:21.672771+00:00 app[web.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx686m -Dfile.encoding=UTF-8 -javaagent:/app/.heroku/bin/heroku-metrics-agent.jar 
2018-04-25T14:31:09.964904+00:00 app[web.1]: 04-25 14:31:09 [1mINFO metabase.util[0m :: Loading Metabase...
2018-04-25T14:31:20.091757+00:00 app[web.1]: 04-25 14:31:20 [1mINFO util.encryption[0m :: DB details encryption is DISABLED for this Metabase instance. 🔓 
2018-04-25T14:31:20.091768+00:00 app[web.1]: See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
2018-04-25T14:31:31.775838+00:00 app[web.1]: 04-25 14:31:31 [1mINFO metabase.core[0m :: Starting Metabase in STANDALONE mode
2018-04-25T14:31:31.799907+00:00 app[web.1]: 04-25 14:31:31 [1mINFO metabase.core[0m :: Launching Embedded Jetty Webserver with config:
2018-04-25T14:31:31.799911+00:00 app[web.1]:  {:port 21548}
2018-04-25T14:31:31.799912+00:00 app[web.1]: 
2018-04-25T14:31:31.854237+00:00 app[web.1]: 04-25 14:31:31 [1mINFO metabase.core[0m :: Starting Metabase version v0.29.0-RC1 (95a6267 release-0.29.0) ...
2018-04-25T14:31:31.854514+00:00 app[web.1]: 04-25 14:31:31 [1mINFO metabase.core[0m :: System timezone is 'Etc/UTC' ...
2018-04-25T14:31:32.010852+00:00 heroku[web.1]: State changed from starting to up
