### ISSUE TITLE
Allow embedding of cards in other websites

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#1380]
Right now a card can only be used in a dashboard. It would be useful to be able to embed a card in blogs, etc.

**Comment by tlrobinson** [comment]
We will probably want some sort of query caching before doing this.

**Comment by jstenquist** [comment]
+1. We have other internal tools and this would be immensely helpful.

**Comment by dncpax** [comment]
This is absolutely critical... we should share results like graphics, and link to "fullblown" metabase for deeper understanding and exploration. This also links to parameterized queries. Both are critical for us.

**Comment by salsakran** [comment]
Hey @jstenquist  + @dncpax, mind giving us a bit more context at https://docs.google.com/a/metabase.com/forms/d/11eZ5mwDy8IZaLZYlOUMyjCLXzJXKsGLaI1_xzi8TFD8/viewform

**Comment by dncpax** [comment]
done. great work!

**Comment by jstenquist** [comment]
@salsakran just submitted. Let me know if I can give any more input. ~15 person funded startup, looking to save time with reporting internally.

**Comment by AdamLandis** [comment]
Ditto, love to give this functionality without having to build it out ourselves.

**Comment by IvanBioRender** [comment]
Just FYI, this issue is still linked at the bottom of [the FAQ](https://www.metabase.com/faq/).

**Comment by flamber** [comment]
@IvanBioRender Thanks for the pointer. That faq page is outdated (#11413) and we're working on getting rid of it. Please look in the https://www.metabase.com/docs/latest/ for the most up-to-date information. If you find anything outdated/wrong in the documentation, then click the link in the bottom of each page to see the Github markdown file, which you can propose changes to.
