### ISSUE TITLE
Filters with dropdown lists uses query on the database

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#13832]
**Describe the bug**
Since 0.37, filters with dropdown lists gets the information by querying the source database, when focusing the filter, and caching is not effective for those queries.
In previous versions, this information was retrieved from the application database as part of the dashboard data (`/api/dashboard/:id`)

**To Reproduce**
(this is using a converted Sample Dataset on MariaDB)
1. Make sure Admin > Data Model > (MariaDB) > Products > Category > "Field Type"="Category" and "Filtering on this field"="A list of all values"
2. Simple question > (MariaDB) > Products - save as "Q1"
3. Create dashboard, add Q1 and add filter type "Categories" and connect to Q1.Category - save dashboard
4. Click filter widget, which sends request `/api/dashboard/:id/params/:params/values`, which makes a query in the source database. Clicking the filter widget again will do the same. The query sent every time:
```SELECT `PRODUCTS`.`CATEGORY` AS `CATEGORY` FROM `PRODUCTS` GROUP BY `PRODUCTS`.`CATEGORY` ORDER BY `PRODUCTS`.`CATEGORY` ASC LIMIT 1000```

**Expected behavior**
While it might not be possible to have a behavior like previous versions, since part of the change was to allow linked filters, it should not make a query to the source database, since that makes the scan-process moot (which is still used in QB filters) and causes excessive amount of queries on busy dashboards.

The `LIMIT 1000` also makes it behave differently than in QB filter, which does some auto-widget-conversion of the filter, when there's more than 300 distinct values - that conversion has it's own quirks #7603
But now, the dashboard filter list will only list 1000 values. Creating a filter for Reviews.Reviewer would only show results until "timmy" and never show or indicate that there are 76 results were not included. This might need it's own issue coupled with #7603

**Information about your Metabase Installation:**
Metabase 0.37 thru 0.37.2

Related to #13537 and #12654

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by slickrock22** [comment]
Sorry I am little confused.  I have read all of the related and referenced issues (mine is 14070 above).  Is this a bug or a permissions issue?  I am access as an admin so I don't think it is a permissions issue but want to make sure.  I would like to attempt to troubleshoot.

**Comment by flamber** [comment]
@slickrock22 This is a regression bug.

**Comment by slickrock22** [comment]
@flamber Thanks.  I am not super technical so i am not sure what that means for me getting my dashboard working again.  I googled Regression Error, and I understand what that means now, thanks.  For the purposes of my dashboard, do I need to rebuild from scratch because the upgrade permanently broke the filters or is there a bug fix coming that will magically fixed what is now broken?  Thanks for any insights!

**Comment by slickrock22** [comment]
Ok so I just rebuilt the dashboard from scratch with the same questions and same filters and the drop downs work.  Not ideal but it doesn't look like it is a problem with the code.

**Comment by slickrock22** [comment]
@flamber  I just fixed this issue in all of my dashboards by identifying the offending value in the db.  In my case, every dashboard had {"name":"","slug":"","id":"3db2f415","type":"date/all-options"} as the first value in the parameters field.  

SELECT * FROM public.report_dashboard WHERE parameters like '%"name":"","slug"%'

You simply delete the value from the beginning of the string, save and my dashboards all worked.  Not sure if the value will be the same for everyone but hopefully this provides some direction.  It looked odd becuase it didnt reference a real filter.  Also I noticed in the UI, when I looked at the embedding page, I have a filter value for embedding that was blank.

**Comment by flamber** [comment]
@slickrock22 Then your problem is unrelated to this issue.

**Comment by janamfisdom** [comment]
@flamber is this resolved yet? because we also upgraded Metabase from old version to 0.37.4 and all of the dropdown filters are messed up and are behaving like plain text box. I also checked field properties in admin console but in that it shows 'list of values'.

I also tried building a new question and new dashboard but still doesn't work.

**Comment by flamber** [comment]
@janamfisdom No, the issue is still open.

**Comment by janamfisdom** [comment]
@flamber any work around which you found for this issue? because we tried with search but it is very very slow.

**Comment by dpsutton** [comment]
Just putting some notes here. The chain-filter apparatus has a pathway for when there are cached FieldValues. However, it has a logic flaw: it assumes that if there aren't `human_readable_values` then it ignores the field values. It ideally should fall back to `values` and return that. I made the following adjustment to `metabase.models.params.chain-filter/chain-filter` (`chain-filter-search`) would need a similar fix.

```clojure
(s/defn chain-filter
  [field-id    :- su/IntGreaterThanZero
   constraints :- (s/maybe ConstraintsMap)
   & options]
  (assert (even? (count options)))
  (let [{:as options} options
        {orig :values, remapped :human_readable_values :as _field-values} (db/select-one
                                                                              [FieldValues :values :human_readable_values] :field_id field-id)
        remapping (not-empty (zipmap orig remapped))
        need-db? (or (segmented-user?) (seq constraints))]
    (cond remapping
          (if need-db?
              (human-readable-values-remapped-chain-filter field-id remapping constraints options)
              (map vector orig remapped))

          (and orig (not need-db?))
          orig

          :else
          (if-let [remapped-field-id (remapped-field-id field-id)]
            (field-to-field-remapped-chain-filter field-id remapped-field-id constraints options)
            (unremapped-chain-filter field-id constraints options)))))
```

The idea is to use the cached FieldValues if we don't have segmented-user concerns or constraints. In order to speed up the rest, we would need some kind of cache. I'm not sure if our existing caching middleware can help (depends on if the constraints and permissions end up in the query or not since the cache key is just a hash of the query). Any in memory caching can't work in a multi-tenant scenario.

**Comment by mazameli** [comment]
P1 due to upvotes and that it's a regression and related to performance.

**Comment by nemanjaglumac** [comment]
@camsaul I see you were already assigned. Just a heads-up that there is now a repro available.

**Comment by camsaul** [comment]
Fixed by #15943

**Comment by nemanjaglumac** [comment]
> @camsaul I see you were already assigned. Just a heads-up that there is now a repro available.

Once again, this issue has a reproduction that wasn't unskipped in #15943 . I unskipped it in https://github.com/metabase/metabase/pull/16023 but exactly that repro is failing for both OSS and EE versions in Circle CI.

Tried to test this locally, in case repro was wrong, but I can still see multiple requests every time I click filter widget.
![image](https://user-images.githubusercontent.com/31325167/118056757-c9f3f800-b38a-11eb-93de-ef9f6f79cc07.png)

Either I didn't understand how to repro and am doing something wrong locally, or this issue hasn't been fixed.

**Comment by camsaul** [comment]
@nemanjaglumac 

The issue wasn't that we shouldn't hit the Dashboard parameter `values` endpoint. It was that hitting the endpoint should return cached `FieldValues` instead of running a query to determine them

The fact that the FE is making all those requests is still a bad thing, but that's a separate issue. I fixed what happens under the hood after you hit those endpoints

**Comment by nemanjaglumac** [comment]
> The fact that the FE is making all those requests is still something we should fix, but that's a separate issue (and not as big of a deal as this one). I fixed what happens under the hood after you hit those endpoints

@flamber should we then open a new issue and update the Cypress repro reference?
