### ISSUE TITLE
Dashboard filter on a Custom Column date-type causes error

### ISSUE THREAD

**Issue by andreychirikba** [metabase/metabase#17775]
**Describe the bug**
On a dashboard, when I connect a date dashboard filter to a custom (date) column, the chart card shows "There was a problem displaying this chart."

**Logs**
`Unknown field type: Array(2)
f @ app-main.bundle.js?4b22fb95a94bed9cef71:5
app-main.bundle.js?4b22fb95a94bed9cef71:5 Unknown field type: Array(2)
f @ app-main.bundle.js?4b22fb95a94bed9cef71:5
`

**To Reproduce**
On sample dataset:
1. Create a question from Orders, add a date column that equals "Created At".
![image](https://user-images.githubusercontent.com/30152071/132225280-2052f995-684c-4285-8b6b-e7115a20f0e8.png)
2. Save the question and add it to a new dashboard.
3. Create a dashboard filter and connect it to the custom field.
![image](https://user-images.githubusercontent.com/30152071/132225485-38a3aa33-cdee-4a9f-adf3-d50b53cb341e.png)
4. Set the filter to any date.
5. Notice the error.
![image](https://user-images.githubusercontent.com/30152071/132225542-7e4aa6be-31d4-4b73-8d66-896d35f1d383.png)

If you click on the question card to open it, the filter is applied correctly. Only on the dashboard does the filter fail.

**Expected behavior**
I expect the filter to work on the dashboard.

**Information about your Metabase Installation:**

`{
  "browser-info": {
    "language": "en-GB",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36",
    "vendor": "Google Inc."
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "11.0.11+9",
    "java.vendor": "AdoptOpenJDK",
    "java.vendor.url": "https://adoptopenjdk.net/",
    "java.version": "11.0.11",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "11.0.11+9",
    "os.name": "Linux",
    "os.version": "5.10.25-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "hosting-env": "unknown",
    "application-database": "h2",
    "application-database-details": {
      "database": {
        "name": "H2",
        "version": "1.4.197 (2018-03-18)"
      },
      "jdbc-driver": {
        "name": "H2 JDBC Driver",
        "version": "1.4.197 (2018-03-18)"
      }
    },
    "run-mode": "prod",
    "version": {
      "date": "2021-07-14",
      "tag": "v0.40.1",
      "branch": "release-x.40.x",
      "hash": "ed8f9c8"
    },
    "settings": {
      "report-timezone": null
    }
  }
}`

**Severity**
This prevents us from solving a specific problem for a customer.

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by flamber** [comment]
The interesting part is in the log. Custom Columns were not exposed to dashboard filter until 0.40.0

```
2021-09-06 16:00:53,970 ERROR middleware.catch-exceptions :: Error processing query: null
{:database_id 4,
 :started_at #t "2021-09-06T16:00:53.665247+02:00[Europe/Copenhagen]",
 :error_type :invalid-query,
 :json_query
 {:constraints {:max-results 10000, :max-results-bare-rows 2000},
  :type :query,
  :middleware {:js-int-to-string? true, :ignore-cached-results? false},
  :database 4,
  :query {:source-table 11, :expressions {:CustomColumn CreatedAt [:field 86 nil]}},
  :parameters
  [{:type "date/all-options",
    :value "2010-09-06~2021-09-06",
    :target ["dimension" ["expression" "CustomColumn CreatedAt"]]}],
  :async? true,
  :cache-ttl nil},
 :native nil,
 :status :failed,
 :class clojure.lang.ExceptionInfo,
 :stacktrace
 ["--> models.params$fn__34961$unwrap_field_clause__34966.invoke(params.clj:21)"
  "query_processor.middleware.parameters.mbql$fn__48848$build_filter_clause__48853$fn__48863.invoke(mbql.clj:58)"
  "query_processor.middleware.parameters.mbql$fn__48848$build_filter_clause__48853.invoke(mbql.clj:45)"
  "query_processor.middleware.parameters.mbql$expand.invokeStatic(mbql.clj:87)"
  "query_processor.middleware.parameters.mbql$expand.invoke(mbql.clj:73)"
  "query_processor.middleware.parameters$expand_mbql_params.invokeStatic(parameters.clj:37)"
  "query_processor.middleware.parameters$expand_mbql_params.invoke(parameters.clj:33)"
  "query_processor.middleware.parameters$expand_one.invokeStatic(parameters.clj:49)"
  "query_processor.middleware.parameters$expand_one.invoke(parameters.clj:41)"
  "query_processor.middleware.parameters$expand_all$replace_48949__48950.invoke(parameters.clj:59)"
  "mbql.util.match.impl$replace_in_collection$iter__18118__18122$fn__18123.invoke(impl.cljc:44)"
  "mbql.util.match.impl$replace_in_collection.invokeStatic(impl.cljc:43)"
  "mbql.util.match.impl$replace_in_collection.invoke(impl.cljc:38)"
  "query_processor.middleware.parameters$expand_all$replace_48949__48950.invoke(parameters.clj:59)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:59)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
  "query_processor.middleware.parameters$expand_all.invokeStatic(parameters.clj:56)"
  "query_processor.middleware.parameters$expand_all.invoke(parameters.clj:53)"
  "query_processor.middleware.parameters$expand_parameters.invokeStatic(parameters.clj:77)"
  "query_processor.middleware.parameters$expand_parameters.invoke(parameters.clj:73)"
  "query_processor.middleware.parameters$fn__48965$substitute_parameters_STAR___48970$fn__48971.invoke(parameters.clj:82)"
  "query_processor.middleware.parameters$fn__48965$substitute_parameters_STAR___48970.invoke(parameters.clj:79)"
  "query_processor.middleware.parameters$substitute_parameters$fn__48991.invoke(parameters.clj:111)"
  "query_processor.middleware.resolve_referenced$resolve_referenced_card_resources$fn__46790.invoke(resolve_referenced.clj:79)"
  "query_processor.middleware.expand_macros$expand_macros$fn__47539.invoke(expand_macros.clj:184)"
  "query_processor.middleware.add_timezone_info$add_timezone_info$fn__45335.invoke(add_timezone_info.clj:15)"
  "query_processor.middleware.splice_params_in_response$splice_params_in_response$fn__49982.invoke(splice_params_in_response.clj:32)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49192$fn__49196.invoke(resolve_database_and_driver.clj:31)"
  "driver$do_with_driver.invokeStatic(driver.clj:60)"
  "driver$do_with_driver.invoke(driver.clj:56)"
  "query_processor.middleware.resolve_database_and_driver$resolve_database_and_driver$fn__49192.invoke(resolve_database_and_driver.clj:25)"
  "query_processor.middleware.fetch_source_query$resolve_card_id_source_tables$fn__47779.invoke(fetch_source_query.clj:274)"
  "query_processor.middleware.store$initialize_store$fn__49991$fn__49992.invoke(store.clj:11)"
  "query_processor.store$do_with_store.invokeStatic(store.clj:44)"
  "query_processor.store$do_with_store.invoke(store.clj:38)"
  "query_processor.middleware.store$initialize_store$fn__49991.invoke(store.clj:10)"
  "query_processor.middleware.validate$validate_query$fn__50036.invoke(validate.clj:10)"
  "query_processor.middleware.normalize_query$normalize$fn__47915.invoke(normalize_query.clj:22)"
  "query_processor.middleware.add_rows_truncated$add_rows_truncated$fn__45181.invoke(add_rows_truncated.clj:35)"
  "query_processor.middleware.results_metadata$record_and_return_metadata_BANG_$fn__49967.invoke(results_metadata.clj:147)"
  "query_processor.middleware.constraints$add_default_userland_constraints$fn__47032.invoke(constraints.clj:42)"
  "query_processor.middleware.process_userland_query$process_userland_query$fn__49078.invoke(process_userland_query.clj:134)"
  "query_processor.middleware.catch_exceptions$catch_exceptions$fn__46972.invoke(catch_exceptions.clj:173)"
  "query_processor.reducible$async_qp$qp_STAR___38255$thunk__38256.invoke(reducible.clj:103)"
  "query_processor.reducible$async_qp$qp_STAR___38255$fn__38258.invoke(reducible.clj:108)"],
 :context :question,
 :error
 "Output of unwrap-field-clause does not match schema: \n\n\t   [(not (present? :field)) (not (present? \"id-or-name\")) (not (present? \"options\"))]  \n\n",
 :row_count 0,
 :running_time 0,
 :preprocessed nil,
 :ex-data
 {:type :schema.core/error,
  :value nil,
  :error [(not (present? :field)) (not (present? "id-or-name")) (not (present? "options"))]},
 :data {:rows [], :cols []}}

2021-09-06 16:00:53,987 DEBUG middleware.log :: POST /api/card/81/query 202 [ASYNC: completed] 344.5 ms (4 DB calls) App DB connections: 0/7 Jetty threads: 3/50 (2 idle, 0 queued) (70 total active threads) Queries in flight: 0 (0 queued)
```

**Comment by ranquild** [comment]
The underlying problem is that the BE doesn't support filtering by custom (date) columns. This should be fixed first before changing the FE.

**Comment by flamber** [comment]
@ranquild Quite sure it's only relative dates that are not supported by the backend - see https://github.com/metabase/metabase/issues/16273#issuecomment-918406362 - but perhaps querying is handled differently from the dashboard vs QB.
![image](https://user-images.githubusercontent.com/1447303/134916143-78e6e2d9-c411-4a45-8540-09f4f2d1a189.png)

**Comment by ranquild** [comment]
@flamber this request fails `/api/card/<id>/query`:

request:
```
dashboard_id: 8
parameters: [{type: "date/month-year", value: "2019-05", target: ["dimension", ["expression", "DateColumn"]]}]
```

response:
```
class: "class clojure.lang.ExceptionInfo"
context: "question"
data: {rows: [], cols: []}
database_id: 1
error: "Output of unwrap-field-clause does not match schema: \n\n\t \u001b[0;33m  [(not (present? :field)) (not (present? \"id-or-name\")) (not (present? \"options\"))] \u001b[0m \n\n"
```

**Comment by flamber** [comment]
@ranquild I'm unsure what type of query "Year Month" makes behind the scenes, since it's slightly different from using Between (called Date Range on the dashboard), which is a specific range.
But probably worth getting the backend fixed for all types and then we can see if there's anything to fix in the frontend.

**Comment by daltojohnso** [comment]
What FE work needs doing here? I can still reproduce the `"Output of unwrap-field-clause does not match schema...` error from the dashboard query endpoint.

**Comment by camsaul** [comment]
> The interesting part is in the log. Custom Columns were not exposed to dashboard filter until 0.40.0

The error is definitely that it doesn't work if you use an `:expression` reference as the target of a Field filter -- that's where that Schema error is coming from (it's expecting the function to return a `:field` clause but it's returning an `:expression` instead). We might be able to fix this by loosening up that schema but I'm not sure how much other stuff needs to be tweaked as well

**Comment by WiNloSt** [comment]
This issue was tagged as `FE` on the tactical board. I've corrected it to be `BE` to match with `.Backend` label and unassigned myself.

**Comment by qnkhuat** [comment]
Dropping this into QP inbox because it requires changing the QP
