### ISSUE TITLE
Week numbers are off by 1

### ISSUE THREAD

**Issue by whatthewhat** [metabase/metabase#2517]
When creating queries grouped by week the week numbers seems to be off by 1 (e.g. current week is shown as 19, but should be 18).

When comparing with the json data returned it looks like this might be a timezone issue, but changing "REPORT TIMEZONE" is settings has no effect:

![](https://s3.amazonaws.com/f.cl.ly/items/3S0P1U1Q2K0F3c1C2z43/Image%202016-05-03%20at%2012.20.21%20PM.png?v=b7723428)

![](https://s3.amazonaws.com/f.cl.ly/items/0B3c2K2d0k3d1u1I2t3U/Image%202016-05-03%20at%2012.21.11%20PM.png?v=9efb85d9)

Tested on browsers with UTC+3 and UTC-5.

Bug report info:
-  I am using the Chrome(50) browser.
-  My computer's OS is OS X 10.11.4.
-  I'm running Metabase on AWS.
-  My database is Postgres.
-  My Metabase version is v0.16.1.

**Comment by agilliland** [comment]
I believe this is a dupe of https://github.com/metabase/metabase/issues/2340 which is fixed and included in the new release coming out today.

**Comment by whatthewhat** [comment]
Hey @agilliland, thanks for the response!
Just upgraded to 0.17 and tables look good now 👍 

There's still a small issue with charts, the tooltip shows the right week number (18), but the X-axis labels are off by 1:

|![](https://s3.amazonaws.com/f.cl.ly/items/3w3y2j1g271R3C1g0j04/Image%202016-05-04%20at%2012.52.36%20PM.png?v=4e85eb38)   | ![](https://s3.amazonaws.com/f.cl.ly/items/3D2F272I0x2A0C212X28/Image%202016-05-04%20at%2012.52.51%20PM.png?v=3e5b714a)   |
|---|---|

**Comment by agilliland** [comment]
Okay, if you look at the latest comments at the end of https://github.com/metabase/metabase/issues/2340 I think you'll get some more information about what's likely happening here and how to address it.

In specific, it looks like your Metabase system is not running in your Report Timezone, which is likely what's causing this issue.  There's some docs about this here ... http://www.metabase.com/docs/v0.17.0/operations-guide/start.html#handling-timezones-in-metabase

I believe the fix for you will be to launch the app with the appropriate timezone set.  You can do this on Docker & AWS deployments by setting the `JAVA_TIMEZONE` environment variable, or if you are running the jar directly you can just add `-Duser.timezone=<report-timezone>`

give that a try and see if that resolves this for you.  what you'll be looking for is to have the output data from your queries all ending on the 0th hour.

**Comment by whatthewhat** [comment]
@agilliland Hey, sorry it took a while to get back to you on this one.
I tried setting `JAVA_TIMEZONE` and the result is still not what I'd expect to see (it is consistent between tables/chart views, though).

So, to reiterate: we have a postgres database with timezone set to UTC, report timezone in Metabase is UTC, I've set JAVA_TIMEZONE to UTC and, just to be sure, I've set my (OS X) timezone to UTC as well.

With this setup I'm seeing the following results:

![](https://s3.amazonaws.com/f.cl.ly/items/0W3m3o3c220H0j1i2e3g/Image%202016-05-24%20at%205.50.05%20PM.png?v=18e563f9)

The json payload looks like this:

![](https://s3.amazonaws.com/f.cl.ly/items/2f1f3V0p2e2s251Q2U02/Image%202016-05-24%20at%205.50.17%20PM.png?v=da5b39b3)

Is it possible that Metabase uses some different standard for week numbers and the current week is supposed to be **22** (this is posted on May, 24th)?..

**Comment by agilliland** [comment]
Yeah, I see what you are saying.  Those values are actually handled by our frontend codebase which parses the dates which represent the start of the week and then converts them into a more readable format with the week of year number.  It's entirely possible that something is not quite right in that conversion.

**Comment by tlrobinson** [comment]
I believe the inconsistency between tooltips and tick labels was resolved in 0.20.0, but whether we're showing the "correct" week number is still an open question.

@whatthewhat We group by weeks starting on Sunday (the US standard) rather than the [ISO week date](https://en.wikipedia.org/wiki/ISO_week_date) standard, which I assume is what you expected?

For postgres this is the SQL we generate:

`(date_trunc('week', (column_name + INTERVAL '1 day')) - INTERVAL '1 day')`

using this code on the backend:

```
    ;; Postgres weeks start on Monday, so shift this date into the proper bucket and then decrement the resulting day
    :week            (hx/- (date-trunc :week (hx/+ expr one-day))
                           one-day)
    :week-of-year    (extract-integer :week (hx/+ expr one-day))
```

https://github.com/metabase/metabase/blob/ec356f7fe3b6e4b67aea36f742f1fe77af005e7b/src/metabase/driver/postgres.clj#L138

and this code to format it on the frontend:

```
        case "week": // 1st - 2015
            // force 'en' locale for now since our weeks currently always start on Sundays
            m = m.locale("en");
            return formatMajorMinor(m.format("wo"), m.format("gggg"), options);
```

https://github.com/metabase/metabase/blob/ec356f7fe3b6e4b67aea36f742f1fe77af005e7b/frontend/src/metabase/lib/formatting.js#L61-L64

I believe `wo` and `gggg` follow the US standard, which says the first day of the week is Sunday and the first week of the year includes January 1st (whereas `Wo` and `GGGG` follow the ISO standard, which says the first day of the week is Monday, and the first week of the year includes January 4th)

For example this results in `2016-01-07` being put into the `2016-01-03T00:00:00.000Z` bucket, which is formatted as `2nd - 2016` because `2016-01-03` is a Sunday, thus the start of the "2nd" week of 2016, according to the US standard, 

So I believe we at doing something reasonable/correct on both the backend and frontend for `week` groupings.

However, I do think there a bug in the `week-of-year` extract. Postgres' `week` extract follows the ISO week standard, and `ISO weeks start on Mondays and the first week of a year contains January 4 of that year. In other words, the first Thursday of a year is in week 1 of that year.` whereas the US standard week (which I think is what our `moment` formatting code is doing) says that the first week of the year starts on January 1. This isn't an issue for `week` because we're basically using `date_trunc('week', ...)` to round to the week starting on Sunday, but in the case of `week-of-year` we get the actual week number.

I think we need to do two things:

1) Compute `week-of-year` correctly (consistent with `week` formatting on the frontend)
2) Maybe give the user control over the 1st day of week and 1st week of year (or maybe just simplified options like ISO week standard and US week standard?)

Here's a summary of my understanding:

                    | 1st day of week | 1st week of year           |
| ----------------- |-----------------| ---------------------------|
| US standard       | Sunday          | January 1st                |
| ISO standard      | Monday          | Contains Jan 4 / 1st Thurs |
| MB `week`         | Sunday          | January 1st                |
| MB `week-of-year` | Sunday          | Contains Jan 4?            |

**Comment by whatthewhat** [comment]
Just wanted to mention that after upgrading to 0.20.1 week numbers in tooltips and tick labels are consistent 👍
Also an option in the admin would be great!

**Comment by atharvai** [comment]
@tlrobinson can you take a look at https://github.com/metabase/metabase/issues/1779#issuecomment-301482150

That's an attempt at making locales configurable in Metabase. I haven't posted a PR yet but need to clean up and test properly.

**Comment by senior** [comment]
@whatthewhat Not sure if you're still experiencing the problem related to timezones throwing of the week calculations and the offset of the results, but this was fixed in https://github.com/metabase/metabase/pull/5729 and released with 0.26 RC1. More information can be found on the [0.26.RC1 release page](https://github.com/metabase/metabase/releases/tag/v0.26.0.RC1). Would be great to get some validation on the fix if you're still experiencing the problem.

**Comment by atharvai** [comment]
The full issue includes the implementation issue posted by tlrobinson. To calculate week number there is some plus 1 minus 1 hack going on. This forces Sunday as first day but most/all SQL implementations use iso week which is Monday starting . 0.26-rc1 addresses part of the problem. Week number is still going to be incorrect

**Comment by mazameli** [comment]
Thanks for the clarification, @atharvai. We no longer represent weeks by their number in the UI, however.

**Comment by atharvai** [comment]
Is there an option to? Feels restrictive if not

**Comment by mazameli** [comment]
No, there isn't. We did a lot of research, thinking, and discussion about this (see https://github.com/metabase/metabase/issues/3449), and came up with a change that we thought would be more generally useful to the majority of users. I'd be curious to hear a use case that might explain why "37th week of 2016" is better or clearer — I don't think most people have any idea which months/days the 37th week of the year represents off the top of their head, for example. This follows our general ethos of going with the clearest, simplest solution in every case whenever we can, and to keep from polluting the UI with too many settings and knobs to account for all edge cases.

**Comment by atharvai** [comment]
So a lot of year over year charts are broken down by week. Yes some years have 53 v 52 weeks but dates are rarely the same for same week across years. So seeing a series for each year and week on X axis would be difficult if weeks were represented by actual date ranges. 

I feel that date time structure is one of the easier data types to give flexibility around and needs the most. Other data types could be more restrictive but date time is used in many different ways across the world. First day of week is Monday in most of the world but Sunday in only some countries so even day number of week should be flexible.
