### ISSUE TITLE
Nested JSON fields generate large file names that are not allowed by the file system in serialization

### ISSUE THREAD

**Issue by paoliniluis** [metabase/metabase#29246]
**Describe the bug**
When you have a very deeply nested json in a json field in a database, Metabase will generate a very large filename when using serialization dump that the filesystem won't allow, breaking the process

**Logs**
java.io.FileNotFoundException:  (Filename too long)

**To Reproduce**
1) create a table with a json field, the json should be deeply nested
e.g.
```
create table "json_table"
(
    json_field json
);
```
then
```
INSERT INTO public.json_table (json_field) VALUES (e'{
                 "level1": {
                   "level2": {
                     "level3": {
                       "level4": {
                         "level5": {
                           "level6": {
                             "level7": {
                               "level8": {
                                 "level9": {
                                   "level10": {
                                     "level11": {
                                       "level12": {
                                         "level13": {
                                           "level14": {
                                             "level15": {
                                               "level16": {
                                                 "level17": {
                                                   "level18": {
                                                     "level19": {
                                                       "level20": "Nested value"
                                                     }
                                                   }
                                                 }
                                               }
                                             }
                                           }
                                         }
                                       }
                                     }
                                   }
                                 }
                               }
                             }
                           }
                         }
                       }
                     }
                   }
                 }
               }')
```
2) tell metabase to parse this field and then try an export
3) hit the error

**Expected behavior**
Generate shorter file names

**Screenshots/videos**
NA

**Information about your Metabase Installation:**
- Metabase version: 1.45.3

**Severity**
P2

**Additional context**
NA

**Comment by paoliniluis** [comment]
bumping the priority as once you have this on your Metabase DB, you can't use serialization anymore

**Comment by paoliniluis** [comment]
No workaround unless we physically delete the field table from the DB

**Comment by john-metabase** [comment]
@paoliniluis we are thinking this fix should be fixed on the 45 release branch first, since I found [a regression](https://github.com/metabase/metabase/issues/29322) in v1 `dump` on `master` related to the new toucan2 changes which will need to be fixed, but won't be backported.

**Comment by paoliniluis** [comment]
I don't think we're going to release another 45 version, so if this can get into 45 and 46 just for everyone in 45 to have it (I need to tell customers using 45 to get the full branch and not a tag), then that would be great!

**Comment by paoliniluis** [comment]
A sibling issue of this one https://github.com/metabase/metabase/issues/29309

**Comment by john-metabase** [comment]
@paoliniluis this PR got hung up on failing CI tests. Since the affected customer found a workaround, do you still want this merged? I may just need to re-open this PR under a different branch to clear up whatever is wrong with this one.

**Comment by luizarakaki** [comment]
This was a Serdes v1 bug. We need to verify if still happens on v2 (export/import)

**Comment by qnkhuat** [comment]
No longer an issue with Serdesv2, AFAIK there is no constraint for the filename length in serdesv2
