### ISSUE TITLE
Drill-Through Part 2 -- Polish

### ISSUE THREAD

**Issue by salsakran** [metabase/metabase#4667]
Splitting off polish + minor bugs off #4496 so we can merge + experiment with this. 

This will be the main tracking issue, and should include anything that is intended to happen by version 0.24

Sherpa: @salsakran 

### Feature To-dos
- [ ] Enable for visualizations on dashboards 
- [x] Replace Summarize for Raw Tables with 
   - common metrics (flattened, and limited to 5?)
   - count of TableName(plural) by time
   - sum of columns -> column picker???
- [ ] Visual design for drill-through options
- [x] Clicking on column header should let you get
    - min/max/avg of this column (if numeric)
    - sum of this column (if numeric)
    - sum of this column by time (if numeric)
    - distinct values of this column (if numeric)
    - count of rows pivoted by this column

 
### Bugs
- [ ] Click-through popover not working for maps on mobile

### Polish
- [ ] When clicking on a funnel, the target should be the line and not the bar

### Open-ended To-dos
- [ ] Decide on ordering of options 

### Open Questions
- How does this work in the context of permissions?
- How does this work wrt public links?

**Comment by salsakran** [comment]
Stream of consciousness -- I think the cell click through should offer a couple of things in raw-table mode
I think we should replace "=" quick filter with 2 things. 
A) See rows where `blah`=`current value` 
B) Number of rows where `blah`=`current value`

(also added some column header click todos above)

**Comment by mazameli** [comment]
Here's an update on the state of the visual designs for the action menu. We did a number of quick riffs yesterday trying to see if we could make the groupings labels stand out more and to make the actions iconographic instead of textual. These examples are meant to be illustrative rather than exhaustive. **Note:** _I'm also messing around here with a popover restyle that positions the popover on top of the originating element a la material design, so don't be thrown by that._

**Time series**

![rows](https://cloud.githubusercontent.com/assets/2223916/25026787/2367c7b0-205d-11e7-9b91-976455d7af8b.png)

**Hover**

![rows hover](https://cloud.githubusercontent.com/assets/2223916/25026796/2df0c18c-205d-11e7-91ec-bfbfe051bc7a.png)

**Raw data table cell**

![cell](https://cloud.githubusercontent.com/assets/2223916/25026803/362116c2-205d-11e7-85dc-98d9c3d2e5d4.png)

**Primary key cell (the drill in action would be to go to that single record view)**

![pk](https://cloud.githubusercontent.com/assets/2223916/25026820/4ad6571c-205d-11e7-91f1-2e12ed890e1c.png)

**Column heading v1**
The `Summarize` buttons in this example would be for:
- count of rows pivoted by this column
- sum of this column
- average of this column

![column heading v1](https://cloud.githubusercontent.com/assets/2223916/25026840/65fb6f0a-205d-11e7-9bab-d1af9b42207b.png)

**Column heading v2**
The `Summarize` actions are the same here, just a different visual treatment.

![column heading v2](https://cloud.githubusercontent.com/assets/2223916/25026864/8e0eced8-205d-11e7-9c0e-ec8e8de7ebbd.png)

**Comment by tlrobinson** [comment]
Regarding

> View these X” should be renamed “View rows where ColumnName=Value?” or something else?

There could be up to 2 or 3 columns that are being filtered (e.x. a multiseries scatter plot) and I don't think we want to list all of them.

**Comment by tlrobinson** [comment]
> sum of this column by time (if numeric)

What should the default granularity be?

**Comment by tlrobinson** [comment]
> count of rows pivoted by this column

Does this only appear for `category` type columns?

**Comment by salsakran** [comment]
`I assume this only appears if there's a time column (what if there's more than one? how about via fks?)` 

Yes, let's just grab the first available time metric. (looking forward we'll eventually let people order dimensions for a given metric/table)

**Comment by salsakran** [comment]
`Does this only appear for category type columns?` 
Any column that allows you to group by it.

**Comment by salsakran** [comment]
`There could be up to 2 or 3 columns that are being filtered (e.x. a multiseries scatter plot) and I don't think we want to list all of them.` 

This is actually no longer an issue, as this was appearing in segment view a while ago. deleting.

**Comment by tlrobinson** [comment]
Alright, I've implemented the column actions. Have fun @mazameli...

![screen shot 2017-04-18 at 4 53 10 pm](https://cloud.githubusercontent.com/assets/18193/25157674/a96e4e8a-2457-11e7-9adf-4bebdee74ce9.png)

**Comment by mazameli** [comment]
I'm a little sad that now you can't just click on a heading to sort by it. Not sure that I love the one obvious alternative I can think of, though, which is slapping an action button next to the heading, and keeping the heading text the click target for sorting (button would either be persistent [gross] or appear on hover [less gross, but not mobile friendly]). It just feels a little goofy that we're breaking a pretty common table interaction pattern, and that sorting would now take two clicks.

If we do keep sort in the action menu, then I think the copy for the sort action should read `Sort ascending`, presuming you're not yet sorting by that field. If you are, it would say `Sort descending`.

**Comment by salsakran** [comment]
Yeah, I think there's something to the idea of primary actions being right in front of you.  I feel similarly with respect to things like clicking on a user id twice.

**Comment by mazameli** [comment]
I'm still seeing a bug where zooming/drilling in on "this month" or "this year" on a time series results in an error: `ERROR: function date_trunc(unknown, unknown) is not unique Hint: Could not choose a best candidate function. You might need to add explicit type casts. Position: 511`

**Comment by salsakran** [comment]
@mazameli this on PG or the sample dataset?

**Comment by mazameli** [comment]
Postgres

**Comment by mazameli** [comment]
Redshift, too
