### ISSUE TITLE
Can't select "No field type" without going to Admin Panel

### ISSUE THREAD

**Issue by joshuashort** [metabase/metabase#5276]
- Your browser and the version: Safari 10.1.1
- Your operating system: macOS 10.12.5
- Your databases: MariaDB
- Metabase version: 0.24.1
- Metabase hosting environment: Docker
- Metabase internal database: H2

- *Repeatable steps to reproduce the issue*
-- Admin user at http://localhost:3000/reference/databases
-- Select a database
-- Click "Tables in this database"
-- Select a table
-- Click "Fields in this table"
-- If "Field type" is already blank
--- Selecting another type works
--- Selecting "No field type" works
-- If "Field type" isn't blank
--- Selecting "No field type" leaves the previous field type instead of the expected behavior

**Comment by mazameli** [comment]
I was unable to reproduce this bug on either Safari or Chrome. It's possible it has been fixed since version 0.24.1.

**Comment by joshuashort** [comment]
Ok.. but this occurred on the official Docker image of Metabase. Was it not reproducible in that environment?

**Comment by joshuashort** [comment]
I can't see what I'm doing wrong -- I was using metabase/metabase:latest, and I tried removing the image, thinking it might be out of sync.. looking on hub.docker.com, :latest is still set to v0.24.1. I manually set to the latest docker hub tag (i.e. v0.24.2), and the issue is still there. Maybe I'm reporting this in the wrong place, and maybe it's actually a different problem?

**Comment by joshuashort** [comment]
Same problem with metabase/metabase-head:

Thanks for using Metabase!
You're on version v0.25.0-snapshot
Built on 2017-05-11
Branch: master
Hash: 2222f41

(can't select "No field type" on a field that already has a type in the Data Reference 'tab')

I'm just running `docker run -d -p 3000:3000 --name metabase -v "$(pwd)"/data:/metabase-data -e MB_DB_FILE=/metabase-data/metabase.db metabase/metabase-head`

**Comment by mazameli** [comment]
Cool, I'll reopen this, but I'll need some help from the other @metabase/core-developers to see if this is a Docker-specific issue, because I'm still unable to reproduce this.

**Comment by joshuashort** [comment]
Thanks! I just noticed this issue (https://github.com/metabase/metabase/issues/5280) about the version on DockerHub. Time for me to dig a little more.

**Comment by Varunram** [comment]
@joshuashort @mazameli Turns out I am able to reproduce the error on OSX 10.12.5. I used the default Metabase h2 db and am running the Metabase Docker image on Docker Edge. Funny thing is even after changing the field type 2-3 times, it defaults to the previous value if we select "No Field Type" in the end.

**Comment by joshuashort** [comment]
I'm also getting this on Docker on Ubuntu 16.04.2 with Metabase v0.24.1 (haven't tried v0.24.2 or :head) on this server yet.

**Comment by salsakran** [comment]
@Varunram + @joshuashort can you check the JS and server logs for errors? Is the field being set or is there an error on that call? should be something like `PUT /api/metadata/field/1111` or something similar.

**Comment by joshuashort** [comment]
@salsakran I don't see any browser console messages while trying to select "No field type"; and there's never a `PUT` call on the server log; the selection doesn't happen on the client side. I'll check in Chrome..

**Comment by Varunram** [comment]
@salsakran Nope, logs look clean on my side. What do you suspect the issue is though?

**Comment by ranquild** [comment]
Checked docker images for both `v0.42` and `v.043-rc1` and couldn't reproduce the issue.

**Comment by flamber** [comment]
This is not fixed:

https://user-images.githubusercontent.com/1447303/166228248-4e7da232-2b6e-4e71-ac67-0321c35404be.mp4

**Comment by ranquild** [comment]
In case someone is affected by this - you can still remove the field type via Admin -> Data Model. This bug affects Data Reference pages only.
