### ISSUE TITLE
Parameters in shared questions don't work with json output from the BE json endpoint

### ISSUE THREAD

**Issue by Leen15** [metabase/metabase#5674]
Hi, I didn't find a useful documentation about using parameters in shared question, but I think there is something wrong.

This is the example:
1. Create a shared question with the follow SQL (I'm using the sample dataset):
```
select * from PEOPLE
where created_at <= {{to_day}}
order by created_at DESC
```
and set the `to_day` variable as `required` with default value `June 1, 2017`.

2. Now, try to open the public link:
`https://*****.***/public/question/f13fe0f3-3721-48b7-9ff9-cab8264a9127?to_day=2017-03-01`

And it's ok:
![immagine 1505](https://user-images.githubusercontent.com/3629071/28914407-cdc46a48-783b-11e7-870d-8a0eda64fe20.png)

3. Finally, Try to open the same link with json:
`https://*****.***/public/question/f13fe0f3-3721-48b7-9ff9-cab8264a9127.json?to_day=2017-03-01`

The result set doesn't respect the parameter:
![immagine 1506](https://user-images.githubusercontent.com/3629071/28914462-0a1ed1a4-783c-11e7-9af9-81ff4fecaff6.png)

Is there something wrong on how I'm using metabase?
I'm using v0.24.2 due to #5607 issue.

Thanks

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by salsakran** [comment]
I think we fixed something similar to this a bit back. I don't think this was in 0.25 however.

@attekei or @camsaul did we do anything that might have broken this? The query-lib refactor shouldn't have touched any backend json endpoints.

**Comment by attekei** [comment]
I think that this isn't a regression, seems like an oversight in logic that 
1) constructs the download URL in the UI in https://github.com/metabase/metabase/blob/master/frontend/src/metabase/lib/urls.js#L72
2) does a redirection to the proper API endpoint in https://github.com/metabase/metabase/blob/master/src/metabase/routes.clj#L55

The public question downloading logic itself supports parameters so this shouldn't be hard to fix.

**Comment by jpulec** [comment]
Any chance this will get looked at anytime soon? Not being able to filter public CSVs/JSON/XSLX is quite painful.

**Comment by dobobaie** [comment]
Replace 
`https://*****.***/public/question/f13fe0f3-3721-48b7-9ff9-cab8264a9127?to_day=2017-03-01`
to
`https://*****.***/public/question/f13fe0f3-3721-48b7-9ff9-cab8264a9127?parameters=[{"type":"category","target":["variable",["template-tag","to_day"]],"value":"2017-03-01"}]`

**Comment by giannoug** [comment]
As of v0.38.0.1, this is still an issue.

This works: 
```
https://metabase.example.com/public/question/e551bad7-c0d3-442b-95ff-ef4f58de32db?variable_one=123&variable_two=asd
```

But when requesting a JSON response, for example consider the following request:
```
https://metabase.example.com/public/question/e551bad7-c0d3-442b-95ff-ef4f58de32db.json?variable_one=123&variable_two=asd
```
The above request returns:
```
{"status":"failed","error":"You'll need to pick a value for 'variable_one' before this query can run.","error_type":"missing-required-parameter"}
```

**Comment by cdeweyx** [comment]
[Example question for internal use](https://stats.metabase.com/question/24178-test-shared-question-5674?to_day=2021-02-18)

**Comment by LukePammant** [comment]
That `parameters` query parameter is pretty clunky. Is there documentation on this anywhere?

Side note - is that slack channel private for MetaBase contributors? or can I get an invite?

**Comment by markatlish** [comment]
Confirming this is still an issue.  I'd suggest renaming it: 

👉 *"Public question share links ignore query parameters for variables when exporting (JSON/CSV/XLSX)"*

This would be VERY useful to fix, since it would allow integrating Metabase in lots of ways w/ the power of dynamic variables.   (eg: [`=IMPORTDATA("*.csv")`](https://support.google.com/docs/answer/3093335?hl=en) in Google Sheets is my use case)

 The frontend already supports variables/parameters with `?key=value`-style query parameters for public questions, but the backend does not.

* Specifically the backend [`/card/:uuid/query/:export-format`](https://www.metabase.com/docs/latest/api#tag/apicard/post/api/card/{card-id}/query/{export-format}) API doesn't accept arbitrary `?key=value` URL parameters, so effectively this is broken for ALL export formats (eg: CSV, XLSX, etc) -- not just JSON.

* (The BE endpoint DOES accept the `?parameters=...` [workaround](https://github.com/metabase/metabase/issues/5674#issuecomment-393903707 ), but this is clunky,  undocumented, and unexpected since it doesn't match the frontend behavior where it works properly according to the docs)

https://www.metabase.com/docs/v0.53/embedding/public-links#filter-parameters

🔧  I have a draft fix for this, so LMK if there's interest and I'll open a PR.
