### ISSUE TITLE
Cannot add new ClickHouse connection in Metabase 54+ with ssl=true&sslmode=none JDBC options (worked in previous versions)

### ISSUE THREAD

**Issue by Y-55** [metabase/metabase#58129]
### Describe the bug

We have Metabase 52+ running in production with the ClickHouse plugin, and ClickHouse connections work as expected. While testing an upgrade to Metabase 54+ locally, I am unable to add a new ClickHouse database connection. The same connection details work in production (52+ with plugin), but fail locally on 54+.

### To Reproduce

Run Metabase 54+ locally (fresh instance, no plugins in /plugins).

Go to Admin > Databases > Add a database.

Select ClickHouse.

Enter connection details (host, port, username, password, database).

Enable "Use a secure connection (SSL)".

In "Additional JDBC connection string options", set:
ssl=true&sslmode=none

Attempt to save/test the connection.

![Image](https://github.com/user-attachments/assets/899fb16e-7744-44db-af3d-71264e88cc3e)

### Expected behavior

Metabase should successfully connect to the ClickHouse database using the provided details, as it did in 52+ with the plugin.

### Logs

[d590165c-67d2-426b-b5a4-d20c42ba2125] 2025-05-18T16:56:48+03:00 ERROR metabase.driver.util Failed to connect to Database,java.sql.SQLException: Failed to create connection,	at com.clickhouse.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:104),	at com.clickhouse.jdbc.Driver.connect(Driver.java:123),	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:97),	at metabase.plugins.jdbc_proxy$proxy_driver$reify__96453.connect(jdbc_proxy.clj:37),	at java.sql/java.sql.DriverManager.getConnection(Unknown Source),	at java.sql/java.sql.DriverManager.getConnection(Unknown Source),	at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271),	at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250),	at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411),	at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274),	at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111),	at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093),	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182),	at clojure.java.jdbc$query.invoke(jdbc.clj:1144),	at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160),	at clojure.java.jdbc$query.invoke(jdbc.clj:1144),	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:395),	at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:392),	at metabase.driver.sql_jdbc.connection$can_connect_QMARK_$fn__62495.invoke(connection.clj:404)
[d590165c-67d2-426b-b5a4-d20c42ba2125] 2025-05-18T16:56:48+03:00 ERROR metabase.api.database Cannot connect to Database,clojure.lang.ExceptionInfo: Failed to create connection {:message "Failed to create connection"},	at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:190),	at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:161),	at clojure.lang.RestFn.invoke(RestFn.java:445),	at metabase.api.database$test_database_connection.invokeStatic(database.clj:729),	at metabase.api.database$test_database_connection.doInvoke(database.clj:719),	at clojure.lang.RestFn.invoke(RestFn.java:428),	at metabase.api.database$test_connection_details111648__111649.invokeStatic(database.clj:783),	at metabase.api.database$test_connection_details111648__111649.invoke(database.clj:763),	at metabase.api.database$fn__111656$fn__111662.invoke(database.clj:807),	at metabase.api.macros$_core_fn96155__96156$core_fn__96157.invoke(macros.clj:415),	at metabase.api.macros$endpoint_handler_STAR_96199__96201$handler__96205.invoke(macros.clj:611),	at metabase.api.macros$build_ns_handler96232__96233$ns_handler_STAR___96234.invoke(macros.clj:675),	at metabase.api.open_api.HandlerWithOpenAPISpec.invoke(open_api.clj:42),	at metabase.server.middleware.auth$enforce_authentication$fn__106915.invoke(auth.clj:23),	at metabase.api.open_api.HandlerWithOpenAPISpec.invoke(open_api.clj:42),	at metabase.api.util.handlers$_route_map_handler$fn__106871.invoke(handlers.clj:23),	at metabase.api.open_api.HandlerWithOpenAPISpec.invoke(open_api.clj:42),	at compojure.core$routes$fn__106808$f__106809.invoke(core.clj:198),	at compojure.core$routes$fn__106808$f__106809$respond_SINGLEQUOTE___106810.invoke(core.clj:197)
[d590165c-67d2-426b-b5a4-d20c42ba2125] 2025-05-18T16:56:48+03:00 DEBUG metabase.server.middleware.log POST /api/database 400 631ms (0 DB calls) {:metabase-user-id 1} 
{:message "Failed to create connection"}

### Information about your Metabase installation

```JSON
{
  "browser-info": {
    "language": "en-US",
    "platform": "MacIntel",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36",
    "vendor": "Google Inc."
  },
  "metabase-info": {
    "databases": [
      "h2"
    ],
    "run-mode": "prod",
    "plan-alias": "",
    "version": {
      "date": "2025-05-15",
      "tag": "v0.54.8",
      "hash": "6a2ed8f"
    },
    "settings": {
      "report-timezone": null
    },
    "hosting-env": "unknown",
    "application-database": "postgres",
    "application-database-details": {
      "database": {
        "name": "PostgreSQL",
        "version": "17.5 (Debian 17.5-1.pgdg120+1)"
      },
      "jdbc-driver": {
        "name": "PostgreSQL JDBC Driver",
        "version": "42.7.4"
      }
    }
  },
  "system-info": {
    "file.encoding": "UTF-8",
    "java.runtime.name": "OpenJDK Runtime Environment",
    "java.runtime.version": "21.0.7+6-LTS",
    "java.vendor": "Eclipse Adoptium",
    "java.vendor.url": "https://adoptium.net/",
    "java.version": "21.0.7",
    "java.vm.name": "OpenJDK 64-Bit Server VM",
    "java.vm.version": "21.0.7+6-LTS",
    "os.name": "Linux",
    "os.version": "6.10.14-linuxkit",
    "user.language": "en",
    "user.timezone": "GMT"
  }
}
```

### Severity

blocking an upgrade

### Additional context

The ClickHouse driver is now bundled and maintained by the Metabase team as of 54+ ([reference](https://github.com/ClickHouse/metabase-clickhouse-driver)).

The same connection details work in production (Metabase 52+ with plugin).

The issue occurs only when adding a new ClickHouse connection in 54+.

I have confirmed there are no old driver JARs present and have followed the official documentation for connection settings ([reference](https://www.metabase.com/docs/latest/databases/connections/clickhouse)).

This appears to be a regression introduced with the new bundled driver.

**Comment by rileythomp** [comment]
Hi @Y-55 could you let me know what version of the clickhouse-metabase plugin you were using?

**Comment by Y-55** [comment]
Hi @rileythomp, clickhouse-metabase plugin version is 1.51.0.

Deployed in k8s using https://github.com/pmint93/helm-charts/blob/master/charts/metabase/values.yaml helm chart, overriding this value to download the plugin inside the container

> extraInitContainers:
>  - name: download-modules
>    image: "curlimages/curl:7.70.0"
>    imagePullPolicy: "IfNotPresent"
>    volumeMounts:
>      - name: plugins
>        mountPath: /plugins
>    workingDir: /plugins
>    command:
>      - "/bin/sh"
>      - "-ec"
>      - |
>        curl -Lso /plugins/ch.jar \
>        https://github.com/ClickHouse/metabase-clickhouse-driver/releases/download/1.51.0/clickhouse.metabase-driver.jar
>

**Comment by rileythomp** [comment]
We think this is due to an issue with the Clickhouse JDBC driver rather than Metabase. We've opened [an issue](https://github.com/ClickHouse/clickhouse-java/issues/2389) on their repo and will be keep an eye on it to know when this issue can be resolved.

**Comment by Serdnaley** [comment]
Same issue reproduced w/o SSL.

Docker compose:
```yaml
services:
  # PostgreSQL Database (for Metabase)
  postgres:
    image: postgres:17-alpine
    container_name: analytics_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_METABASE_DB:-metabase}
      POSTGRES_USER: ${POSTGRES_METABASE_USER:-metabase_user}
      POSTGRES_PASSWORD: ${POSTGRES_METABASE_PASSWORD:-metabase_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - analytics_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_METABASE_USER:-metabase_user} -d ${POSTGRES_METABASE_DB:-metabase}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ClickHouse Analytics Database
  clickhouse:
    image: clickhouse:latest
    container_name: analytics_clickhouse
    restart: unless-stopped
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-analytics}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-analytics}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-clickhouse_password}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT:-1}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./config/clickhouse/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./config/clickhouse/users.xml:/etc/clickhouse-server/users.xml:ro
      - ./init-scripts/clickhouse:/docker-entrypoint-initdb.d:ro
    ports:
      - "${CLICKHOUSE_HTTP_PORT:-8123}:8123"
      - "${CLICKHOUSE_TCP_PORT:-9000}:9000"
      - "${CLICKHOUSE_MYSQL_PORT:-9004}:9004"
      - "${CLICKHOUSE_POSTGRES_PORT:-9005}:9005"
    networks:
      - analytics_network
      - peerdb_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  # Metabase Analytics Platform
  metabase:
    image: metabase/metabase:latest
    platform: linux/arm64
    container_name: analytics_metabase
    restart: unless-stopped
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${POSTGRES_METABASE_DB:-metabase}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_METABASE_USER:-metabase_user}
      MB_DB_PASS: ${POSTGRES_METABASE_PASSWORD:-metabase_password}
      MB_DB_HOST: postgres
      MB_ENCRYPTION_SECRET_KEY: ${MB_ENCRYPTION_SECRET_KEY:-your-secret-key-here}
      JAVA_OPTS: "-Xmx2g"
    volumes:
      - metabase_data:/metabase-data
    ports:
      - "${METABASE_PORT:-4000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - analytics_network
      - peerdb_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
```

Connection info:
<img width="1218" height="2241" alt="Image" src="https://github.com/user-attachments/assets/d9ffc9f5-e8b5-48b1-abd6-9477dd19d327" />
Password is set from .env and it’s correct, tested with cli.

Logs:
```
2025-09-01 20:49:00,020 INFO driver.impl :: Initializing driver :clickhouse... 
2025-09-01 20:49:00,022 INFO classloader.impl :: Added URL file:/plugins/clickhouse.metabase-driver.jar to classpath 
2025-09-01 20:49:00,023 DEBUG plugins.init-steps :: Loading plugin namespace metabase.driver.clickhouse... 
2025-09-01 20:49:00,105 INFO driver.impl :: Registered driver :clickhouse (parents: [:sql-jdbc]) 🚚 
2025-09-01 20:49:00,129 DEBUG plugins.jdbc-proxy :: Registering JDBC proxy driver for com.clickhouse.jdbc.ClickHouseDriver... 
2025-09-01 20:49:00,131 INFO metabase.util :: Load lazy loading driver :clickhouse took 107.4 ms 
2025-09-01 20:49:00,181 ERROR driver.util :: Failed to connect to Database 
java.sql.SQLException: Failed to create connection
        at com.clickhouse.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:104)
        at com.clickhouse.jdbc.Driver.connect(Driver.java:123)
        at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:97)
        at metabase.plugins.jdbc_proxy$proxy_driver$reify__98324.connect(jdbc_proxy.clj:37)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
        at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:368)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:365)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_$fn__95344.invoke(connection.clj:377)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection$fn__95326.invoke(connection.clj:353)
        at metabase.driver.sql_jdbc.connection.ssh_tunnel$do_with_ssh_tunnel.invokeStatic(ssh_tunnel.clj:152)
        at metabase.driver.sql_jdbc.connection.ssh_tunnel$do_with_ssh_tunnel.invoke(ssh_tunnel.clj:141)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:348)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:344)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:376)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:372)
        at metabase.driver.clickhouse$fn__136788.invokeStatic(clickhouse.clj:172)
        at metabase.driver.clickhouse$fn__136788.invoke(clickhouse.clj:152)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.driver.util$can_connect_with_details_QMARK_$fn__55842.invoke(util.clj:135)
        at clojure.core$binding_conveyor_fn$fn__5844.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Host cannot be null or empty string
        at com.clickhouse.data.ClickHouseChecker.newException(ClickHouseChecker.java:19)
        at com.clickhouse.data.ClickHouseChecker.nonEmpty(ClickHouseChecker.java:250)
        at com.clickhouse.client.ClickHouseNode.<init>(ClickHouseNode.java:892)
        at com.clickhouse.client.ClickHouseNode.of(ClickHouseNode.java:797)
        at com.clickhouse.client.api.Client.lambda$new$0(Client.java:162)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at com.clickhouse.client.api.Client.<init>(Client.java:161)
        at com.clickhouse.client.api.Client.<init>(Client.java:116)
        at com.clickhouse.client.api.Client$Builder.build(Client.java:1052)
        at com.clickhouse.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:92)
        ... 35 more
2025-09-01 20:49:00,192 ERROR driver.util :: Failed to connect to Database 
java.sql.SQLException: Failed to create connection
        at com.clickhouse.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:104)
        at com.clickhouse.jdbc.Driver.connect(Driver.java:123)
        at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:97)
        at metabase.plugins.jdbc_proxy$proxy_driver$reify__98324.connect(jdbc_proxy.clj:37)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
        at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:368)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:365)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_$fn__95344.invoke(connection.clj:377)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection$fn__95326.invoke(connection.clj:353)
        at metabase.driver.sql_jdbc.connection.ssh_tunnel$do_with_ssh_tunnel.invokeStatic(ssh_tunnel.clj:152)
        at metabase.driver.sql_jdbc.connection.ssh_tunnel$do_with_ssh_tunnel.invoke(ssh_tunnel.clj:141)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:348)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:344)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:376)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:372)
        at metabase.driver.clickhouse$fn__136788.invokeStatic(clickhouse.clj:172)
        at metabase.driver.clickhouse$fn__136788.invoke(clickhouse.clj:152)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.driver.util$can_connect_with_details_QMARK_$fn__55842.invoke(util.clj:135)
        at clojure.core$binding_conveyor_fn$fn__5844.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Host cannot be null or empty string
        at com.clickhouse.data.ClickHouseChecker.newException(ClickHouseChecker.java:19)
        at com.clickhouse.data.ClickHouseChecker.nonEmpty(ClickHouseChecker.java:250)
        at com.clickhouse.client.ClickHouseNode.<init>(ClickHouseNode.java:892)
        at com.clickhouse.client.ClickHouseNode.of(ClickHouseNode.java:797)
        at com.clickhouse.client.api.Client.lambda$new$0(Client.java:162)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at com.clickhouse.client.api.Client.<init>(Client.java:161)
        at com.clickhouse.client.api.Client.<init>(Client.java:116)
        at com.clickhouse.client.api.Client$Builder.build(Client.java:1052)
        at com.clickhouse.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:92)
        ... 35 more
2025-09-01 20:49:00,196 ERROR warehouses.api :: Cannot connect to Database 
clojure.lang.ExceptionInfo: Failed to create connection {:message "Failed to create connection"}
        at metabase.driver.util$can_connect_with_details_QMARK_.invokeStatic(util.clj:152)
        at metabase.driver.util$can_connect_with_details_QMARK_.doInvoke(util.clj:123)
        at clojure.lang.RestFn.invoke(RestFn.java:445)
        at metabase.warehouses.api$test_database_connection.invokeStatic(api.clj:760)
        at metabase.warehouses.api$test_database_connection.doInvoke(api.clj:750)
        at clojure.lang.RestFn.invoke(RestFn.java:428)
        at metabase.warehouses.api$test_connection_details.invokeStatic(api.clj:814)
        at metabase.warehouses.api$test_connection_details.invoke(api.clj:794)
        at metabase.warehouses.api$fn__120454$fn__120460.invoke(api.clj:838)
        at metabase.api.macros$_core_fn$core_fn__88186.invoke(macros.clj:416)
        at metabase.api.macros$endpoint_handler_STAR_$handler__88228.invoke(macros.clj:612)
        at metabase.api.macros$build_ns_handler$ns_handler_STAR___88254.invoke(macros.clj:676)
        at metabase.api.open_api.HandlerWithOpenAPISpec.invoke(open_api.clj:42)
        at metabase.api.routes.common$enforce_authentication$fn__113600.invoke(common.clj:91)
        at metabase.api.open_api.HandlerWithOpenAPISpec.invoke(open_api.clj:42)
        at metabase.api.util.handlers$_route_map_handler$fn__99004.invoke(handlers.clj:23)
        at metabase.api.open_api.HandlerWithOpenAPISpec.invoke(open_api.clj:42)
        at compojure.core$routes$fn__98941$f__98942.invoke(core.clj:198)
        at compojure.core$routes$fn__98941$f__98942$respond_SINGLEQUOTE___98943.invoke(core.clj:197)
        at metabase.api_routes.routes$fn__123964.invokeStatic(routes.clj:97)
        at metabase.api_routes.routes$fn__123964.invoke(routes.clj:96)
        at metabase.api.open_api.HandlerWithOpenAPISpec.invoke(open_api.clj:42)
        at compojure.core$routes$fn__98941$f__98942.invoke(core.clj:198)
        at compojure.core$routes$fn__98941.invoke(core.clj:200)
        at metabase.api.open_api.HandlerWithOpenAPISpec.invoke(open_api.clj:42)
        at clojure.lang.Var.invoke(Var.java:395)
        at metabase.server.routes$api_handler$api_handler_STAR___99593.invoke(routes.clj:71)
        at compojure.core$routes$fn__98941$f__98942.invoke(core.clj:198)
        at compojure.core$routes$fn__98941.invoke(core.clj:200)
        at compojure.core$make_context$handler__98969.invoke(core.clj:290)
        at compojure.core$make_context$fn__98973.invoke(core.clj:300)
        at compojure.core$routes$fn__98941$f__98942.invoke(core.clj:198)
        at compojure.core$routes$fn__98941$f__98942$respond_SINGLEQUOTE___98943.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__98922.invoke(core.clj:153)
        at compojure.core$routes$fn__98941$f__98942.invoke(core.clj:198)
        at compojure.core$routes$fn__98941$f__98942$respond_SINGLEQUOTE___98943.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__98922.invoke(core.clj:153)
        at compojure.core$routes$fn__98941$f__98942.invoke(core.clj:198)
        at compojure.core$routes$fn__98941$f__98942$respond_SINGLEQUOTE___98943.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__98922.invoke(core.clj:153)
        at compojure.core$routes$fn__98941$f__98942.invoke(core.clj:198)
        at compojure.core$routes$fn__98941$f__98942$respond_SINGLEQUOTE___98943.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__98922.invoke(core.clj:153)
        at compojure.core$routes$fn__98941$f__98942.invoke(core.clj:198)
        at compojure.core$routes$fn__98941$f__98942$respond_SINGLEQUOTE___98943.invoke(core.clj:197)
        at compojure.core$wrap_route_matches$fn__98922.invoke(core.clj:153)
        at compojure.core$routes$fn__98941$f__98942.invoke(core.clj:198)
        at compojure.core$routes$fn__98941$f__98942$respond_SINGLEQUOTE___98943.invoke(core.clj:197)
        at metabase.api.util.handlers$_route_map_handler$fn__99004.invoke(handlers.clj:24)
        at metabase.api.open_api.HandlerWithOpenAPISpec.invoke(open_api.clj:42)
        at metabase.api.util.handlers$_route_map_handler$fn__99004.invoke(handlers.clj:23)
        at metabase.api.open_api.HandlerWithOpenAPISpec.invoke(open_api.clj:42)
        at compojure.core$routes$fn__98941$f__98942.invoke(core.clj:198)
        at compojure.core$routes$fn__98941.invoke(core.clj:200)
        at metabase.server.middleware.exceptions$catch_uncaught_exceptions$fn__117864.invoke(exceptions.clj:77)
        at metabase.server.middleware.exceptions$catch_api_exceptions$fn__117861.invoke(exceptions.clj:66)
        at metabase.server.middleware.log$log_api_call$fn__110502$fn__110503$fn__110504.invoke(log.clj:224)
        at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invokeStatic(diagnostic.clj:17)
        at metabase.driver.sql_jdbc.execute.diagnostic$do_with_diagnostic_info.invoke(diagnostic.clj:12)
        at metabase.server.middleware.log$log_api_call$fn__110502$fn__110503.invoke(log.clj:215)
        at toucan2.execute$do_with_call_counts.invokeStatic(execute.clj:112)
        at toucan2.execute$do_with_call_counts.invoke(execute.clj:103)
        at metabase.server.middleware.log$log_api_call$fn__110502.invoke(log.clj:214)
        at metabase.server.middleware.browser_cookie$ensure_browser_id_cookie$fn__124807.invoke(browser_cookie.clj:40)
        at metabase.server.middleware.security$add_security_headers$fn__117834.invoke(security.clj:292)
        at metabase.server.middleware.json$wrap_json_body$fn__117007.invoke(json.clj:128)
        at metabase.server.middleware.offset_paging$handle_paging$fn__119698.invoke(offset_paging.clj:48)
        at metabase.server.middleware.json$wrap_streamed_json_response$fn__116995.invoke(json.clj:83)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__125074.invoke(keyword_params.clj:55)
        at ring.middleware.params$wrap_params$fn__125093.invoke(params.clj:77)
        at metabase.server.middleware.misc$maybe_set_site_url$fn__109581.invoke(misc.clj:59)
        at metabase.server.middleware.session$reset_session_timeout$fn__124795.invoke(session.clj:270)
        at metabase.server.middleware.session$bind_current_user$fn__124788$fn__124789.invoke(session.clj:245)
        at metabase.request.session$do_with_current_user$fn__76421.invoke(session.clj:52)
        at metabase.request.session$do_with_current_user$do_with_user_local_values__76416.invoke(session.clj:48)
        at metabase.request.session$do_with_current_user.invokeStatic(session.clj:49)
        at metabase.request.session$do_with_current_user.invoke(session.clj:31)
        at metabase.server.middleware.session$bind_current_user$fn__124788.invoke(session.clj:244)
        at metabase.server.middleware.session$wrap_current_user_info$fn__124784.invoke(session.clj:220)
        at metabase.analytics.sdk$embedding_mw$embedding_mw_fn__55354.invoke(sdk.clj:68)
        at metabase.server.middleware.session$wrap_session_key$fn__124752.invoke(session.clj:82)
        at metabase.server.middleware.auth$wrap_static_api_key$fn__111156.invoke(auth.clj:17)
        at ring.middleware.cookies$wrap_cookies$fn__124994.invoke(cookies.clj:200)
        at metabase.server.middleware.misc$add_content_type$fn__109563.invoke(misc.clj:28)
        at metabase.server.middleware.misc$disable_streaming_buffering$fn__109589.invoke(misc.clj:75)
        at ring.middleware.gzip$wrap_gzip$fn__125036.invoke(gzip.clj:86)
        at metabase.server.middleware.request_id$wrap_request_id$fn__100206.invoke(request_id.clj:10)
        at metabase.server.middleware.misc$bind_request$fn__109592$fn__109593.invoke(misc.clj:87)
        at metabase.request.current$do_with_current_request.invokeStatic(current.clj:19)
        at metabase.request.current$do_with_current_request.invoke(current.clj:15)
        at metabase.server.middleware.misc$bind_request$fn__109592.invoke(misc.clj:86)
        at metabase.server.middleware.ssl$redirect_to_https_middleware$fn__124823.invoke(ssl.clj:42)
        at metabase.server.instance$async_proxy_handler$fn__110237.invoke(instance.clj:81)
        at metabase.server.instance.proxy$org.eclipse.jetty.ee9.servlet.ServletHandler$ff19274a.doHandle(Unknown Source)
        at org.eclipse.jetty.ee9.nested.ScopedHandler.handle(ScopedHandler.java:127)
        at metabase.server.statistics_handler$new_handler$fn__98186.invoke(statistics_handler.clj:105)
        at metabase.server.statistics_handler.proxy$org.eclipse.jetty.ee9.nested.HandlerWrapper$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.ee9.nested.HandlerWrapper.handle(HandlerWrapper.java:124)
        at org.eclipse.jetty.ee9.nested.ScopedHandler.nextHandle(ScopedHandler.java:197)
        at org.eclipse.jetty.ee9.nested.ContextHandler.doHandle(ContextHandler.java:1045)
        at org.eclipse.jetty.ee9.nested.ScopedHandler.nextScope(ScopedHandler.java:164)
        at org.eclipse.jetty.ee9.servlet.ServletHandler.doScope(ServletHandler.java:483)
        at metabase.server.instance.proxy$org.eclipse.jetty.ee9.servlet.ServletHandler$ff19274a.doScope(Unknown Source)
        at org.eclipse.jetty.ee9.nested.ScopedHandler.nextScope(ScopedHandler.java:162)
        at org.eclipse.jetty.ee9.nested.ContextHandler.doScope(ContextHandler.java:966)
        at org.eclipse.jetty.ee9.nested.ScopedHandler.handle(ScopedHandler.java:125)
        at org.eclipse.jetty.ee9.nested.ContextHandler.handle(ContextHandler.java:1719)
        at org.eclipse.jetty.ee9.nested.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1565)
        at org.eclipse.jetty.ee9.nested.HttpChannel.dispatch(HttpChannel.java:724)
        at org.eclipse.jetty.ee9.nested.HttpChannel.handle(HttpChannel.java:512)
        at org.eclipse.jetty.ee9.nested.ContextHandler$CoreContextHandler$CoreToNestedHandler.handle(ContextHandler.java:3029)
        at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1071)
        at org.eclipse.jetty.server.Server.handle(Server.java:182)
        at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:678)
        at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:416)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:480)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:443)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:981)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1211)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1166)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: Failed to create connection
        at com.clickhouse.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:104)
        at com.clickhouse.jdbc.Driver.connect(Driver.java:123)
        at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:97)
        at metabase.plugins.jdbc_proxy$proxy_driver$reify__98324.connect(jdbc_proxy.clj:37)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql/java.sql.DriverManager.getConnection(Unknown Source)
        at clojure.java.jdbc$get_driver_connection.invokeStatic(jdbc.clj:271)
        at clojure.java.jdbc$get_driver_connection.invoke(jdbc.clj:250)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:411)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:274)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1111)
        at clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1093)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1182)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at clojure.java.jdbc$query.invokeStatic(jdbc.clj:1160)
        at clojure.java.jdbc$query.invoke(jdbc.clj:1144)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invokeStatic(connection.clj:368)
        at metabase.driver.sql_jdbc.connection$can_connect_with_spec_QMARK_.invoke(connection.clj:365)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_$fn__95344.invoke(connection.clj:377)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection$fn__95326.invoke(connection.clj:353)
        at metabase.driver.sql_jdbc.connection.ssh_tunnel$do_with_ssh_tunnel.invokeStatic(ssh_tunnel.clj:152)
        at metabase.driver.sql_jdbc.connection.ssh_tunnel$do_with_ssh_tunnel.invoke(ssh_tunnel.clj:141)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invokeStatic(connection.clj:348)
        at metabase.driver.sql_jdbc.connection$do_with_connection_spec_for_testing_connection.invoke(connection.clj:344)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invokeStatic(connection.clj:376)
        at metabase.driver.sql_jdbc.connection$can_connect_QMARK_.invoke(connection.clj:372)
        at metabase.driver.clickhouse$fn__136788.invokeStatic(clickhouse.clj:172)
        at metabase.driver.clickhouse$fn__136788.invoke(clickhouse.clj:152)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at metabase.driver.util$can_connect_with_details_QMARK_$fn__55842.invoke(util.clj:135)
        at clojure.core$binding_conveyor_fn$fn__5844.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        ... 1 more
Caused by: java.lang.IllegalArgumentException: Host cannot be null or empty string
        at com.clickhouse.data.ClickHouseChecker.newException(ClickHouseChecker.java:19)
        at com.clickhouse.data.ClickHouseChecker.nonEmpty(ClickHouseChecker.java:250)
        at com.clickhouse.client.ClickHouseNode.<init>(ClickHouseNode.java:892)
        at com.clickhouse.client.ClickHouseNode.of(ClickHouseNode.java:797)
        at com.clickhouse.client.api.Client.lambda$new$0(Client.java:162)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at com.clickhouse.client.api.Client.<init>(Client.java:161)
        at com.clickhouse.client.api.Client.<init>(Client.java:116)
        at com.clickhouse.client.api.Client$Builder.build(Client.java:1052)
        at com.clickhouse.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:92)
        ... 35 more
2025-09-01 20:49:00,341 DEBUG middleware.log :: POST /api/database 400 326ms (0 DB calls) {:metabase-user-id 1} 
{:message "Failed to create connection"}
```

**Comment by Serdnaley** [comment]
Fixed my case... The JDBC Driver does not support underscores in URLs 🤦‍♂️
@Y-55 it might your case as well I guess.
But still @rileythomp I think it's better to add some kind of validation for those cases.

**Comment by Y-55** [comment]
Thanks for your input, @Serdnaley. It looks like you tested with ClickHouse over HTTP port without SSL. The case here is different,  My ClickHouse only allows HTTPS for security reasons. But anyway I tried again without underscores as you mentioned, but it still failed with the same issue. As @rileythomp mentioned, this seems to be a JDBC driver issue.

By the way, @rileythomp, is there any update on this? I’m currently running Metabase v52 and would really like to upgrade to access the new features in the latest versions.

**Comment by stevegoulet** [comment]
Following - having the same issue whereby I need HTTPS connectivity between Metabase and ClickHouse

**Comment by quantum-pilot** [comment]
I had the same problem as @Serdnaley - tried connecting without SSL but for some reason, it enforced SSL. I tried these in my connection params `connection_timeout=1000&socket_timeout=300000&ssl=false&secure=false&sslmode=none` and then it worked.

**Comment by George-k-tech** [comment]
I'm encountering the same challenge as well. Metabase keeps throwing "query failed" whether I connect over HTTP or HTTPS. Even after explicitly disabling SSL (ssl=false, secure=false, sslmode=none), the connection still fails. Looks like the same bug affecting ClickHouse connections.

**Comment by Tony-metabase** [comment]
Hi @quantum-pilot and @George-k-tech and @stevegoulet are you passing custom certificates?

This is not a bug. Enabling SSL (for https URLs that do not require custom certificates) will work. What is missing is the feature to upload the certificates like in PSQL driver.

https://github.com/ClickHouse/metabase-clickhouse-driver/issues/136

When using the driver with on-premises Metabase, it is still possible to mount the certs into the MB container and specify the path in the advanced jdbc options.

There is more info about this here:

https://github.com/ClickHouse/metabase-clickhouse-driver/issues/41

**Comment by quantum-pilot** [comment]
> This is not a bug. Enabling SSL (for https URLs that do not require custom certificates) will work. What is missing is the feature to upload the certificates like in PSQL driver.

I'm pretty sure both of us were talking about connection without SSL.

**Comment by Tony-metabase** [comment]
Then why are you commenting on an issue which states "Support self-signed certificates on Clickhouse" ?? If it's a separate issue please open a separate BUG. Please check https://github.com/ClickHouse/clickhouse-java/issues/2389

The issue mentioned by Serdnley is because The JDBC Driver does not support underscores in URLs ... It seems you're talking about something completely different.

**Comment by quantum-pilot** [comment]
> Then why are you commenting on an issue which states "Support self-signed certificates on Clickhouse" ??

For the same reason Serdnley did when he posted the error attempting to connect without SSL (why didn't you ask him btw?) - that it *might* be relevant. If it's not, then please ignore it and move on - I didn't ask you for anything now, did I? I was merely stating how I encountered the same connection creation issue as Serdnley when I tried without SSL and how I was able to fix it (it wasn't underscore for me). My intention was that someone may find it helpful. It's not my problem if you misread my comment. If you don't want people to comment at all, then lock the issue.

**Comment by Tony-metabase** [comment]
It just adds confusion to an already skewed thread `sslmode=none` isn't supported by the JDBC driver

https://github.com/ClickHouse/clickhouse-java/issues/2389

**Comment by dragonsahead** [comment]
@Y-55 does this work now? cc @Tony-metabase

**Comment by Y-55** [comment]
Not sure @dragonsahead, We were in a hurry, so we started using a real certificates instead of waiting this to resolve.

but anyway, look at the issue @rileythomp opened last time [this one](https://github.com/metabase/metabase/issues/58129#issuecomment-2910125880), it seems Clickhouse team just closed it yesterday. so may be in the next Metabase versions when they update the client we get this issue resolved.
