### ISSUE TITLE
Floating-point rounding errors in UI for very large integers (JS stores all numbers as 64-bit floats)

### ISSUE THREAD

**Issue by bcbob** [metabase/metabase#5816]
Our data has several primary / foreign key ID fields that are 8 byte BIGINT's.
So fairly large numbers, many above 256^7, are involved.

Metabase is unable to display the large numbers as answers, and appears to round them off when displaying them.

Among other issues, this creates problems with foreign key links.

The underlying data is correct - and downloading the answer as a CSV yields the correct numbers, without an apparent rounding error.

It is not possible to drill through the data, because Metabase appears to use the displayed number (rather than the actual query result as shown in the CSV download) to make the link / drill down. The result is an error screen when drilling down for linked foreign key records.

The following screen shots show the problem:

1. THE QUESTION RESULT DOWNLOADED AS A CSV, showing the correct large numbers:

![image](https://user-images.githubusercontent.com/30799811/29706747-32c90dc4-8983-11e7-8f7a-722d13ddd061.png)

2. THE QUESTION RESULT DISPLAYED ON SCREEN, showing the apparently rounded numbers:

![image](https://user-images.githubusercontent.com/30799811/29706803-6299142c-8983-11e7-9f73-8f036a5404ba.png)

3. And the normal error screen when attempting to drill down / click through on the rounded numbers:

![image](https://user-images.githubusercontent.com/30799811/29706857-8f7327b2-8983-11e7-8431-8667137859f1.png)

⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by salsakran** [comment]
what database is this on? and can you share the schema or create statement for the tables that have these PKs?

**Comment by bcbob** [comment]
MySQL on AWS RDS.
I can source the create statement.
The PK's are 8 byte integers. Which are too big for Metabase Answers to display, as shown.

Of course, it's unusual to have such large size PK's, and we have addressed the problem by reducing the size of the PK's to under 6 bytes (256^6). This displays fine on Metabase without a rounding problem.

It would be good to address the rounding bug at some point. We have worked around it by changing our PK setup. (We are importing data into MySQL from a legacy relational system distributed across multiple locations, and are combining the location ID with the order ID to make a single unique ID for all the merged location data. Originally the combined ID used more than 6 bytes. We have now addressed the issue and got it under 6 bytes (281,474,976,710,656), so our Metabase questions and answers are working.

**Comment by trifle** [comment]
+1, this impacts me while using Facebook IDs as natural PKs.
Those IDs are up to 17 digits (potentially more?) such as 10153934773129407.

**Comment by trifle** [comment]
By the way, this was also reported in #5076

**Comment by lindaro** [comment]
transfering from #6775

same issue, here's the schema as request @salsakran 

`CREATE TABLE `trades` (
  `id` bigint(20) NOT NULL,
  `exprice` decimal(24,6) NOT NULL,
  `excost` decimal(32,8) NOT NULL,
  `volume` decimal(28,8) NOT NULL,
  `margin` decimal(32,8) NOT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
`

**Comment by lindaro** [comment]
I tried the suggestion in #5076 and manually changed bigint mapper in the mysql driver to text.

under `show original schema` the `id field is correctly mapped as a Text field
![screenshot from 2018-02-07 15-42-28](https://user-images.githubusercontent.com/17762156/35947623-a5468148-0c1d-11e8-9698-b81ca8215880.png)

However, the bug persists for some reason and still the numbers are being truncated and the frontend still thinks its a number.

I'll continue to track this down, advice is appreciated.

**Comment by samgaw** [comment]
The use of BIGINT as primary keys is becoming a lot more common, with a lot of frameworks switching to it as the default; in addition to libs like [KSUID](https://github.com/segmentio/ksuid), Snowflake, Instagram-style sharding etc introducing large numbers ranging from 62 to 128-bit.

It's a [known Javascript limitation](http://www.ecma-international.org/ecma-262/5.1/#sec-8.5) so it's not specific to any particular DB layer. And while I could cast affected columns to VARCHAR in a SQL question so that records display properly, this breaks FK click-throughs, removing a fantastic feature of being able to drill through datasets.

I'm not sure what the policy is but is there any willingness to introduce something like https://github.com/MikeMcl/bignumber.js on the frontend to fix this? I'm happy to give it a go if there's a possibility of the PR being accepted.

**Comment by samgaw** [comment]
Actually it turns out I underestimated this. Running the queries against the REST API I'm seeing the same issue so I probably should have spent more time reading other people's comments before opening my mouth :speak_no_evil:

Running `curl 'http://localhost:13228/api/dataset' \
  --data '{"database":2,"type":"native","native":{"query":"SELECT \"id\" AS \"id\" FROM \"public\".\"test\" LIMIT  1","template_tags":{}},"parameters":[]}'` returns:
```json
{
  "started_at": "2018-10-03T23:59:08.373Z",
  "json_query": {
    "database": 2,
    "type": "native",
    "native": {
      "query": "SELECT \"id\" AS \"id\" FROM \"public\".\"test\" LIMIT  1",
      "template_tags": {}
    },
    "parameters": [],
    "constraints": {
      "max-results": 10000,
      "max-results-bare-rows": 2000
    }
  },
  "average_execution_time": null,
  "status": "completed",
  "context": "ad-hoc",
  "row_count": 1,
  "running_time": 11,
  "data": {
    "rows": [
      [
        49135538019501064
      ]
    ],
    "columns": [
      "id"
    ],
    "native_form": {
      "query": "SELECT \"id\" AS \"id\" FROM \"public\".\"test\" LIMIT  1",
      "template_tags": {},
      "params": []
    },
    "cols": [
      {
        "name": "id",
        "display_name": "ID",
        "base_type": "type/Integer",
        "remapped_to": null,
        "remapped_from": null
      }
    ],
    "results_metadata": {
      "checksum": "+bTmln1907HRedu3YIhE6Q==",
      "columns": [
        {
          "name": "id",
          "display_name": "ID",
          "base_type": "type/Integer",
          "special_type": "type/PK",
          "fingerprint": null
        }
      ]
    }
  }
}
```

Whereas `curl 'http://localhost:13228/api/dataset' \
  --data '{"database":2,"type":"native","native":{"query":"SELECT \"id\"::varchar AS \"id\" FROM \"public\".\"test\" LIMIT  1","template_tags":{}},"parameters":[]}'` gives me the correct id:
```json
{
  "started_at": "2018-10-04T00:01:12.608Z",
  "json_query": {
    "database": 2,
    "type": "native",
    "native": {
      "query": "SELECT \"id\"::varchar AS \"id\" FROM \"public\".\"test\" LIMIT  1",
      "template_tags": {}
    },
    "parameters": [],
    "constraints": {
      "max-results": 10000,
      "max-results-bare-rows": 2000
    }
  },
  "average_execution_time": null,
  "status": "completed",
  "context": "ad-hoc",
  "row_count": 1,
  "running_time": 5,
  "data": {
    "rows": [
      [
        "49135538019501062"
      ]
    ],
    "columns": [
      "id"
    ],
    "native_form": {
      "query": "SELECT \"id\"::varchar AS \"id\" FROM \"public\".\"test\" LIMIT  1",
      "template_tags": {},
      "params": []
    },
    "cols": [
      {
        "name": "id",
        "display_name": "ID",
        "base_type": "type/Text",
        "remapped_to": null,
        "remapped_from": null
      }
    ],
    "results_metadata": {
      "checksum": "i9ufblIaTrvb9ZABfr3wCg==",
      "columns": [
        {
          "name": "id",
          "display_name": "ID",
          "base_type": "type/Text",
          "special_type": "type/PK",
          "fingerprint": null
        }
      ]
    }
  }
}
```
```
psql> SELECT id FROM test LIMIT 1; +
+ -- -- -- -- -- -- -- -- -- - +
| id                           |
|-- -- -- -- -- -- -- -- -- -- |
| 49135538019501062            |
+ -- -- -- -- -- -- -- -- -- - +
SELECT 1
Time: 0.008 s
```

**Comment by lindaro** [comment]
any word on this?

**Comment by TheAussieStew** [comment]
@mazameli Should this issue be re-opened since the commit was reverted in 0.33.2? #10387

**Comment by flamber** [comment]
@paulrosenzweig Re-open since it was reverted and change milestone?

**Comment by samgaw** [comment]
From my basic testing in my previous comment, the backend rounds large numbers as well; so the inclusion of a bigint lib on the frontend like #10387 is only handling the presentation. It seems to be related to how `cheshire` is wrapped for the JSON encoding.

ring-clojure/ring-json/issues/15 had a similar issue a few years back with cheshire rounding large floats and included a `:bigdecimals` param as a workaround. Is a similar custom type required in src/metabase/middleware/json.clj to handle large numbers?

**Comment by jvtrigueros** [comment]
I'm having this issue as well, the curious case here is that if I make the call via `curl` or Insomnia the results are correct, see attached:
![insomnia-query](https://user-images.githubusercontent.com/151656/67629039-4c5eaa80-f82d-11e9-9d7d-9608b1641097.png)

However, making the same query from the browser, the data from the server comes back incorrect, see attached:
![firefox-query](https://user-images.githubusercontent.com/151656/67629042-600a1100-f82d-11e9-8536-03e586d0248f.png)

As far as I know, I'm calling the API both in the same way via `/api/dataset` with the exact same input. The output is identical save for the rounded off IDs.

**Comment by smadan2703** [comment]
I am also facing the same issue. Is there any fix for this issue or workaround?

**Comment by banuragprdxn** [comment]
Would love a fix around this. This is the only issue that I am facing with Metabase.

**Comment by pan-christensen** [comment]
In addition to bigint being displayed incorrectly, it's also impossible to filter by these values in the GUI.

When I try to filter on account_id = 201912021829210865, the frontend changes the filter to 201912021829210880. This may give the rows of a completely different customer, or no rows at all. My users will not be able to understand this and may use incorrect data.

Converting the question to SQL will return the correct rows as the value is not rounded there. Joining on these columns in the GUI also works correctly.

**Comment by camsaul** [comment]
This is because JavaScript internally stores all numbers as 64-bit floating point numbers, so we're running into a rounding error. See [this SO post](https://stackoverflow.com/questions/8663298/json-transfer-of-bigint-12000000000002539-is-converted-to-12000000000002540) for an explanation.

Assuming the correct non-rounded value is actually coming back in the API response itself then I suppose we could address this by parsing the JSON in such a way as to automatically convert large numbers to things [`BigInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) as needed -- @paulrosenzweig do you have a sense of how easy this would be?

**Comment by camsaul** [comment]
alternatively maybe we could just parse all Integers in query results as BigInt and all floating-point numbers as whatever arbitrary Decimal class JavaScript has. Would that break a bunch of things?

**Comment by robdaemon** [comment]
It's even worse - JavaScript is a 64-bit float with a 52 bit mantissa.

In the past, I've had to work around this by returning any number >52 bit to the frontend as a string.

**Comment by camsaul** [comment]
That's one way we could approach that issue as well. Seems like it would be easy enough to do app-wide in the backend code. As long as the FE would still be able to handle the strings

**Comment by paulrosenzweig** [comment]
I like the string approach. I'm assuming we don't need to really support arithmetic for higher-precision types. It seems like this only comes up for ID fields. Given that, I think the client would probably keep them as strings rather than parsing into BigInts. The only potential issue I see is the difference in sorting (e.g. "1" < "10" < "2")

**Comment by sbelak** [comment]
Something to think about: moving to strings will break any automations/integrations people have built around our API (I know we don't give any guarantees, but still).

**Comment by areyouokevan** [comment]
Is there an ETA for this bug to be fixed? It's been an issue for way over a year now, 17 digits IDs are used nearly everywhere, Twitter, Discord, Facebook, ...

**Comment by fannigurt** [comment]
I can't make an analytics app based on Metabase - Facebook uses BIGINT in the ids for all it's all model.
Are the users really need to vote for this feature? 😀 

`select fb_ad.ad_id from fb_ad where fb_ad.ad_id = 23845047323130744;`
> 23 845 044 470 130 650

What?

**Comment by camsaul** [comment]
Fixed by #13107

**Comment by tw0517tw** [comment]
It's great to have this fixed! But we encountered into another problem that when clicking on the BIGINT fields to do further query, it shows DB error that it can't convert CHAR to BIGINT. We are querying a postgresDB at backend.

For example click on one of these IDs.
![圖片](https://user-images.githubusercontent.com/1003146/93174756-17b75280-f761-11ea-90e1-56931c31e392.png)
It shows DB error from our backend postgresDB.
![圖片](https://user-images.githubusercontent.com/1003146/93174785-2867c880-f761-11ea-9fa5-f89c33744fbd.png)

**Comment by flamber** [comment]
@tw0517tw I have created an issue for it - #13249 - upvote by clicking :+1: on the first post

**Comment by udisun** [comment]
> Fixed by #13107

on version 0.36.7
dashboard filters and query filters rounds the long number on paste, no way to change it.
drill down on long numbers work.
so I guess the issue is still ongoing
:(

**Comment by flamber** [comment]
@udisun Yes, this issue has been re-opened instead of creating a handful of issues.

**Comment by tw0517tw** [comment]
I found that when using "Native Query" in asking question, the big-int column is still rounded in `v0.37.0.1`.
![圖片](https://user-images.githubusercontent.com/1003146/97114678-e69d4b00-172c-11eb-8d2c-1d9603989335.png)

**Comment by flamber** [comment]
@tw0517tw Yes, this issue is not fixed. PR #13107 only addressed PK/FK via QB.

**Comment by udisun** [comment]
any update? this is a really urgent critical issue
should be the top priority imo

**Comment by camsaul** [comment]
I think addressing this will require some refactoring in a few places -- maybe parsing long number sequences as `Decimal` (?) on the frontend and updating a lot of code to handle that. This probably would need to go in a major release rather than a patch release

**Comment by udisun** [comment]
Any solution to this?
in previous versions we could paste the big number filter in the browser url and that worked.
now even that doesn't work.
all big numbers are rounded.

**Comment by paoliniluis** [comment]
> I think addressing this will require some refactoring in a few places -- maybe parsing long number sequences as `Decimal` (?) on the frontend and updating a lot of code to handle that. This probably would need to go in a major release rather than a patch release

I think we'll have to go for a good n' old string in the frontend

**Comment by paoliniluis** [comment]
Lifting the priority on this one as a customer is hitting the issue

**Comment by cyhhao** [comment]
2023 is almost over, why has this problem not been solved yet? Are there any alternatives?

**Comment by thibauds** [comment]
@cyhhao You can contribute and fix this if you want to contribute to this great project.

**Comment by tritatuy** [comment]
Issue is still actual in March 2024.
Metabase 0.47.0 -> ClickHouse (ver. 23.8.9.54)

**Comment by cyhhao** [comment]
Guys, how is the progress of fixing this bug?

**Comment by Enderyu** [comment]
When is the problem expected to be resolved? It makes our work very difficult

**Comment by rgsthethird** [comment]
I'm experiencing this issue when working with [Discord Snowflakes](https://github.com/metabase/metabase/issues/5816). Just bumping to share another use case and continued desire to have this resolved

**Comment by paoliniluis** [comment]
@rgsthethird please tell us what you mean when you say "discord snowflakes"
