### ISSUE TITLE
Failed to upgrade to v0.27.0

### ISSUE THREAD

**Issue by thucnc** [metabase/metabase#6494]
I got below error when upgrading metabase docker from v0.26.0 to v0.27.0 

![screen shot 2017-11-29 at 7 54 01 am](https://user-images.githubusercontent.com/2088055/33352395-39ab4cee-d4db-11e7-9f90-4261da70249f.png)

**Comment by camsaul** [comment]
@senior it sounds like we should tweak `populate-card-database-id` migration from 0.26.1 to make sure we don't set `database_id` for Cards that have the nested query pseudo-database ID :sweat: Ick

@thucnc as a workaround you can just insert a row in the Data migrations table so Metabase thinks it's already been ran which will let you start normally:

```sql
INSERT INTO data_migrations (id, timestamp) VALUES
  ('populate-card-database-id', current_timestamp);
```

If you're using H2 I think you need to do `current_timestamp()` instead of `current_timestamp`

**Comment by kapsule** [comment]
Hi, I just upgraded from v0.26.2 to 0.27 and the same thing happens to me. Thanks.

If you need additional information I can send it.

**Comment by senior** [comment]
I've got a fix for this in #6498. It looks like this issue can happen if you have a native query as a saved question, then construct another question against that saved native query question.

**Comment by doodlebro** [comment]
This is an exceptionally poor release. When can we expect a hotfix to be released?

**Comment by salsakran** [comment]
That's a touch harsh @doodlebro. What kind of response were you hoping for from that comment?

**Comment by doodlebro** [comment]
When can we expect a hotfix to be released?
Probably can start by answering this^

Also, this is the second update that has had significant issues since I've started using Metabase (since May). I'm making a comment on this since it won't fly in the future.

**Comment by salsakran** [comment]
Your tone is out of place and hostile. You might find that people will be more helpful and forthcoming if you use a friendlier tone around here.

**Comment by doodlebro** [comment]
Commenting on a poor release is hardly hostile. Release better software.

Since you still have not answered...

>When can we expect a hotfix to be released?

>When can we expect a hotfix to be released?

>When can we expect a hotfix to be released?

**Comment by camsaul** [comment]
Fixed by #6498

**Comment by camsaul** [comment]
@thucnc @kapsule we've released a hotfix release, 0.27.1, which fixes this issue. You can download it here: https://www.metabase.com/start/

**Comment by doodlebro** [comment]
Good job guys.

**Comment by doodlebro** [comment]
Except it's not in the docker registry... @camsaul @salsakran @mazameli ...?

**Comment by mazameli** [comment]
Docker registry is updated now: https://hub.docker.com/r/metabase/metabase/tags/

Thanks for bringing that to our attention.

**Comment by sailxjx** [comment]
When I upgrade metabase from 0.26.1 to 0.27.1, this error still occurred.

```
org.postgresql.util.PSQLException: ERROR: insert or update on table "report_card" violates foreign key constraint "fk_report_card_ref_database_id"
Detail: Key (database_id)=(2) is not present in table "metabase_database".
```

**Comment by senior** [comment]
@sailxjx Interesting, it looks like you've got a question that references a database that doesn't exist. Could you open a separate issue for this issue along with any other logging you've got around it?

**Comment by chanthus** [comment]
I get a similar error when upgrading from 0.26.1 to 0.27.1 as well.

```03/12/2017 20:51:1312-03 09:51:13 INFO metabase.util :: Loading Metabase...
03/12/2017 20:51:2612-03 09:51:26 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
03/12/2017 20:51:26See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
03/12/2017 20:51:4012-03 09:51:40 INFO metabase.core :: Starting Metabase in STANDALONE mode
03/12/2017 20:51:4012-03 09:51:40 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
03/12/2017 20:51:40 {:port 3000, :host "0.0.0.0"}
03/12/2017 20:51:40
03/12/2017 20:51:4012-03 09:51:40 INFO metabase.core :: Starting Metabase version v0.27.1 (055e448 release-0.27.0) ...
03/12/2017 20:51:4012-03 09:51:40 INFO metabase.core :: System timezone is 'GMT' ...
03/12/2017 20:51:4312-03 09:51:43 WARN metabase.driver :: No -init-driver function found for 'metabase.driver.google'
03/12/2017 20:51:4312-03 09:51:43 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
03/12/2017 20:51:4312-03 09:51:43 INFO metabase.db :: Verifying postgres Database Connection ...
03/12/2017 20:51:4412-03 09:51:44 INFO metabase.db :: Verify Database Connection ...  ✅
03/12/2017 20:51:4412-03 09:51:44 INFO metabase.db :: Running Database Migrations...
03/12/2017 20:51:4412-03 09:51:44 INFO metabase.db :: Setting up Liquibase...
03/12/2017 20:51:4412-03 09:51:44 INFO metabase.db :: Liquibase is ready.
03/12/2017 20:51:4412-03 09:51:44 INFO metabase.db :: Checking if Database has unrun migrations...
03/12/2017 20:51:5012-03 09:51:50 INFO metabase.db :: Database Migrations Current ...  ✅
03/12/2017 20:51:50com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
03/12/2017 20:51:5012-03 09:51:50 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
03/12/2017 20:51:5012-03 09:51:50 INFO db.migrations :: Running data migration 'populate-card-database-id'...
03/12/2017 20:51:50org.postgresql.util.PSQLException: ERROR: insert or update on table "report_card" violates foreign key constraint "fk_report_card_ref_database_id"
03/12/2017 20:51:50  Detail: Key (database_id)=(6) is not present in table "metabase_database".
03/12/2017 20:51:50	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
03/12/2017 20:51:50	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
03/12/2017 20:51:50	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
03/12/2017 20:51:50	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
03/12/2017 20:51:50	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
03/12/2017 20:51:50	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
03/12/2017 20:51:50	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
03/12/2017 20:51:50	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
03/12/2017 20:51:50	at clojure.java.jdbc$db_do_execute_prepared_statement$fn__10886.invoke(jdbc.clj:901)
03/12/2017 20:51:50	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:714)
03/12/2017 20:51:50	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
03/12/2017 20:51:50	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:697)
03/12/2017 20:51:50	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
03/12/2017 20:51:50	at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:900)
03/12/2017 20:51:50	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:894)
03/12/2017 20:51:50	at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:932)
03/12/2017 20:51:50	at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:912)
03/12/2017 20:51:50	at clojure.java.jdbc$execute_BANG_$execute_helper__10945.invoke(jdbc.clj:1161)
03/12/2017 20:51:50	at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1165)
03/12/2017 20:51:50	at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1145)
03/12/2017 20:51:50	at toucan.db$execute_BANG_.invokeStatic(db.clj:324)
03/12/2017 20:51:50	at toucan.db$execute_BANG_.doInvoke(db.clj:319)
03/12/2017 20:51:50	at clojure.lang.RestFn.invoke(RestFn.java:410)
03/12/2017 20:51:50	at toucan.db$update_BANG_.invokeStatic(db.clj:378)
03/12/2017 20:51:50	at toucan.db$update_BANG_.invoke(db.clj:367)
03/12/2017 20:51:50	at toucan.db$update_where_BANG_.invokeStatic(db.clj:402)
03/12/2017 20:51:50	at toucan.db$update_where_BANG_.doInvoke(db.clj:392)
03/12/2017 20:51:50	at clojure.lang.RestFn.invoke(RestFn.java:464)
03/12/2017 20:51:50	at metabase.db.migrations$populate_card_database_id.invokeStatic(migrations.clj:336)
03/12/2017 20:51:50	at metabase.db.migrations$populate_card_database_id.invoke(migrations.clj:332)
03/12/2017 20:51:50	at metabase.db.migrations$run_migration_if_needed_BANG_.invokeStatic(migrations.clj:49)
03/12/2017 20:51:50	at metabase.db.migrations$run_migration_if_needed_BANG_.invoke(migrations.clj:40)
03/12/2017 20:51:50	at metabase.db.migrations$run_all_BANG_.invokeStatic(migrations.clj:68)
03/12/2017 20:51:50	at metabase.db.migrations$run_all_BANG_.invoke(migrations.clj:62)
03/12/2017 20:51:50	at clojure.lang.Var.invoke(Var.java:375)
03/12/2017 20:51:50	at metabase.db$run_data_migrations_BANG_.invokeStatic(db.clj:374)
03/12/2017 20:51:50	at metabase.db$run_data_migrations_BANG_.invoke(db.clj:369)
03/12/2017 20:51:50	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:385)
03/12/2017 20:51:50	at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
03/12/2017 20:51:50	at clojure.lang.RestFn.invoke(RestFn.java:421)
03/12/2017 20:51:50	at metabase.core$init_BANG_.invokeStatic(core.clj:108)
03/12/2017 20:51:50	at metabase.core$init_BANG_.invoke(core.clj:87)
03/12/2017 20:51:50	at metabase.core$start_normally.invokeStatic(core.clj:194)
03/12/2017 20:51:50	at metabase.core$start_normally.invoke(core.clj:188)
03/12/2017 20:51:50	at metabase.core$_main.invokeStatic(core.clj:292)
03/12/2017 20:51:50	at metabase.core$_main.doInvoke(core.clj:287)
03/12/2017 20:51:50	at clojure.lang.RestFn.invoke(RestFn.java:397)
03/12/2017 20:51:50	at clojure.lang.AFn.applyToHelper(AFn.java:152)
03/12/2017 20:51:50	at clojure.lang.RestFn.applyTo(RestFn.java:132)
03/12/2017 20:51:50	at metabase.core.main(Unknown Source)
03/12/2017 20:51:5012-03 09:51:50 ERROR metabase.core :: Metabase Initialization FAILED:  ERROR: insert or update on table "report_card" violates foreign key constraint "fk_report_card_ref_database_id"
03/12/2017 20:51:50  Detail: Key (database_id)=(6) is not present in table "metabase_database".
03/12/2017 20:51:5012-03 09:51:50 INFO metabase.core :: Metabase Shutting Down ...
03/12/2017 20:51:5012-03 09:51:50 INFO metabase.core :: Metabase Shutdown COMPLETE```

**Comment by ston3o** [comment]
I have a similar error when I upgrading from v0.26.2 to v0.27.1

```
12-09 09:44:01 INFO metabase.util :: Loading Metabase...
12-09 09:44:10 INFO util.encryption :: DB details encryption is DISABLED for this Metabase instance. 🔓
See http://www.metabase.com/docs/latest/operations-guide/start.html#encrypting-your-database-connection-details-at-rest for more information.
12-09 09:44:19 INFO metabase.core :: Starting Metabase in STANDALONE mode
12-09 09:44:19 INFO metabase.core :: Launching Embedded Jetty Webserver with config:
 {:port 3000, :host "0.0.0.0"}

12-09 09:44:19 INFO metabase.core :: Starting Metabase version v0.27.1 (055e448 release-0.27.0) ...
12-09 09:44:19 INFO metabase.core :: System timezone is 'GMT' ...
12-09 09:44:21 WARN metabase.driver :: No -init-driver function found for 'metabase.driver.google'
12-09 09:44:22 INFO metabase.core :: Setting up and migrating Metabase DB. Please sit tight, this may take a minute...
12-09 09:44:22 INFO metabase.db :: Verifying h2 Database Connection ...
12-09 09:44:26 INFO metabase.db :: Verify Database Connection ...  ✅
12-09 09:44:26 INFO metabase.db :: Running Database Migrations...
12-09 09:44:26 INFO metabase.db :: Setting up Liquibase...
12-09 09:44:26 INFO metabase.db :: Liquibase is ready.
12-09 09:44:26 INFO metabase.db :: Checking if Database has unrun migrations...
12-09 09:44:34 INFO metabase.db :: Database Migrations Current ...  ✅
com.mchange.v2.cfg.DelayedLogItem [ level -> FINE, text -> "The configuration file for resource identifier 'hocon:/reference,/application,/c3p0,/' could not be found. Skipping.", exception -> null]
12-09 09:44:34 INFO db.migrations :: Running all necessary data migrations, this may take a minute.
12-09 09:44:34 INFO db.migrations :: Running data migration 'populate-card-database-id'...
org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "FK_REPORT_CARD_REF_DATABASE_ID: PUBLIC.REPORT_CARD FOREIGN KEY(DATABASE_ID) REFERENCES PUBLIC.METABASE_DATABASE(ID) (9)"; SQL statement:
UPDATE "REPORT_CARD" SET "DATABASE_ID" = 9 WHERE ("ID" in (2, 4, 3, 5)) [23506-194]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.constraint.ConstraintReferential.checkRowOwnTable(ConstraintReferential.java:371)
        at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:313)
        at org.h2.table.Table.fireConstraints(Table.java:976)
        at org.h2.table.Table.fireAfterRow(Table.java:994)
        at org.h2.command.dml.Update.update(Update.java:151)
        at org.h2.command.CommandContainer.update(CommandContainer.java:101)
        at org.h2.command.Command.executeUpdate(Command.java:258)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:160)
        at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:146)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
        at clojure.java.jdbc$db_do_execute_prepared_statement$fn__10886.invoke(jdbc.clj:901)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:714)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:697)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:684)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invokeStatic(jdbc.clj:900)
        at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:894)
        at clojure.java.jdbc$db_do_prepared.invokeStatic(jdbc.clj:932)
        at clojure.java.jdbc$db_do_prepared.invoke(jdbc.clj:912)
        at clojure.java.jdbc$execute_BANG_$execute_helper__10945.invoke(jdbc.clj:1161)
        at clojure.java.jdbc$execute_BANG_.invokeStatic(jdbc.clj:1165)
        at clojure.java.jdbc$execute_BANG_.invoke(jdbc.clj:1145)
        at toucan.db$execute_BANG_.invokeStatic(db.clj:324)
        at toucan.db$execute_BANG_.doInvoke(db.clj:319)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at toucan.db$update_BANG_.invokeStatic(db.clj:378)
        at toucan.db$update_BANG_.invoke(db.clj:367)
        at toucan.db$update_where_BANG_.invokeStatic(db.clj:402)
        at toucan.db$update_where_BANG_.doInvoke(db.clj:392)
        at clojure.lang.RestFn.invoke(RestFn.java:464)
        at metabase.db.migrations$populate_card_database_id.invokeStatic(migrations.clj:336)
        at metabase.db.migrations$populate_card_database_id.invoke(migrations.clj:332)
        at metabase.db.migrations$run_migration_if_needed_BANG_.invokeStatic(migrations.clj:49)
        at metabase.db.migrations$run_migration_if_needed_BANG_.invoke(migrations.clj:40)
        at metabase.db.migrations$run_all_BANG_.invokeStatic(migrations.clj:68)
        at metabase.db.migrations$run_all_BANG_.invoke(migrations.clj:62)
        at clojure.lang.Var.invoke(Var.java:375)
        at metabase.db$run_data_migrations_BANG_.invokeStatic(db.clj:374)
12-09 09:44:34 ERROR metabase.core :: Metabase Initialization FAILED:  Referential integrity constraint violation: "FK_REPORT_CARD_REF_DATABASE_ID: PUBLIC.REPORT_CARD FOREIGN KEY(DATABASE_ID) REFERENCES PUBLIC.METABASE_DATABASE(ID) (9)"; SQL statement:
UPDATE "REPORT_CARD" SET "DATABASE_ID" = 9 WHERE ("ID" in (2, 4, 3, 5)) [23506-194]
        at metabase.db$run_data_migrations_BANG_.invoke(db.clj:369)
        at metabase.db$setup_db_BANG_.invokeStatic(db.clj:385)
        at metabase.db$setup_db_BANG_.doInvoke(db.clj:376)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at metabase.core$init_BANG_.invokeStatic(core.clj:108)
        at metabase.core$init_BANG_.invoke(core.clj:87)
        at metabase.core$start_normally.invokeStatic(core.clj:194)
        at metabase.core$start_normally.invoke(core.clj:188)
        at metabase.core$_main.invokeStatic(core.clj:292)
        at metabase.core$_main.doInvoke(core.clj:287)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at metabase.core.main(Unknown Source)
12-09 09:44:34 INFO metabase.core :: Metabase Shutting Down ...
12-09 09:44:34 INFO metabase.core :: Metabase Shutdown COMPLETE
```

**Comment by jacopoch** [comment]
According to https://github.com/ocf/metabase/commit/72ed2eaacd91c95a63f75c06a5c26abbadcf8006 this release (as well as 0.27.0) seems to be broken in Postgres as well, could the two docker images be pulled from the repo to prevent others getting stuck into this problem?

Thanks!

**Comment by robsonpeixoto** [comment]
The same problem here after upgrade from `metabase/metabase:v0.26.1` to `metabase/metabase:v0.27.1`

**Comment by pavneetskapoor** [comment]
Still having an issue with this after trying to export Metabase config database on prod to localhost (PostgreSQL) and running jar file on version `0.27`. Any ideas @camsaul ?
