### ISSUE TITLE
PDF Exports of Gauge Chart Contain Oversized Text (Chrome) 

### ISSUE THREAD

**Issue by ixipixi** [metabase/metabase#65322]
### Describe the bug

If you export a dashboard to PDF in the dashboard contains a gauge chart the resulting PDF doesn't render the gauge correctly.

### To Reproduce

1. Create a Gauge Chart
2. Export to PDF in Chrome (see large text and cut off upper section)
3. Export in Firefox (see empty box with ellipses in place of viz) - Resolved

Firefox (now resolved):
https://www.loom.com/share/23641b199b2b407a8bfff59208e5474c

Chrome (still an issue):
https://www.loom.com/share/15823eba21e84c699d0c422c74070ed3

### Expected behavior

The gauge chart should be exported and the text and labels of the chart should be of a size that's relative to the viz itself.

### Information about your Metabase installation

```JSON
56.12 & 57.5.4
```

### Severity

Very bad for firefox users; pretty annoying for everyone else

**Comment by thegeekybaniya** [comment]
Hi, I am new here wanted to contribute

please review https://github.com/metabase/metabase/pull/65917

**Comment by thegeekybaniya** [comment]
@ixipixi on the Firefox issue, that is happening due to [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/CSP).

Firefox has a higher overall standard for security and some features are blocked.

[firefox-security.patch](https://github.com/user-attachments/files/23610375/firefox-security.patch)

if you apply the above patch using

`git apply firefox-security.patch`

It will start working for firefox, I am still reviewing if this change can be used for beyond local dev. I will raise a PR if that works.


can you get my PR https://github.com/metabase/metabase/pull/65917 reviewed, Chrome PDF export is fixed here.

**Comment by eliotmetabase** [comment]
@thegeekybaniya thanks for your contribution.
We recently fixed a similar bug here: https://github.com/metabase/metabase/pull/66337
Can you check if you're still able to reproduce the issue with this fix?

**Comment by thegeekybaniya** [comment]
Will check, had a busy week.

**Comment by ixipixi** [comment]
@eliotmetabase Firefox issue seems to be resolved. The oversized text being cut off in Chrome is not resolved, however. I'll update the issue.

**Comment by anthonysfancher** [comment]
why is this closed when it is still an open bug
