### ISSUE TITLE
CSV & XLSX downloads return internal server error

### ISSUE THREAD

**Issue by milgner** [metabase/metabase#6901]
Browser: Firefox 58, 60, Linux (colleague also tried current Chrome on MacOS)
Database: PostgreSQL 9.6 (internal and external)
Metabase: 0.28.0, hosted on Elastic Beanstalk

- navigate to saved question (not all questions are affected, unable to identify any commonalities so far
- click "download" and choose either "CSV" or "XLSX"

Expected behaviour: query results are downloaded in the requested format.

Actual behaviour: error stacktrace (see below)

Trying to download data in JSON format, returns status code 200 but an empty file.

```json
{"message":null,"stacktrace":["api.dataset$datetime_str__GT_date.invokeStatic(dataset.clj:85)","api.dataset$datetime_str__GT_date.invoke(dataset.clj:81)","api.dataset$swap_date_columns$fn__33299$fn__33300.invoke(dataset.clj:90)","api.dataset$swap_date_columns$fn__33299.invoke(dataset.clj:89)","util.export$export_to_csv.invokeStatic(export.clj:45)","util.export$export_to_csv.invoke(export.clj:42)","api.dataset$as_format.invokeStatic(dataset.clj:115)","api.dataset$as_format.invoke(dataset.clj:107)","api.card$fn__33710$fn__33711$fn__33712.invoke(card.clj:623)","api.card$fn__33710$fn__33711.invoke(card.clj:622)","api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:253)","api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:248)","api.card$fn__33710.invokeStatic(card.clj:616)","api.card$fn__33710.invoke(card.clj:616)","middleware$enforce_authentication$fn__33151.invoke(middleware.clj:123)","api.routes$fn__46089.invokeStatic(routes.clj:62)","api.routes$fn__46089.invoke(routes.clj:62)","routes$fn__46855$fn__46856.doInvoke(routes.clj:106)","routes$fn__46855.invokeStatic(routes.clj:101)","routes$fn__46855.invoke(routes.clj:101)","middleware$log_api_call$fn__33250$fn__33252.invoke(middleware.clj:342)","middleware$log_api_call$fn__33250.invoke(middleware.clj:341)","middleware$add_security_headers$fn__33200.invoke(middleware.clj:255)","core$wrap_streamed_json_response$fn__47650.invoke(core.clj:66)","middleware$bind_current_user$fn__33155.invoke(middleware.clj:144)","middleware$maybe_set_site_url$fn__33204.invoke(middleware.clj:279)"]}
```

**Comment by ifulfilment** [comment]
I am also having issues now that we have updated to 0.28.

When exporting CSV or XLSX we are getting a file with just the header row results and no real data. The table within the Metabase app, however, shows the table with data in as normal.

**Comment by ifulfilment** [comment]
Upon further investigation, the issue only seems to happen when multiple values are selected from a drop-down filter. 

For example: If I choose **status** is '_open_' it exports fine. If i choose **status** in '_open_' or '_closed_' it breaks

**Comment by senior** [comment]
@milgner @ifulfilment Do the logs include the full stacktrace? It looks like there's some issue in converting the dates used in the export.

**Comment by drewblas** [comment]
We're experiencing the same error.  Here's a full stacktrace from the logs:

```
02-08 20:23:05 ERROR metabase.middleware :: POST /api/dataset/csv 500 (472 ms) (18 DB calls)
{:message nil,
 :stacktrace
 ["api.dataset$datetime_str__GT_date.invokeStatic(dataset.clj:85)"
  "api.dataset$datetime_str__GT_date.invoke(dataset.clj:81)"
  "api.dataset$swap_date_columns$fn__33299$fn__33300.invoke(dataset.clj:90)"
  "api.dataset$swap_date_columns$fn__33299.invoke(dataset.clj:89)"
  "util.export$export_to_csv.invokeStatic(export.clj:45)"
  "util.export$export_to_csv.invoke(export.clj:42)"
  "api.dataset$as_format.invokeStatic(dataset.clj:115)"
  "api.dataset$as_format.invoke(dataset.clj:107)"
  "api.dataset$fn__33317$fn__33318.invoke(dataset.clj:136)"
  "api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:248)"
  "api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:253)"
  "api.dataset$fn__33317.invokeStatic(dataset.clj:129)"
  "api.dataset$fn__33317.invoke(dataset.clj:129)"
  "middleware$enforce_authentication$fn__33151.invoke(middleware.clj:123)"
  "api.routes$fn__46097.invokeStatic(routes.clj:66)"
  "api.routes$fn__46097.invoke(routes.clj:66)"
  "routes$fn__46855$fn__46856.doInvoke(routes.clj:106)"
  "routes$fn__46855.invokeStatic(routes.clj:101)"
  "routes$fn__46855.invoke(routes.clj:101)"
  "middleware$log_api_call$fn__33250$fn__33252.invoke(middleware.clj:342)"
  "middleware$log_api_call$fn__33250.invoke(middleware.clj:341)"
  "middleware$add_security_headers$fn__33200.invoke(middleware.clj:255)"
  "core$wrap_streamed_json_response$fn__47650.invoke(core.clj:66)"
  "middleware$bind_current_user$fn__33155.invoke(middleware.clj:144)"
  "middleware$maybe_set_site_url$fn__33204.invoke(middleware.clj:279)"]}
```

**Comment by salsakran** [comment]
fixed via #6909 and going out in a few moments in 0.28.1

**Comment by nskalis** [comment]
Hi, thanks for the quick reaction on this one. But I am getting:
```
{"message":"String index out of range: -1","type":"class java.lang.StringIndexOutOfBoundsException","stacktrace":["api.dataset$datetime_str__GT_date.invokeStatic(dataset.clj:86)","api.dataset$datetime_str__GT_date.invoke(dataset.clj:81)","api.dataset$swap_date_columns$fn__33300$fn__33301.invoke(dataset.clj:91)","api.dataset$swap_date_columns$fn__33300.invoke(dataset.clj:90)","util.export$export_to_csv.invokeStatic(export.clj:45)","util.export$export_to_csv.invoke(export.clj:42)","api.dataset$as_format.invokeStatic(dataset.clj:116)","api.dataset$as_format.invoke(dataset.clj:108)","api.card$fn__33711$fn__33712$fn__33713.invoke(card.clj:623)","api.card$fn__33711$fn__33712.invoke(card.clj:622)","api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)","api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)","api.card$fn__33711.invokeStatic(card.clj:616)","api.card$fn__33711.invoke(card.clj:616)","middleware$enforce_authentication$fn__33152.invoke(middleware.clj:123)","api.routes$fn__46090.invokeStatic(routes.clj:62)","api.routes$fn__46090.invoke(routes.clj:62)","routes$fn__46856$fn__46857.doInvoke(routes.clj:106)","routes$fn__46856.invokeStatic(routes.clj:101)","routes$fn__46856.invoke(routes.clj:101)","middleware$log_api_call$fn__33251$fn__33253.invoke(middleware.clj:342)","middleware$log_api_call$fn__33251.invoke(middleware.clj:341)","middleware$add_security_headers$fn__33201.invoke(middleware.clj:255)","core$wrap_streamed_json_response$fn__47651.invoke(core.clj:66)","middleware$bind_current_user$fn__33156.invoke(middleware.clj:144)","middleware$maybe_set_site_url$fn__33205.invoke(middleware.clj:279)"]}
```
while `json` dump is empty. could you peal advise ?

**Comment by senior** [comment]
@nskalis Could you open up a separate issue for this? You have a date flowing out of Metabase that is not formatted as it should be. Be sure to include which database the data is coming from and some of that JSON export would be helpful as well.

**Comment by nskalis** [comment]
@senior thanks! I just created #6944

**Comment by sunny-t** [comment]
Seems like this is still an issue, I can export large datasets on 27.2 with no issues. However since I upgraded to 28.1 it throws errors.

**Comment by senior** [comment]
@sunny-t Can you include what error message(s) you're seeing?

**Comment by sunny-t** [comment]
I reverted to 27.2 and can download the xls with no issues, however 28.1 throws this error:

```
{"message":"java.lang.Integer cannot be cast to java.lang.String","type":"class java.lang.ClassCastException","stacktrace":["api.dataset$datetime_str__GT_date.invokeStatic(dataset.clj:86)","api.dataset$datetime_str__GT_date.invoke(dataset.clj:81)","api.dataset$swap_date_columns$fn__33300$fn__33301.invoke(dataset.clj:91)","api.dataset$swap_date_columns$fn__33300.invoke(dataset.clj:90)","util.export$export_to_xlsx.invokeStatic(export.clj:28)","util.export$export_to_xlsx.invoke(export.clj:27)","api.dataset$as_format.invokeStatic(dataset.clj:116)","api.dataset$as_format.invoke(dataset.clj:108)","api.dataset$fn__33318$fn__33319.invoke(dataset.clj:137)","api.common.internal$do_with_caught_api_exceptions.invokeStatic(internal.clj:254)","api.common.internal$do_with_caught_api_exceptions.invoke(internal.clj:249)","api.dataset$fn__33318.invokeStatic(dataset.clj:130)","api.dataset$fn__33318.invoke(dataset.clj:130)","middleware$enforce_authentication$fn__33152.invoke(middleware.clj:123)","api.routes$fn__46098.invokeStatic(routes.clj:66)","api.routes$fn__46098.invoke(routes.clj:66)","routes$fn__46856$fn__46857.doInvoke(routes.clj:106)","routes$fn__46856.invokeStatic(routes.clj:101)","routes$fn__46856.invoke(routes.clj:101)","middleware$log_api_call$fn__33251$fn__33253.invoke(middleware.clj:342)","middleware$log_api_call$fn__33251.invoke(middleware.clj:341)","middleware$add_security_headers$fn__33201.invoke(middleware.clj:255)","core$wrap_streamed_json_response$fn__47651.invoke(core.clj:66)","middleware$bind_current_user$fn__33156.invoke(middleware.clj:144)","middleware$maybe_set_site_url$fn__33205.invoke(middleware.clj:279)"]}
```

**Comment by senior** [comment]
@sunny-t The error you getting is a pretty easy fix, but I don't know how the scenario you have is possible. Somehow you have a Date column that has integer values. We support unix timestamps that are integers, but their special type is a DateTime and their base type is an integer.

I'd like to try and get a unit test together that reproduces your issue, can you include which database you're querying and the schema for that table?

**Comment by sunny-t** [comment]
The date field uses a "date_key" which is an integer in the format yyyymmdd e.g. 20180131. This is why it does not appear to be a timestamp. 

As I mentioned the xls generation works fine in 27.2.

**Comment by senior** [comment]
@sunny-t I agree that what you are seeing is a bug (and I just merged the fix here https://github.com/metabase/metabase/pull/6956). It will be released with version 0.28.2. It was broken because I didn't know it was possible to have column with a database type that was a date, but the value was an integer.

I'd like to create a test for this so that I don't break it again in the future. I'm not familiar with the term `date_key`, is that the type specified for your date column in the schema? It would also help to know which database you using so that I can use that same database in my test.

**Comment by sunny-t** [comment]
@senior Thanks for the clarification. The database is using postgresql; as for the date_key it is simply an integer which is extracted from the timestamp.
