### ISSUE TITLE
Pulses not showing figures - metabase.pulse.render.NumericWrapper

### ISSUE THREAD

**Issue by TheCondorman** [metabase/metabase#7210]
I've just updated to version 0.28.3 and Pulses seem to be broken:
![image](https://user-images.githubusercontent.com/6168847/37963925-aeda9324-31b7-11e8-8ef5-f40f4fea5a4a.png)

Viewed in Outlook and Outlook web (Office 365)
Your operating system: Win 10
Your databases: MySQL 5.7.19
Metabase version: 0.28.3
Metabase hosting environment: Win10 Powershell jar
Metabase internal database: H2 (default)

**Comment by JoeSham** [comment]
We also have some problems with pulses since the upgrade. They often don't get sent as scheduled. But when manually sending them, they work.

But we have been having multiple other issues since the upgrade, most notably the java process running out of memory quite often (with -Xms and -Xmx set to more than 6 GB and even more GB available to the container), causing Metabase docker container restart, so it might be connected.

**Comment by thedavidprice** [comment]
Same issue for me with pulses. Started with 28.2, continued on 28.3 and now 28.4.

Will continue an attempt to diagnose but no idea as of yet.

**Comment by senior** [comment]
I fixed this bug in a few other places, must have missed this one. Thanks for reporting this!

**Comment by thedavidprice** [comment]
@senior greatly appreciate it!

**Comment by brnt** [comment]
Sounds like you've got a handle on it @senior, so I won't pile on to the report.

Can we make sure this gets pushed into the heroku binary branch once the issue is resolved?

**Comment by valtlfelipe** [comment]
This is still present in `0.28.5`.

![captura de tela 2018-04-05 as 10 05 33](https://user-images.githubusercontent.com/3065339/38367400-ec36d572-38b8-11e8-848d-2aaf38e15351.png)

**Comment by senior** [comment]
Sorry for misleading everyone on this issue, but it's already been fixed, I just didn't realize that the fix was in master, not the 0.28.x release branches. The fix was merged into master quite a while ago (early March) https://github.com/metabase/metabase/pull/7074. It will be included with 0.29.0 which should be soon.

I spent all morning trying to reproduce this issue on master and couldn't, which is good news as it validated the fix, just waiting for a release now.

**Comment by camsaul** [comment]
Fixed by #7074

**Comment by salsakran** [comment]
Heads up @TheCondorman @thedavidprice @JoeSham and @brnt , this is embarrassing enough that we kicked out an 0.28.6 to fix it while we do final testing + tweaking on 0.29. Sorry for the mess!

**Comment by bishwo633** [comment]
This is occurring again on v0.32.9. I pulled a docker image of metabase "docker pull metabase/metabase:v0.32.9", configured postgresql database data source, then setup pulse to send an email to exchange mail.

Output (outlook email):
![image](https://user-images.githubusercontent.com/3096411/60793275-14046500-a187-11e9-8239-b6b0b7066a4c.png)

Output (web browser):
![image](https://user-images.githubusercontent.com/3096411/60793280-1797ec00-a187-11e9-99c1-927c99ba5b26.png)

**Comment by flamber** [comment]
@bishwo633 I think you're seeing issue #6874
