### ISSUE TITLE
Binning not working in some situations like when there are null values

### ISSUE THREAD

**Issue by tuaris** [metabase/metabase#7782]
### Bugs
If you're filing an issue about a bug please include as much information
as you can including the following.

- Your databases: MySQL
- Metabase version: 0.29.3
- Metabase hosting environment: Linux/Debian
- Metabase internal database:  MySQL

How do I 'bin' results into ranges?  For example a row with column A that falls between 0 AND 3600 and another for 3601 to 7200, and finally one for those above 7200

:arrow_down: Please click the :+1: reaction instead of leaving a `+1` or `update?` comment

**Comment by mazameli** [comment]
If column A in your example is marked as a number or latitude/longitude in the data model, Metabase should bin that for you automatically. You can also select between 10, 50, or 100 bins if the auto binning isn't what you're looking for. Customs bins haven't been implemented yet. 

Example:

![screen shot 2018-06-01 at 11 43 09 am](https://user-images.githubusercontent.com/2223916/40857770-00bdd1e4-6591-11e8-8821-a4d3b185d972.png)

**Comment by mausch** [comment]
I can't get binning options (or automatic binning) for my latitude/longitude columns.
When I try to use the grid map visualisation I get an error "grid map requires binned longitude/latitude" but I can't seem to find how to do it. Are there any special column type requirements or something? (Postgres)

**Comment by mazameli** [comment]
@mausch If you go to the Data Model section of the Admin Panel, can you verify that your latitude and longitude columns are marked as Latitude and Longitude, like this?

![lat-long](https://user-images.githubusercontent.com/2223916/40929654-49418276-67da-11e8-8ada-bde093d70049.png)

**Comment by tuaris** [comment]
Thank you for the explanation.   Is this something that's hard to add in?  For now, I can use a custom query or MySQL views to do some manual binning, but it's very complex and ugly.  

With the custom query approach I'm having some difficulty adding in a variable to support a date filter that will at the same time support the ability to specify a specific range and use the fancy stuff like "last 30 days".

I'm not sure how to achieve that or if it's even possible.

**Comment by salsakran** [comment]
@tuaris as @mazameli mentioned, it should work out of the box. Can you share the schema for a table where you don't see the option on a numeric column like this example from the sample dataset -
<img width="518" alt="screen shot 2018-07-05 at 9 31 45 pm" src="https://user-images.githubusercontent.com/107439/42360018-e0d22d9c-809a-11e8-8762-9f9969c609ef.png">

**Comment by liransmartlighthouse** [comment]
Hey,

I'm seeing the same issue as mentioned (number not showing auto bin option) for field = Age. 

BigQuery schema:
![image](https://user-images.githubusercontent.com/42851040/44938298-0d79b580-ad4c-11e8-8fbd-e6046a54ab63.png)

Can confirm the my field Age is Type=Number in the Metabase model.

The weird thing is...
Auto bins is working in another chart for field for field Treatment_Length, also a Number in the Metabase model.

![image](https://user-images.githubusercontent.com/42851040/44938271-e3c08e80-ad4b-11e8-95ba-db2606da6efd.png)

Both are integers in the schema, both are numbers in the Metabase model. 

**Attempts to fix:**
- I've tried changing it to Lat/Long as well as text field, then discarding cached values, then rescanning the table without luck.
- Also tried loading via Chrome Incognito and rarely ever used Firefox

Your databases: BigQuery
Metabase version: 0.30.1
Metabase hosting environment: Google Cloud/Kubernetes
Metabase internal database: MySQL

**Comment by leorochael** [comment]
I'm also experiencing this problem on a table colum that is classified as Number but for a long time (days) only contained null values.

Now that the column has many values varying from 0 and 0.0001 all the way to 678,981.97, the binning options don't show up...

The DB is Postgres (10), the `original schema` shows the column to be `type/Float` and the type in metabase is set to Number.

I've tried setting the type to different things and back to `Number` or `Score`, including `Longitude` and `UNIX timestamp`, but could never get the bin options to appear.

**Comment by sbelak** [comment]
@leorochael have you tried manually forcing a sync (Admin->Databases)?

**Comment by leorochael** [comment]
@sbelak, yes, I've tried requesting a sync of just the values, of the whole table and of the whole database, to no avail.

I even tried renaming the table so Metabase thinks it's a new table, and still no luck.

**Comment by vblagomir** [comment]
I am using MongoDB, and see no binning at all (neither with generic top-level numbers fields, nor with nested fields, including latitude/longitude etc, whereas sample dataset works).. Does this mean Mongo is not supported for binning?

**Comment by dorringel** [comment]
Same here, Using MongoDB, the field is set to Number in the Data Model, synced in every way possible, still not seeing any option of binning.

**Comment by notrom** [comment]
Same issue here, v0.32.7, Metabase in Postgres, data in SQL Server.

Tried fields set as Number or Latitude/Longitude. Discarded cache and re-scan both at table level and filed. No binning available on that field. 

This is preventing me from using the grid map which would be really useful for my org.

**Comment by notrom** [comment]
I've found an error reported during the schema sync operation, the error appears fatal and is stopping field fingerprints from being created. Binning in the query builder interface appears to use these fingerprints, if they don't exist binning isn't available.

I fudged it by manually inserting a few fingerprint values into the Metabase database, after doing that binning is available on those fields.

I recommend checking your error logs after a sync for errors like those in #10038, if you see them please give that issue a thumbs up, it would be great to get it fixed.

**Comment by tprestonwills** [comment]
I'm also having trouble getting the binning options to appear and get the dreaded error "Grid map requires binned longitude/latitude." I too would find great value in using the grid map.

**Problem description:**
- Metabase does not provide the binning option (or autobin fields) when using the simple or custom question builder.

**Here's the tech info:**
- Metabase v0.34.3
![image](https://user-images.githubusercontent.com/19897230/79817651-95f70080-834b-11ea-861a-efb54a90590d.png)
- MySQL database
- latitude and longitude columns are decimal(8,6) and decimal(9,6) respectively
![image](https://user-images.githubusercontent.com/19897230/79817446-2254f380-834b-11ea-9050-103491de20b2.png)

**Here's what I've done/verified:**
- I can get the grid map to work with the sample data set. It's great and I'd love to use it!
- Searched GitHub and Discourse for an existing solution.
- Used **BOTH** the simple and custom question builders to create a query grouped by latitude and longitude (native query currently not supported by the grid map).
- Verified the latitude and longitude table columns are set to latitude and longitude types in the data model (in the admin section).
![2020-04-20_20h59_09](https://user-images.githubusercontent.com/19897230/79818479-8aa4d480-834d-11ea-8902-abda9881d943.png)
- Discarded cached fields values and re-scanned the table fields in the data model settings for the respective latitude and longitude fields.
- Re-scanned the table.
- Re-scanned the entire database.
- Changed the latitude and longitude table columns to float and retried the above steps. Just for giggles, I changed them to an INT datatype and re-scanned. No dice.

**Outcome:**
None of the above worked. Any thoughts or other trouble shooting steps are much appreciated!

![image](https://user-images.githubusercontent.com/19897230/79820034-e886eb80-8350-11ea-902d-0488ea664f04.png)

![image](https://user-images.githubusercontent.com/19897230/79820057-f2a8ea00-8350-11ea-8160-d7b720cd914f.png)

**Comment by flamber** [comment]
@tprestonwills 
Did you check the log for errors during the sync/scan, like mentioned in https://github.com/metabase/metabase/issues/7782#issuecomment-496871006?
Which version of MySQL?
There's been some changes in 0.35 in regards to fingerprinting, so might be worth testing.

**Comment by JrmyDev** [comment]
Same problem with mongodb database

**Comment by tprestonwills** [comment]
What I eventually landed on with this issue is that it's related to the scanned values. If you have a NULL value or invalid value in the data, it won't autobin for the latitude/longitude type in the metabase data model. With that said, even after I set the default column value to 0 in MySql, updated NULL values to 0, dropped the cache and rescanned the field in the Metabase data model, it still didn't work. I ended up creating a cross reference table and storing latitude/longitude values there. I found it to be a better representation in the data model and had no problem getting it to autobin from the onset. By the way, this was a couple of releases ago in v.034, so it might well be fixed now.

**Comment by JrmyDev** [comment]
@tprestonwills  I'm in  0.37.2 and issue not fixed. I double check, no null or undefined values....
Maybe my longitude/latitude format is not well ?
![image](https://user-images.githubusercontent.com/10810617/99793484-0c99ed80-2b29-11eb-8c69-dc69c5b3c17c.png)

**Comment by flamber** [comment]
It is likely caused by incorrect fingerprinting (most likely from initial data). The workaround is to delete old fingerprints from your database, which will then make Metabase create updated fingerprints, when it sync the database next time.
Make sure you have backups of your application database.
```
UPDATE metabase_field SET fingerprint = NULL, fingerprint_version = 0
```
There's work being done in upcoming versions to have the fingerprints updated automatically.

If that still doesn't work, then please post the output from this request `/api/field/:id`, where :id is the ID of the field, which can be found in the URL, when going to Admin > Data Model > (database) > (table) > (column) :gear:

**Comment by JrmyDev** [comment]
> It is likely caused by incorrect fingerprinting (most likely from initial data). The workaround is to delete old fingerprints from your database, which will then make Metabase create updated fingerprints, when it sync the database next time.
> Make sure you have backups of your application database.
> 
> ```
> UPDATE metabase_field SET fingerprint = NULL, fingerprint_version = 0
> ```
> 
> There's work being done in upcoming versions to have the fingerprints updated automatically.
> 
> If that still doesn't work, then please post the output from this request `/api/field/:id`, where :id is the ID of the field, which can be found in the URL, when going to Admin > Data Model > (database) > (table) > (column) ⚙️

Thanks a lot !! How could I execute this query ? My metabase is installed on a remote server (debian) with original h2 database...

**Comment by flamber** [comment]
@JrmyDev Migrate away from H2: https://www.metabase.com/docs/latest/operations-guide/migrating-from-h2.html
Please use the forum for questions and troubleshooting: https://discourse.metabase.com/

**Comment by JrmyDev** [comment]
@flamber :
I've deleted old fingerprints and resync my database. Doesn't seems to work...
My new fingerprint : 
"fingerprint":{"global":{"distinct-count":3495,"nil%":0.0},"type":{"type/Number":{"min":-149.5613378,"q1":2.1730640031725907,"q3":4.87253769865183,"max":166.4787306,"sd":6.138366334740051,"avg":3.02797091714922}}}

**Comment by dpsutton** [comment]
@JrmyDev what are the column names? We try to infer `:type/Longitude` and `:type/Latitude` from column names with regexes. You can see this in the admin panel if those 

```sql

create table locations2 (name text, location_x double, location_y double);  # note these columns won't be matched
insert into locations2 (name, location_x, location_y) values ('france', 48.5112, 2.2055);
```

when synced, these are not recognized as lat and long columns

## admin panel
<img width="974" alt="image" src="https://user-images.githubusercontent.com/6377293/99832416-1bcb6c00-2b26-11eb-94f6-92797dd0148c.png">

## browse table
<img width="450" alt="image" src="https://user-images.githubusercontent.com/6377293/99832459-2c7be200-2b26-11eb-8f24-a75d7af689dc.png">

in the admin panel you can update them to be lat and long columns

## admin panel marking as lat and long
<img width="957" alt="image" src="https://user-images.githubusercontent.com/6377293/99832520-474e5680-2b26-11eb-93b8-921aa5a4dd1b.png">

and then metabase is aware they are special

## visualizing in the browser
<img width="386" alt="image" src="https://user-images.githubusercontent.com/6377293/99832559-56350900-2b26-11eb-86a7-a985c637c02e.png">

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/6377293/99832586-64832500-2b26-11eb-8bdf-c1c3c5369015.png">


(when i clicked on visualize)

**Comment by JrmyDev** [comment]
@dpsutton : no problem with that, my two field are ok :
![image](https://user-images.githubusercontent.com/10810617/99833562-797da980-2b62-11eb-9eb1-0ee880a9b543.png)

Pin map works well but not the grid one

**Comment by tprestonwills** [comment]
@JrmyDev Here is how I configured the columns for latitute/longitude. What data type are your latitude/longitude table columns? 
![image](https://user-images.githubusercontent.com/19897230/99834153-c17fda80-2b28-11eb-902b-37c92dc3aecb.png)

**Comment by JrmyDev** [comment]
@tprestonwills type Double (mongodb database)

**Comment by JrmyDev** [comment]
any chance to fix this bug ?

**Comment by thunfischtoast** [comment]
I'm experiencing the same issue. I pull the data from MongoDB. Below is the API-Output. The table only has a couple thousand entries and the value range is in the small integers. 

In addition, when I click the "Distribution" button for this column in the table view I get this error: `No method in multimethod '->lvalue' for dispatch value: :binning-strategy`

```
{
  "description": null,
  "database_type": "java.lang.Integer",
  "table_id": 7,
  "table": {
    "description": null,
    "entity_type": "entity/GenericTable",
    "schema": null,
    "db": {
      "description": null,
      "features": [
        "basic-aggregations",
        "nested-fields",
        "native-parameters",
        "case-sensitivity-string-filter-options"
      ],
      "cache_field_values_schedule": "0 0 3 * * ? *",
      "timezone": null,
      "auto_run_queries": true,
      "metadata_sync_schedule": "0 53 * * * ? *",
      "name": "MongoDB",
      "caveats": null,
      "is_full_sync": true,
      "updated_at": "2021-04-07T08:26:45.298888Z",
      "details": {
        "additional-options": null,
        "ssl": false,
        "use-srv": false,
        "authdb": "admin",
        "port": 27017,
        "dbname": "fw",
        "use-connection-uri": false,
        "host": "db",
        "tunnel-enabled": false,
        "pass": "**MetabasePass**",
        "user": "root"
      },
      "is_sample": false,
      "id": 3,
      "is_on_demand": false,
      "options": null,
      "engine": "mongo",
      "refingerprint": null,
      "created_at": "2021-04-07T08:26:45.298888Z",
      "points_of_interest": null
    },
    "show_in_getting_started": false,
    "name": "sessions",
    "caveats": null,
    "updated_at": "2021-04-08T11:47:39.424647Z",
    "entity_name": null,
    "active": true,
    "id": 7,
    "db_id": 3,
    "visibility_type": null,
    "field_order": "database",
    "display_name": "Sessions (Raw)",
    "created_at": "2021-04-07T08:26:45.391306Z",
    "points_of_interest": null
  },
  "special_type": "type/Quantity",
  "name": "entCount",
  "fingerprint_version": 5,
  "has_field_values": "list",
  "settings": null,
  "caveats": null,
  "fk_target_field_id": null,
  "dimensions": [],
  "updated_at": "2021-04-08T11:47:31.812192Z",
  "custom_position": 0,
  "active": true,
  "parent_id": 108,
  "id": 126,
  "last_analyzed": "2021-04-07T08:30:02.598154Z",
  "position": 15,
  "visibility_type": "normal",
  "preview_display": true,
  "display_name": "Ent Count",
  "database_position": 17,
  "name_field": null,
  "fingerprint": {
    "global": {
      "distinct-count": 11,
      "nil%": 0
    },
    "type": {
      "type/Number": {
        "min": 0,
        "q1": 1.04752878927726,
        "q3": 4.8802733415519235,
        "max": 15,
        "sd": 2.6231595747932293,
        "avg": 3.087893864013267
      }
    }
  },
  "created_at": "2021-04-07T08:30:02.598154Z",
  "base_type": "type/Integer",
  "points_of_interest": null
}
```

**Comment by lerela** [comment]
Same issue with a MongoDB collection, field is set to Number in the data model, there never was an incorrect (or even null) value in this field since the database was set up, but no binning is available.

**Comment by HeathLee** [comment]
Same issue with a MongoDB

**Comment by minhpq-vbee** [comment]
I have the same issue with MongoDB. Do you have any plan to fix this soon?

**Comment by camsaul** [comment]
Binning only shows up when we have a fingerprint for that column with a valid min and max, if those are there than things should work correctly.

This might have been fixed recently when we rewrote the binning drill thru code in ClojureScript, or when we fixed various errors related to fingerprinting.

If anyone is still running into this problem on 49+ please chime in and include the `fingerprint` for the column in question

**Comment by thebiglabasky** [comment]
As per Cam's comment above, I'll close this issue for the time being. Feel free to reopen with fresh context if that is still happening so we'll look into it. Thank you

**Comment by hs1999-debug** [comment]
I have done all the steps that are mentioned like change the semantic type to latitude and longitude and all the steps but still I am unable to get the auto-bin option. Please help me out to fix it.

**Comment by thebiglabasky** [comment]
@hs1999-debug Can you elaborate on your specific setup?
An important note is that binning isn't supported on MongoDB, so this issue should be solely about MySQL.
If you want binning on MongoDB, please upvote the following issue: https://github.com/metabase/metabase/issues/45005
