### ISSUE TITLE
Date Filter showing wrong date

### ISSUE THREAD

**Issue by vietvudanh** [metabase/metabase#9222]
Metabase version: 0.31.2 
Hosting on Ubuntu 16.04
MySQL version: 5.6.40
Timezone on server: +7
Timezone on browser: +7
Timezone in Metabase setting: Default (I cannot set, it seem problem with MySQL).

=====

As shown in the picture, the date filter return to me 1 day before the date I choose. The query is at 8:00 UTC, 15:00 +7 so I don't think it's timezone problem.

What can cause this?

![screen shot 2019-01-05 at 3 47 54 pm](https://user-images.githubusercontent.com/4011756/50722475-33e89c80-1102-11e9-8d4d-2fef77742b39.png)

**Comment by atamucci** [comment]
Same problem to the same version.

![Cattura](https://user-images.githubusercontent.com/39536453/54669389-8d514c80-4af1-11e9-9e7f-679a0939de1c.PNG)

Will it be solved with new version?

Thanks

**Comment by tomonetml** [comment]
Good day

could be same as https://github.com/metabase/metabase/issues/8262 ?

Can kindly provide us an ETA for the fix ?

have a nice day
Matteo

**Comment by Ydeluca** [comment]
Hello,
I think that's the same problem as 8262 too.
And i have the same whith mysql database and metabase version v0.32.3

![metabase_date_problem](https://user-images.githubusercontent.com/3486537/57859985-4aaba800-77f4-11e9-8612-86cd6762918a.png)

Thanks

**Comment by vietvudanh** [comment]
Seems no update and still happen. My fix is always need to date_add 01 day. 
And yes, the moment Metabase fix this I will have to change everywhere, which is not cool in anyway...

**Comment by michelzetun** [comment]
Same issue here, 
when using dynamic filter to select the last month (May/2019) the result is fine:
![scrnli_18_06_2019 17-22-39](https://user-images.githubusercontent.com/7318904/59717301-190c6f00-91ee-11e9-8827-72afdd8e4fcb.png)

However, when I select the actual days (May, 1st to May, 31th) I get a different result:

![scrnli_18_06_2019 17-19-39](https://user-images.githubusercontent.com/7318904/59717391-45c08680-91ee-11e9-8906-47dabcfdaea5.png)

In order to fix it, I need to add the time and extend the last day to June, 1st. 
![scrnli_18_06_2019 17-21-23](https://user-images.githubusercontent.com/7318904/59717518-87513180-91ee-11e9-9e9a-b1aa3b79e21b.png)

The data is stored in UTC and my Report Timezone is America/Sao_Paulo (that is usually GMT -3). In my understanding, due to this feature, when I explicitly select the date, Metabase always consider the time to be 00:00:00 and due to the Report Timezone Feature, it always subtracts the number of hours, therefore, selecting other dates to pass as a filter. 

The wrong result is due to the inclusion of the last day of April/19 and the lack of the last day of May/19.

**Comment by walterl** [comment]
It looks like this may have been fixed in recent (timezone?) changes. Could anyone please confirm that this is still occurring?

**Comment by tomonetml** [comment]
Hi @walterl ,

Just tested on 0.33.0 with europe/berlin timezone..seems ok to me

![Cattura](https://user-images.githubusercontent.com/34745293/63572455-33165500-c583-11e9-9bf0-acaf39c8aa0a.PNG)

Maybe @michelzetun can confirm if it's fixed also in the query builder

ty have a nice day
Matteo

**Comment by walterl** [comment]
Thanks for the quick response, @tomonetml :)

**Comment by vietvudanh** [comment]
Can confirm this work. Just remember to set timezone in your connection string to your desire one. Mine is +7.
![Screenshot_20190824_092453](https://user-images.githubusercontent.com/4011756/63631404-4859b500-c651-11e9-861e-3f92d6ac7a8b.png)

**Comment by walterl** [comment]
Thanks, @vietvudanh! Then I'm going to close this issue. If anyone can still reproduce it, please reopen.
