### ISSUE TITLE
Metabase 0.31.2 Dashboard Filters on Linked Entities Broke

### ISSUE THREAD

**Issue by MarkRx** [metabase/metabase#9364]
Dashboard filters don't work if the filter is hooked up to a linked field on a question. This appears to have broke in 0.31. For example hook up a field filter to sample data Order > User (name) against a UI question that pulls from Orders and it will not persist. See https://github.com/metabase/metabase/issues/9364#issuecomment-459831573 for REST API differences between 0.30 and 0.31.

![related_field_filter_broke](https://user-images.githubusercontent.com/17504314/52140453-dbcd8900-2620-11e9-8929-a77318acb6f0.gif)

It looks like the data is being stored and returned differently. 

## 0.30
**PUT: /api/dashboard/<id>**
```
"parameter_mappings": [{
		"parameter_id": "4a02cb9",
		"card_id": 9,
		"target": ["dimension", ["fk->", 9, 20]]
	}
],
```

**GET: /api/dashboard/<id>**
```
"parameter_mappings": [{
		"parameter_id": "4a02cb9",
		"card_id": 9,
		"target": ["dimension", ["fk->", 9, 20]]
	}
],
```

## 0.31.2
**PUT: /api/dashboard/<id>**
```
"parameter_mappings": [{
		"parameter_id": "7d90efa5",
		"card_id": 1230,
		"target": ["dimension", ["fk->", 9, 20]]
	}
],
```

**GET: /api/dashboard/<id>**
```
"parameter_mappings": [{
		"parameter_id": "7d90efa5",
		"card_id": 1230,
		"target": ["dimension", ["fk->", ["field-id", 9], ["field-id", 20]]]
	}
],
```

There is a discrepancy between what the UI expects and what the API returns.
The type system says a [DimensionTarget](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/meta/types/Parameter.js#L26) can be a [ForeignFieldReference](https://github.com/metabase/metabase/blob/master/frontend/src/metabase/meta/types/Query.js#L225).

The UI expects `["fk->", FieldId, FieldId]` 
The API returns `["fk->", ["field-id", FieldId], ["field-id", FieldId]]`

I'm not sure which is correct - the UI or the API. I guess @camsaul or @tlrobinson can answer that.

*Steps To Reproduce*
1. Create a select * UI question on orders and add it to a dashboard
2. Hook up a field filter to Orders > User (name) and save
3. Try the filter. It does not work.
4. Edit the filter again and notice how it never saved.

Your browser and the version: 71.0.3578.98 (Official Build) (64-bit)
Your operating system: Windows 7
Your databases: Oracle 12.2
Metabase version: 0.31.2
Metabase hosting environment: RHEL 7
Metabase internal database: MySQL

**Comment by MarkRx** [comment]
Here are the requests from Metabase 0.30.1. It looks similar so this suggests it is a front end issue.

1. PUT /api/dashboard/3/cards
```
{
	"cards": [{
			"id": 7,
			"card_id": 9,
			"row": 0,
			"col": 0,
			"sizeX": 12,
			"sizeY": 7,
			"series": [],
			"visualization_settings": {},
			"parameter_mappings": [{
					"parameter_id": "4a02cb9",
					"card_id": 9,
					"target": ["dimension", ["fk->", 9, 20]]
				}
			]
		}
	]
}
```

2. PUT /api/dashboard/3
```
{
	"description": null,
	"archived": false,
	"collection_position": null,
	"ordered_cards": [{
			"sizeX": 12,
			"series": [],
			"card": {
				"description": null,
				"archived": false,
				"collection_position": null,
				"table_id": 2,
				"result_metadata": [{
						"name": "ID",
						"display_name": "ID",
						"description": "This is a unique ID for the product. It is also called the “Invoice number” or “Confirmation number” in customer facing emails and screens.",
						"base_type": "type/BigInteger",
						"special_type": "type/PK",
						"fingerprint": {
							"global": {
								"distinct-count": 10000
							},
							"type": {
								"type/Number": {
									"min": 1,
									"max": 10000,
									"avg": 5000.5
								}
							}
						}
					}, {
						"name": "CREATED_AT",
						"display_name": "Created At",
						"description": "The date and time an order was submitted.",
						"base_type": "type/DateTime",
						"special_type": "type/CreationTimestamp",
						"unit": "default",
						"fingerprint": {
							"global": {
								"distinct-count": 1387
							},
							"type": {
								"type/DateTime": {
									"earliest": "2016-04-30T04:00:00.000Z",
									"latest": "2020-04-19T04:00:00.000Z"
								}
							}
						}
					}, {
						"name": "DISCOUNT",
						"display_name": "Discount",
						"description": "Discount amount.",
						"base_type": "type/Float",
						"special_type": "type/Discount",
						"fingerprint": {
							"global": {
								"distinct-count": 700
							},
							"type": {
								"type/Number": {
									"min": 0.17088996672584322,
									"max": 61.69684269960571,
									"avg": 5.161255547580321
								}
							}
						}
					}, {
						"name": "PRODUCT_ID",
						"display_name": "Product ID",
						"description": "The product ID. This is an internal identifier for the product, NOT the SKU.",
						"base_type": "type/Integer",
						"special_type": "type/FK",
						"fingerprint": {
							"global": {
								"distinct-count": 200
							},
							"type": {
								"type/Number": {
									"min": 1,
									"max": 200,
									"avg": 100.5084
								}
							}
						}
					}, {
						"name": "QUANTITY",
						"display_name": "Quantity",
						"description": "Number of products bought.",
						"base_type": "type/Integer",
						"special_type": "type/Quantity",
						"fingerprint": {
							"global": {
								"distinct-count": 62
							},
							"type": {
								"type/Number": {
									"min": 0,
									"max": 100,
									"avg": 3.7015
								}
							}
						}
					}, {
						"name": "SUBTOTAL",
						"display_name": "Subtotal",
						"description": "The raw, pre-tax cost of the order. Note that this might be different in the future from the product price due to promotions, credits, etc.",
						"base_type": "type/Float",
						"fingerprint": {
							"global": {
								"distinct-count": 340
							},
							"type": {
								"type/Number": {
									"min": 15.691943673970439,
									"max": 148.22900526552291,
									"avg": 77.01295465356537
								}
							}
						},
						"special_type": null
					}, {
						"name": "TAX",
						"display_name": "Tax",
						"description": "This is the amount of local and federal taxes that are collected on the purchase. Note that other governmental fees on some products are not included here, but instead are accounted for in the subtotal.",
						"base_type": "type/Float",
						"fingerprint": {
							"global": {
								"distinct-count": 797
							},
							"type": {
								"type/Number": {
									"min": 0,
									"max": 11.12,
									"avg": 3.8722099999999875
								}
							}
						},
						"special_type": null
					}, {
						"name": "TOTAL",
						"display_name": "Total",
						"description": "The total billed amount.",
						"base_type": "type/Float",
						"special_type": "type/Income",
						"fingerprint": {
							"global": {
								"distinct-count": 10000
							},
							"type": {
								"type/Number": {
									"min": 12.061602936923117,
									"max": 238.32732001721533,
									"avg": 82.96014815230829
								}
							}
						}
					}, {
						"name": "USER_ID",
						"display_name": "User ID",
						"description": "The id of the user who made this order. Note that in some cases where an order was created on behalf of a customer who phoned the order in, this might be the employee who handled the request.",
						"base_type": "type/Integer",
						"special_type": "type/FK",
						"fingerprint": {
							"global": {
								"distinct-count": 929
							},
							"type": {
								"type/Number": {
									"min": 1,
									"max": 1322,
									"avg": 678.6893
								}
							}
						}
					}
				],
				"database_id": 1,
				"enable_embedding": false,
				"collection_id": null,
				"query_type": "query",
				"name": "Orders",
				"read_permissions": null,
				"query_average_duration": 54,
				"creator_id": 1,
				"updated_at": "2019-02-01T18:14:54.295Z",
				"made_public_by_id": null,
				"embedding_params": null,
				"cache_ttl": null,
				"dataset_query": {
					"database": 1,
					"type": "query",
					"query": {
						"source_table": 2
					}
				},
				"id": 9,
				"display": "table",
				"visualization_settings": {},
				"created_at": "2019-02-01T18:14:46.462Z",
				"public_uuid": null
			},
			"updated_at": "2019-02-01T18:15:41.644Z",
			"col": 0,
			"id": 7,
			"parameter_mappings": [{
					"parameter_id": "4a02cb9",
					"card_id": 9,
					"target": ["dimension", ["fk->", 9, 20]]
				}
			],
			"card_id": 9,
			"visualization_settings": {},
			"dashboard_id": 3,
			"created_at": "2019-02-01T18:14:57.463Z",
			"sizeY": 7,
			"row": 0,
			"isDirty": true
		}
	],
	"can_write": true,
	"enable_embedding": false,
	"collection_id": null,
	"show_in_getting_started": false,
	"name": "Orders Filter",
	"caveats": null,
	"creator_id": 1,
	"updated_at": "2019-02-01T18:15:41.690Z",
	"made_public_by_id": null,
	"embedding_params": null,
	"position": null,
	"parameters": [{
			"name": "Category",
			"slug": "category",
			"id": "4a02cb9",
			"type": "category"
		}
	],
	"created_at": "2019-02-01T18:14:53.959Z",
	"public_uuid": null,
	"points_of_interest": null
}

```

**Comment by MarkRx** [comment]
It looks like the data is being stored and returned differently. 

**0.30**
PUT: /api/dashboard/<id>
```
"parameter_mappings": [{
					"parameter_id": "4a02cb9",
					"card_id": 9,
					"target": ["dimension", ["fk->", 9, 20]]
				}
			],
```

GET: /api/dashboard/<id>
```
"parameter_mappings": [{
					"parameter_id": "4a02cb9",
					"card_id": 9,
					"target": ["dimension", ["fk->", 9, 20]]
				}
			],
```


**0.31**
PUT: /api/dashboard/<id>
```
"parameter_mappings": [{
					"parameter_id": "7d90efa5",
					"card_id": 1230,
					"target": ["dimension", ["fk->", 9, 20]]
				}
			],
```

[{"parameter_id":"cab2683c","card_id":1465,"target":["dimension",["fk->",["field-id",297],["field-id",380]]]}]
GET: /api/dashboard/<id>
```
"parameter_mappings": [{
					"parameter_id": "7d90efa5",
					"card_id": 1230,
					"target": ["dimension", ["fk->", ["field-id", 9], ["field-id", 20]]]
				}
			],
```

**Comment by nickhamlin** [comment]
I just ran into an issue that I *think* is related to this - If you have a dashboard that accepts a unique ID as a filter parameter on a field that is a Foreign Key to another table, it now fails where it didn't used to. The logs contain a `Query failure: Unknown column 'field' in 'where clause'`. There are other issues like https://github.com/metabase/metabase/issues/9391 that reference similar behavior when using field filters in custom SQL questions, but I'm seeing this on questions created in the query builder, which I believe is more inline with this issue. Would love to have this working again, since many members of our team rely on dashboards that had been using this feature in the past!

**Comment by flamber** [comment]
Hi @nickhamlin 
#9391 is an issue about aliases. Your issue sounds very similar to #9017, which was fixed in 0.31.2

**Comment by nickhamlin** [comment]
Thanks @flamber, that's definitely the one I was trying to find. I'll give the update a shot. Much appreciated!

**Comment by tlrobinson** [comment]
@camsaul I think part of the correct fix is to normalize MBQL in the backend, even in dashboard `parameter_mappings` and card `parameters`.

**Comment by jlisyc** [comment]
Hi all, Is there a milestone for this? Could be 0.33? Thanks a lot.

**Comment by joboyx** [comment]
This is still occurring and a dealbreaker in v0.32.X :|

It's really hard to maintain and create dashboards with this issue.

Guys, please like/thumbsup/+1 (:+1:) the main comment so this gets prioritized. Thanks.

**Comment by jlisyc** [comment]
Hi,
Have you got a release decided to fix this issue?

**Comment by flamber** [comment]
@jlisyc Paul (:rocket:) has already made a fix for this (10 days ago), so I would guess it's going into next release, but that's not guaranteed, since the team is very busy trying to finish 0.33

**Comment by jlisyc** [comment]
Great. Thanks a lot.

**Comment by salsakran** [comment]
Hello all, this is fixed in 0.32.10 which just went out.
