### ISSUE TITLE
[0.32.0-RC2] liquibase.exception.ValidationFailedException: Validation Failed: migrations/000_migrations.yaml

### ISSUE THREAD

**Issue by flamber** [metabase/metabase#9612]
I just tried to upgrade to 0.32.0-RC2 from 0.31.2 and got this error ([full log](https://github.com/metabase/metabase/files/3006835/log.txt)):
```
ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          migrations/000_migrations.yaml::10::cammsaul was: 8:5297214d1788d964675d8c6336ac9b6d but is now: 8:96e54d9100db3f9cdcc00eaeccc200a3
```
Metabase 0.31.2 JAR with internal MariaDB on Ubuntu 16.04
@camsaul Do you need anything else? I reverted to 0.31.2, but can try again tomorrow night.

**Comment by mayconbordin** [comment]
I ran into the same issue today. First I tried to force the migration:

`java -jar metabase-v0.32.0-RC2.jar migrate force`

After that I tried to start the server and ran into another issue:

```
03-27 07:48:16 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::99::camsaul failed.  Error: (conn=764026) Duplicate key name 'idx_uniq_field_table_id_parent_id_name' [Failed SQL: ALTER TABLE mbasedb.metabase_field ADD CONSTRAINT idx_uniq_field_table_id_parent_id_name UNIQUE (table_id, parent_id, name)]
03-27 07:48:16 WARN metabase.util :: auto-retry metabase.db$run_schema_migrations_BANG_$fn__14466@3d072a74: Migration failed for change set migrations/000_migrations.yaml::99::camsaul:
     Reason: liquibase.exception.DatabaseException: (conn=764026) Duplicate key name 'idx_uniq_field_table_id_parent_id_name' [Failed SQL: ALTER TABLE mbasedb.metabase_field ADD CONSTRAINT idx_uniq_field_table_id_parent_id_name UNIQUE (table_id, parent_id, name)]
03-27 07:48:16 INFO metabase.db :: Setting up Liquibase...
03-27 07:48:16 INFO metabase.db :: Liquibase is ready.
03-27 07:48:16 INFO metabase.db :: Checking if Database has unrun migrations...
03-27 07:48:17 INFO metabase.db :: Database has unrun migrations. Waiting for migration lock to be cleared...
03-27 07:48:17 INFO metabase.db :: Migration lock is cleared. Running migrations...
03-27 07:48:17 ERROR changelog.ChangeSet :: Change Set migrations/000_migrations.yaml::99::camsaul failed.  Error: (conn=764028) Duplicate key name 'idx_uniq_field_table_id_parent_id_name' [Failed SQL: ALTER TABLE mbasedb.metabase_field ADD CONSTRAINT idx_uniq_field_table_id_parent_id_name UNIQUE (table_id, parent_id, name)]
03-27 07:48:17 ERROR metabase.core :: Metabase Initialization FAILED
liquibase.exception.MigrationFailedException: Migration failed for change set migrations/000_migrations.yaml::99::camsaul:
     Reason: liquibase.exception.DatabaseException: (conn=764028) Duplicate key name 'idx_uniq_field_table_id_parent_id_name' [Failed SQL: ALTER TABLE mbasedb.metabase_field ADD CONSTRAINT idx_uniq_field_table_id_parent_id_name UNIQUE (table_id, parent_id, name)]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at metabase.db$migrate_up_if_needed_BANG_.invokeStatic(db.clj:209)
	at metabase.db$migrate_up_if_needed_BANG_.invoke(db.clj:196)
	at metabase.db$migrate_BANG_$fn__14448.invoke(db.clj:313)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:799)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:834)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:782)
	at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:769)
	at metabase.db$migrate_BANG_.invokeStatic(db.clj:301)
	at metabase.db$migrate_BANG_.invoke(db.clj:282)
	at metabase.db$run_schema_migrations_BANG_$fn__14466.invoke(db.clj:446)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:428)
	at metabase.util$do_with_auto_retries.invoke(util.clj:420)
	at metabase.util$do_with_auto_retries.invokeStatic(util.clj:432)
	at metabase.util$do_with_auto_retries.invoke(util.clj:420)
	at metabase.db$run_schema_migrations_BANG_.invokeStatic(db.clj:445)
	at metabase.db$run_schema_migrations_BANG_.invoke(db.clj:428)
	at metabase.db$setup_db_BANG_$fn__14475.invoke(db.clj:468)
	at metabase.util$do_with_us_locale.invokeStatic(util.clj:683)
	at metabase.util$do_with_us_locale.invoke(util.clj:669)
	at metabase.db$setup_db_BANG_.invokeStatic(db.clj:466)
	at metabase.db$setup_db_BANG_.doInvoke(db.clj:460)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at metabase.core$init_BANG_.invokeStatic(core.clj:72)
	at metabase.core$init_BANG_.invoke(core.clj:51)
	at metabase.core$start_normally.invokeStatic(core.clj:118)
	at metabase.core$start_normally.invoke(core.clj:112)
	at metabase.core$_main.invokeStatic(core.clj:138)
	at metabase.core$_main.doInvoke(core.clj:133)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at metabase.core.main(Unknown Source)
Caused by: liquibase.exception.DatabaseException: (conn=764028) Duplicate key name 'idx_uniq_field_table_id_parent_id_name' [Failed SQL: ALTER TABLE mbasedb.metabase_field ADD CONSTRAINT idx_uniq_field_table_id_parent_id_name UNIQUE (table_id, parent_id, name)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 39 more
Caused by: java.sql.SQLSyntaxErrorException: (conn=764028) Duplicate key name 'idx_uniq_field_table_id_parent_id_name'
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:236)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:356)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:407)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
	... 44 more
Caused by: java.sql.SQLException: Duplicate key name 'idx_uniq_field_table_id_parent_id_name'
Query is: ALTER TABLE mbasedb.metabase_field ADD CONSTRAINT idx_uniq_field_table_id_parent_id_name UNIQUE (table_id, parent_id, name)
java thread: main
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:126)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:222)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:350)
	... 46 more
```

To solve this issue I had to drop the index and start the server again:

`ALTER TABLE metabase_field DROP INDEX  idx_uniq_field_table_id_parent_id_name;`

As far as I've tested everything is fine, but I would wait until the final version comes out to upgrade in production.

**Comment by camsaul** [comment]
@flamber @mayconbordin sorry you've ran into this issue. I've fixed it in #9619. A while back I fixed some syntax errors in our YAML DB migrations file and I had to update the valid checksums list for each DB migration, however this migration differs based on what DBMS you're using and I missed updating the checksums for MySQL/MariaDB. I don't think you should see any more issues like this but there's a small chance some other migrations might need to be fixed too so if you can test the fix it would be super helpful.

I'm not sure whether or not we'll be releasing another RC build before we push out the final version of 0.32.0. or not, so if either of you has run Metabase directly from the source code (as opposed to a built artifact like a JAR or Docker image) I'd love to see if this fixes your issues. If not please let me know and I can get you a custom build so you can try it out.

Thanks
Cam

**Comment by flamber** [comment]
@camsaul Thanks for the fast fix! I can make a JAR build from master, it just takes an hour to build on my computer. Then I can try to migrate again in about 12 hours, when it's off-hours.

**Comment by camsaul** [comment]
Ok, thanks @flamber. If you've recently built `master` on your computer you can run `lein uberjar` instead of the full build script which will repackage things with the updated file in there. That should only take a few minutes.

Alternatively you can take the RC2 JAR and unzip it, replace `migrations/000_migrations.yaml` with the (updated file)[https://raw.githubusercontent.com/metabase/metabase/master/resources/migrations/000_migrations.yaml], and zip it back up. A JAR file is really just a ZIP file under the hood.

Thanks!
Cam

**Comment by on99** [comment]
I think the issue is still there, I cannot upgrade from v0.31.1 to `master` by `docker build && docker run`

**Comment by flamber** [comment]
@camsaul 
I've just upgraded with success - thank you :clap:
I decided to use 0.32.0-RC2.jar, unzip it, replace `migrations/000_migrations.yaml`, remove all the drivers I don't need in `modules/*`, then zip it back up.
Here's [the log](https://github.com/metabase/metabase/files/3016117/0.32-RC2-modified-000_migrations.txt) just for comparison.

@on99 
Can you verify that you have the updated `migrations/000_migrations.yaml` before building.

**Comment by on99** [comment]
@flamber I am sure the 000_migrations.yaml file is updated in my local environment because I already run `git pull --rebase` and double check the commits, however the docker image i built may not contain the update.

Steps:
```
# local
$ git pull --rebase
$ docker build -t metabase.docker .
$ scp metabase.docker to our production server
```
```
# production server
$ docker rmi metabase.docker
$ docker load -i metabase.docker
$ docker run --name metabase metabase.docker # with some environment variables like mysql credentials, not listed here
```

I try to unzip the metabase.jar in docker image, and double check `000_migrations.yaml`, well, it's not updated yet, don't know why

**Comment by on99** [comment]
@camsaul Any idea about it? How can we make docker image work? Thank you for help!

**Comment by on99** [comment]
sorry i run a clean build and it works, should be something wrong with the cache.

**Comment by camsaul** [comment]
Yeah you have to rebuild the JAR before you rebuild the docker image. Good to hear it's working.
