### ISSUE TITLE
Intermittent errors when loading dashboards with filters

### ISSUE THREAD

**Issue by gvisniuc** [metabase/metabase#9955]
Hi there,

Recently I have upgraded from version **0.31.2** to **0.32.0** then to **0.32.7** and have been experiencing intermittent failures in loading data while accessing 
some of the dashboards that use filters.

There are no errors in the application logs nor in the browser errors.
Upon inspection of the query request for some of the questions in the `data.columns` object I can see either of the 2 following errors:

- `Java.sql.sqlexception: [amazon][jdbc](10940) Invalid Parameter Index: 7.`
- `java.sql.SQLNonTransientException: [Amazon][JDBC](10900) Not all parameters have been populated.`

I have tried duplication the dashboard, recreating the dashboard, recreating the questions, adding or removing filters but with no success.

What would be the recommendation in this case? Does it make sense to regress to **0.31.2**?

Thanks!

Your browser and the version: Chrome 74.x
Your operating system: macOS Mojave
Your databases: Redshift
Metabase version: 0.32.7
Metabase hosting environment: Official Metabase Docker image running in Kubernetes.
Metabase internal database: AWS RDS Postgres

⬇️ Please click the 👍 reaction instead of leaving a +1 or 👍 comment

**Comment by camsaul** [comment]
Hi @gvisniuc, did you see these issues in 32.0? We upgraded our Redshift JDBC driver version in 0.32.7 which would explain bugs if they just started happening there.

**Comment by gvisniuc** [comment]
Hi @camsaul, no not in 32.0 with the exception of a few minor incidents whether a question in a dashboard would say it's still loading even though it has loaded previously almost instantly.
In any case I did not see any of these error messages.
Please let me know if I can help with anything else (log dumps, config, etc)

**Comment by TrineFN** [comment]
I'm experiencing the same in version 0.32.8
![image](https://user-images.githubusercontent.com/24959279/58428713-a6ebb300-80a3-11e9-8284-a70ffee7109a.png)

--
Your browser and the version: Chrome 74
Your operating system: macOS Mojave
Your databases: Redshift
Metabase version: 0.32.8
Metabase Hosting Environment: AWS EBS
Metabase Internal Database: Postgres 10.6

**Comment by alexthn** [comment]
We are also experiencing the same issue in version 0.32.8 (and earlier 0.32.x versions). This happens quite often, like 1 time in every 3 dashboard views or so.

> Jun 07 11:36:52 ERROR metabase.middleware.log :: POST /api/card/25/query 500 24 ms (3 DB calls) 
> {:message "(conn=621007) Broken pipe (Write failed)",
> :type java.sql.SQLNonTransientConnectionException,
> :stacktrace
> ("org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:234)"
> "org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:165)"
> "org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)"
> "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:232)"
> "org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:159)"
> "org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:174)"
> "com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:379)"
> "clojure.java.jdbc$execute_query_with_params.invokeStatic(jdbc.clj:1072)"
> "clojure.java.jdbc$execute_query_with_params.invoke(jdbc.clj:1066)"
> "clojure.java.jdbc$db_query_with_resultset_STAR_.invokeStatic(jdbc.clj:1095)"
> "clojure.java.jdbc$db_query_with_resultset_STAR_.invoke(jdbc.clj:1075)"
> "clojure.java.jdbc$query.invokeStatic(jdbc.clj:1164)"
> "clojure.java.jdbc$query.invoke(jdbc.clj:1126)"
> "toucan.db$query.invokeStatic(db.clj:274)"
> "toucan.db$query.doInvoke(db.clj:270)"
> "clojure.lang.RestFn.invoke(RestFn.java:410)"
> "--> models.user$permissions_set.invokeStatic(user.clj:280)"
> "models.user$permissions_set.invoke(user.clj:272)"
> "middleware.session$do_with_current_user$fn__58588.invoke(session.clj:175)"
> "models.interface$current_user_permissions_set.invokeStatic(interface.clj:234)"
> "models.interface$current_user_permissions_set.invoke(interface.clj:234)"
> "models.interface$make_perms_check_fn$_has_perms_QMARK___24078.invoke(interface.clj:249)"
> "models.interface$make_perms_check_fn$_has_perms_QMARK___24078.invoke(interface.clj:247)"
> "models.interface$fn__24013$G__24004__24022.invoke(interface.clj:181)"
> "api.common$read_check.invokeStatic(common.clj:367)"
> "api.common$read_check.invoke(common.clj:360)"
> "api.card$run_query_for_card_async.invokeStatic(card.clj:618)"
> "api.card$run_query_for_card_async.doInvoke(card.clj:610)"
> "api.card$fn__44661$fn__44664.invoke(card.clj:632)"
> "api.card$fn__44661.invokeStatic(card.clj:631)"
> "api.card$fn__44661.invoke(card.clj:627)"
> "middleware.auth$enforce_authentication$fn__59926.invoke(auth.clj:14)"
> "routes$fn__61084$fn__61085.doInvoke(routes.clj:56)"
> "middleware.exceptions$catch_uncaught_exceptions$fn__60017.invoke(exceptions.clj:104)"
> "middleware.exceptions$catch_api_exceptions$fn__60014.invoke(exceptions.clj:92)"
> "middleware.log$log_api_call$fn__61458$fn__61459.invoke(log.clj:170)"
> "middleware.log$log_api_call$fn__61458.invoke(log.clj:164)"
> "middleware.security$add_security_headers$fn__59980.invoke(security.clj:105)"
> "middleware.json$wrap_json_body$fn__61163.invoke(json.clj:61)"
> "middleware.json$wrap_streamed_json_response$fn__61181.invoke(json.clj:97)"
> "middleware.session$bind_current_user$fn__58593$fn__58594.invoke(session.clj:193)"
> "middleware.session$do_with_current_user.invokeStatic(session.clj:176)"
> "middleware.session$do_with_current_user.invoke(session.clj:170)"
> "middleware.session$bind_current_user$fn__58593.invoke(session.clj:192)"
> "middleware.session$wrap_current_user_id$fn__58582.invoke(session.clj:161)"
> "middleware.session$wrap_session_id$fn__58567.invoke(session.clj:123)"
> "middleware.auth$wrap_api_key$fn__59934.invoke(auth.clj:27)"
> "middleware.misc$maybe_set_site_url$fn__61523.invoke(misc.clj:58)"
> "middleware.misc$bind_user_locale$fn__61526.invoke(misc.clj:74)"
> "middleware.misc$add_content_type$fn__61511.invoke(misc.clj:30)"
> "middleware.misc$disable_streaming_buffering$fn__61548.invoke(misc.clj:119)"
> "middleware.misc$wrap_gzip$fn__61541.invoke(misc.clj:101)"),
> :sql-exception-chain ["SQLNonTransientConnectionException:" "Message: (conn=621007) Broken pipe (Write failed)" "SQLState: 08" "Error Code: 0"]}

If you need logs or details let me know I would be happy to provide them.

Your browser and the version: Chrome 74
Your operating system: Windows 10
Your databases: MySQL
Metabase version: 0.32.8
Metabase Hosting Environment: Local VMWare VM, Debian 9.9, Docker
Metabase Internal Database: MySQL

**Comment by flamber** [comment]
Hi @alexthn I think you're seeing #9989 - but they are more likely related.

**Comment by botchniaque** [comment]
According to [this stackoverflow answer](https://stackoverflow.com/a/53131686/1680826) there is a thread safety problem with certain Redshift driver versions. 

Metabase 0.31.2 uses: 1.2.12.1017
Metabase 0.32.9 uses: 1.2.27.1051

Which is coherent to what SO post mentions. 

Was there a reason why Redshift driver was updated other then hygiene and trying to stay up to date?

**Comment by flamber** [comment]
Nice find @botchniaque. Driver updated in PR #9922 
Looking at the SO, someone says that setting the pool to 1 fixes the issue (of course severely impacting performance from the default 15 connections). Just interested if this could be a work-around.
I have no idea if it actually works, but reading through #9788, it looks like you can send parameter that changes the maximum pool size of [c3p0](https://www.mchange.com/projects/c3p0/#maxPoolSize):
```
java -Dc3p0.maxPoolSize=1 -jar metabase.jar
```

**Comment by gvisniuc** [comment]
@flamber I tested this solution since in my case it was breaking a lot of dashboards and it seems to have fixed the issue. 

I've been monitoring the resource usage, output logs and Redshift cluster status and there seems to be nothing unusual atm. I will continue to monitor for performance degradation.

I am using the helm chart and have used set the parameter `javaToolOptions: -Dc3p0.maxPoolSize=1` .

Unrelated issue, I have 3 pods running Metabase and after a period of time (±24hours) one of the pods seems to be very memory intensive (2gb usage) versus the other 2 which seem to use only 1gb. If you have any suggestions they're more than welcome.

**Comment by flamber** [comment]
@gvisniuc That's great. Please keep monitoring and report back no matter if it still works or not.
As for the memory issue, I'm not sure, so I'm hoping @camsaul can give you some hints.
(By the way Cam, doesn't the maxPoolSize parameter kinda fix #2172?)

**Comment by gvisniuc** [comment]
@flamber update. after aprox 30 minutes the Redshift cluster become almost unreachable due to a spikes in CPU and network throughput.

![image](https://user-images.githubusercontent.com/1614747/60330570-0d117180-9993-11e9-9c63-ca0a8f035297.png)

After reverting the fix it became stable again with the same number of queries running, so for now I would advise against using the parameter based on my personal experience.

**Comment by botchniaque** [comment]
I reached out to Amazon regarding the _thread safety problems with redshift driver_. This is the answer from June 29th I got:

> Please note that this issue will be fixed in the driver release "1.2.32.1056", which is expected to release next week. I will notify you once driver "1.2.32.1056" is published for download [1] .

I also asked whether reverting to older driver version is a valid approach: 
> Regarding your query on any other driver is thread safe - development team noted that driver version "1.2.10.1009" doesn't cause "Not all parameters have been populated" error. Older drivers are compatible but support for newer features and fixes aren’t available. For example  -  Amazon Redshift stored procedures.  Therefore it is recommend to use latest driver.


So it looks promising. One week is over now, and the driver has not yet been released, but once it is I will let you guys know. I am also happy to test the fix in our environment where the problem was very visible.

**Comment by botchniaque** [comment]
The new driver version (**1.2.32.1056**) has beed made available for download today:
 https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.32.1056/RedshiftJDBC42-no-awssdk-1.2.32.1056.jar

[release notes](https://s3.amazonaws.com/redshift-downloads/drivers/Amazon+Redshift+JDBC+Release+Notes.pdf) claim to have fixed the concurrency issues:

> Resolved Issues
The following issues were resolved in Amazon Redshift JDBC Driver 1.2.32.
> - PreparedStatement parameters in some multi-threaded environments are
not correctly populated.
> - In some cases, the driver fails to connect when using Okta and the Oracle
SQL Developer client application.
> - Stored procedure calls with the syntax ? = call [sp_name] are not
parsed correctly.
> - In some cases, parameters are not bound correctly for stored procedures that
only have IN parameters.
> - In some cases, quotation marks ( " ) are not escaped correctly.
> - In cases where there are multiple stored procedures with the same name,
and the user calls one of them, the driver picks the first one in the list.
This issue has been resolved. In this situation, the driver now displays an
error stating that there are multiple stored procedures with that name, and the
query fails.

I would be happy to test the new driver if a Docker image was available.

**Comment by botchniaque** [comment]
Any update on this? I am more than happy to test a 0.32.x compatible release with updated redshift driver, if there was a docker image available.

**Comment by gvisniuc** [comment]
@botchniaque It looks like it will be fixed and released with 0.33.

**Comment by GitsMcGee** [comment]
Hi all. Just tried against 0.33.0-RC1 and am still seeing this issue. Looks like the fix wasn't merged yet? Will it make it into RC2? I'd love to test it out.

**Comment by botchniaque** [comment]
I am confused - Apparently Metabase 0.33.0 was released yesterday. This issue has a Milestone 0.33 assigned, it's marked as `Priority 1`, `Bug` and it did not make it to 0.33 release. 

Also the fix for this issue seems to be straight forward - use a different redshift driver version. I even provided a PR for that. 

When can we expect a fix for that? We're stuck with version `0.31.2`, because all above releases are broken with redshift - I am pretty sure it's not only us.

**Comment by gvisniuc** [comment]
@botchniaque same here, I was checking this exact same thing today but it did not make it into the 0.33 release.

We are currently also running version 0.32.10 but the problem is still persisting. Users are currently just tolerating it and using the individual questions view to bypass this.

Wish we could help somehow.

**Comment by fx** [comment]
@botchniaque we're running a fork w/ your jdbc bump patch. It's not just you.

The [0.33 milestone](https://github.com/metabase/metabase/milestone/75) has 48 open issues, `59% complete`. Safe to say they're not a good indicator of what will make it into a release. I'd wager someone will jump in and just bulk move any open issues to 0.34 now.

**Comment by mazameli** [comment]
There are definitely items we'd hoped to get into 0.33 which we obviously didn't, but we're already hard at work on a 0.33.1 release where we're aiming to tackle as many high priority bug fixes and issues as we can.

**Comment by fx** [comment]
Thanks for the update @mazameli, let's hope it makes it into 0.33.1 :)

In the meantime, anyone wanting to run bleeding edge metabase w/ @botchniaque's JDBC patch applied, we have a public docker image: 

https://hub.docker.com/r/popdog/metabase
https://github.com/godpop/metabase

I'll push a build of current master in a bit.

**Comment by botchniaque** [comment]
Since the PR updating the Redshift driver version is already merged, is this issue considered fixed? 

I know it's not battle tested yet, but then I believe the issue could be re-opened if the new driver was not a solution to it.

**Comment by gvisniuc** [comment]
@botchniaque good call, I will close the issue and indeed reopen it when if that is the case. Thank you everyone for your assistance.

**Comment by ljrjain** [comment]
Hi gvisniuc, I have upgraded the Redshift JDBC driver to 1.2.32.1056. However I can still the the issue.
exception: "[Amazon][JDBC](10900) Not all parameters have been populated."
Can we please reopen the ticket.

**Comment by flamber** [comment]
@ljrjain Which version of Metabase? The fix is included since 0.33.2

**Comment by gvisniuc** [comment]
@ljrjain basically what @flamber mentioned I did not have any errors since 0.33.2, I am running 0.33.3 right now and everything works fine.

**Comment by ljrjain** [comment]
yes it is working, it was issue at my end. thank you for response.
